### ISSUE TITLE
Should the x,y, a, b, c, d, strings be translatable?

### ISSUE THREAD

**Issue by veillette** [phetsims/vector-addition#10]
The simulation  graphing quadratics has numerous one mathematical character strings that are similar to vector addition, namely, x,y, a, b. c.  All of these strings exist in a .json file that allowed them to be potentially translated in various locales. There are currently 26 translations of  graphings lines, and  including many non european languages such as korean, japanese, chinese, tamil, vietnamese and russian.

Out of the 26 simulations, all of them translated the strings  x,y,a,b,c as x,y,a,b,c (no changes). In light of this, should we make these string translatable? This is related to issue #2 as FormulaNode does not  handle translated strings (see https://github.com/phetsims/scenery/issues/457).

**Comment by veillette** [comment]
In the design meeting, we agreed that x,y should be translatable but the vector names (a,b,c, etc) are not translatable. The rational is that a,b,c, are simply generic labels  that exist merely to be able to distinguish them from one another.

**Comment by brandonLi8** [comment]
Related to https://github.com/phetsims/scenery/issues/457#issuecomment-156634759
