### ISSUE TITLE
reuse GridCheckbox from graphing-lines

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/vector-addition#104]
Vector Addition and Graphing Lines both have this checkbox:

<img width="74" alt="screenshot_1321" src="https://user-images.githubusercontent.com/3046552/63135741-2c3c8080-bf8c-11e9-9ac9-25a18dc1e099.png">

Generalize `GRAPHING_LINES/GridCheckbox`, move it to scenery-phet, and use it in vector-addition.  

The code to replace in vector-addition is in GraphControlPanel.js:

```js
      // Grid Icon
      panelContent.push( new Checkbox( VectorAdditionIconFactory.createGridIcon(),
        gridVisibleProperty,
        CHECKBOX_OPTIONS ) );
```

**Comment by pixelzoom** [comment]
GridCheckbox was generalized, converted to ES6, and migrated to scenery-phet.  It is used in graphing-lines and vector-addition.  The before/after look and behavior is unchanged in both sims.  

@ariel-phet if you'd like to have someone review GridCheckbox, please assign.  Otherwise close.

**Comment by ariel-phet** [comment]
I think this issue is safe to close @pixelzoom
