### ISSUE TITLE
sum vector can be off the graph

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/vector-addition#106]
The sum vector s&#8407; (and its components) can be off the graph. I can't think of a better way to handle this.  But I wanted to verify that this behavior is both known and desired.

To reproduce:
1. Go to _Explore 2D_ screen.
2. Select the Components radio button for projections on axes.
3. Drag out a&#8407;, put it near origin.
4. Check the "Sum" checkbox.
5. Move s&#8407; to the upper-right corner of the graph. Screenshot:

<img width="1090" alt="screenshot_1331" src="https://user-images.githubusercontent.com/3046552/63298364-84c39480-c290-11e9-82ed-e85b5965dbaf.png">

6. Increase the length of a&#8407;.  Note that s&#8407; and its component projections are way off the graph.  Screenshot:

<img width="1091" alt="screenshot_1332" src="https://user-images.githubusercontent.com/3046552/63298399-99a02800-c290-11e9-82ea-6b3cb6bb5bca.png">

7. Click on s&#8407;. On pointer down, it immediately jumps back inside the bounds of the graph.  Screenshot:

<img width="1091" alt="screenshot_1333" src="https://user-images.githubusercontent.com/3046552/63298432-ade42500-c290-11e9-877e-0aa3989dce59.png">

**Comment by brandonLi8** [comment]
@pixelzoom this was discussed at my last design meeting [here].(https://docs.google.com/document/d/1opnDgqIqIroo8VK0CbOyQ5608_g11MSGZXnFlI8k5Ds/edit?ts=5ced51e9#bookmark=id.obbjd3upnwtf)


This behavior is known and it is the reason why we aren't adding a clip are for vectors.

**Comment by pixelzoom** [comment]
Thanks for the design doc pointer @brandonLi8. I suspected that this was already discussed.  

Closing.

**Comment by samreid** [comment]
Re-discovered in https://github.com/phetsims/vector-addition/issues/376, glad to see a paper trail here, thanks everyone.
