### ISSUE TITLE
polish icons on "snap mode" radio button

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/vector-addition#107]
After literally hours of playing with the sim, I did not understand these radio button icons:

<img width="150" alt="screenshot_1335" src="https://user-images.githubusercontent.com/3046552/63300609-d4588f00-c295-11e9-85db-27087e03b921.png">

It wasn't until I read this bit of code that I finally understood:

```js
  const CoordinateSnapModes = new Enumeration( [

    'CARTESIAN',  // Vector tail and tip are snapped to an exact grid coordinate (components are always integers).

    'POLAR'       // Vector tip is snapped so that the angle is a multiple of 5 and the magnitude is an integer.
                  // When translating the body, the vector tail is either snapped to an exact grid coordinate or
                  // the vector tail/tip is snapped to other polar vector's tails/tips.

  ] );
```
<br>
Now it may just be me.  But you might want to include a label with the word "snap" on it somewhere near these radio buttons.  Or at least watch for this in interviews.

**Comment by pixelzoom** [comment]
Also worth pointing out is that the polar icon communicates nothing about the angle snapping to an increment.

**Comment by pixelzoom** [comment]
Discussed with @ariel-phet.  The "1" labels on these buttons don't communicate "snap to integer", and there nothing that communicates "snap angle to 5".   What we really want to communicate is "snap to x & y" vs "snap to magnitude and angle", as well as "Cartesian" vs "Polar".  How about some thing like this? (but with correct font for x, y, r)

![ss8](https://user-images.githubusercontent.com/3046552/63901970-429eff00-c9c4-11e9-8d40-4eebb15bb68c.jpg)

**Comment by pixelzoom** [comment]
8/29/19 design meeting @arouinfar @ariel-phet @kathy-phet 

* @kathy-phet suggested just getting rid of labels altogether
* @ariel-phet suggested making the radio buttons larger
* @ariel-phet suggested making the x & y thinner in Cartesian icon, so they aren't confused with components

Try these suggestions.

**Comment by pixelzoom** [comment]
Changes made as requested in https://github.com/phetsims/vector-addition/issues/107#issuecomment-526361734.  See screenshot below. @arouinfar please review in master.

<img width="144" alt="screenshot_1430" src="https://user-images.githubusercontent.com/3046552/64136997-503cf600-cdc3-11e9-959b-51f4e4e4aeba.png">

**Comment by arouinfar** [comment]
Looks great @pixelzoom, thanks!
