### ISSUE TITLE
Base Vectors picker font size changes

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/vector-addition#108]
When the pickers for Base Vectors in the Equation screen show negative numbers, their font size is noticeably reduced.  See screenshot below.  @arouinfar is this desired, or is it a bug?

<img width="215" alt="screenshot_1336" src="https://user-images.githubusercontent.com/3046552/63303262-8c893600-c29c-11e9-9e2a-a4397e06cf5b.png">

**Comment by pixelzoom** [comment]
Here's the worst case example, showing the widest negative values related to |d|.   

<img width="212" alt="screenshot_1339" src="https://user-images.githubusercontent.com/3046552/63303688-c4dd4400-c29d-11e9-985d-e0659d80975b.png">

If you want the font size to remain constant, then pickers need to be wider. If you want all pickers to be the same width, then the entire accordion box needs to be quite a bit wider.  Please advise.

**Comment by pixelzoom** [comment]
Angle pickers should be as big as needed to make font size constant.

**Comment by arouinfar** [comment]
Looks good in master. 👍
