### ISSUE TITLE
base vectors shown on graph don't match initial values

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/vector-addition#109]
To reproduce:

1. Start the sim
2. Go to Equation screen
3. Select radio button of "Polar snap" scene
4. Check the "Show Base Vectors" checkbox

The screenshot below shows the initial state.   The base vectors shown on the graph don't match the values shown in the pickers.  It looks like the magnitudes might be correct, but the angles are definitely incorrect.

<img width="1089" alt="screenshot_1338" src="https://user-images.githubusercontent.com/3046552/63303441-16390380-c29d-11e9-986a-50099261f2dc.png">

**Comment by brandonLi8** [comment]
@pixelzoom this one was strange, but after some debugging, I found the source.



In `BaseVector.js` I have this piece of code:
```
        this.magnitudeProperty && this.magnitudeProperty.link( magnitude => {
          this.vectorComponents = Vector2.createPolar( magnitude, this.angleDegreesProperty.value );
        } );
```
However, as you can see, I use `this.angleDegreesProperty.value`, a degree measurement. But the  `Vector2.createPolar` is in radians. At one point, this code worked as I didn't use Vector2.createPolar. But when I switched, I forgot to convert to radians.


Switching that piece of code to this:
```
        this.magnitudeProperty && this.magnitudeProperty.link( magnitude => {
          this.vectorComponents = Vector2.createPolar( magnitude, Util.toRadians( this.angleDegreesProperty.value ) );
        } );
```
solves the problem:


![image](https://user-images.githubusercontent.com/42391580/63305141-f73d7000-c2a2-11e9-89f7-ef8fb3fe5ceb.png)

**Comment by brandonLi8** [comment]
Also, on the topic of that specific link, right above that piece of code is this:

```

        this.angleDegreesProperty && this.angleDegreesProperty.link( angleDegrees => {
          this.vectorComponents = Vector2.createPolar( this.magnitude, Util.toRadians( angleDegrees ) );
        } );

        this.magnitudeProperty && this.magnitudeProperty.link( magnitude => {
          this.vectorComponents = Vector2.createPolar( magnitude, Util.toRadians( this.angleDegreesProperty.value ) );
        } );
```


This should be converted to a multilink.

**Comment by brandonLi8** [comment]
Also, on the topic of those 2 links, I have `this.angleDegreesProperty && ...`. That should be removed, as in that if statement, the angleDegreesProperty and the magnitudeProperty always exist.

**Comment by pixelzoom** [comment]
Thanks for debugging @brandonLi8, I'll proceed with the fixes that you've recommended.

**Comment by pixelzoom** [comment]
Fixed in above commit.  @brandonLi8 feel free to have a look. 

Closing.
