### ISSUE TITLE
checkbox to show/hide vectors "c" and "f"?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/vector-addition#110]
In the _Equation_ screen, it seems like being able to make predictions about vectors "c" and "f" would be useful, similar to predicting the sum "s" in the earlier screens.   But unlike sum, there is no control to show/hide the "c" and "f" vectors.  Should there be checkboxes for "c" and "f", similar to the "Sum" checkbox?

**Comment by pixelzoom** [comment]
8/22/19 design meeting:

Add checkbox at top of upper-right panel for "c" or "f" (depending on scene selection), default is checked.   Icon and label similar to Sum checkbox on other screens.

**Comment by pixelzoom** [comment]
Checkboxes for 'c' and 'f' added to _Equations_ screen in above commit. @arouinfar please review in master.

**Comment by pixelzoom** [comment]
Note that #157 deals with deciding what the scope is for these (and other) sum checkboxes.  For now, the scope is global to the screen. That is, the state of the "c" and "f" checkboxes is linked.

**Comment by arouinfar** [comment]
Looks good in master @pixelzoom!
