### ISSUE TITLE
vector angle is not translatable

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/vector-addition#111]
Vector angles are currently not translatable.  @arouinfar should it be translatable? 

Here's how the string for angles is currently created in `VectorAngleNode`:

```js
this.labelText.setText( angleDegrees !== null ?
                        `${Util.toFixed( vector.angleDegrees, ANGLE_ROUNDING )}${DEGREES}` :
                        '' );
```

Where `const DEGREES = '\u00B0'`

This is not at all translatable.

To make it translatable, in vector-addition-strings_en.json:

```
"anglePattern": {
  "value": "{{angle}}\u00B0"
},
```

And in `VectorAngleNode`:

```js
const anglePatternString = require( 'string!VECTOR_ADDITION/anglePattern' );
...
let angleString = '';
if ( angleDegrees !== null ) {
  angleString = StringUtils.fillIn( anglePatternString, {
    angle: Util.toFixed( vector.angleDegrees, ANGLE_ROUNDING )
  } );
}
this.labelText.setText( angleString );
```

**Comment by arouinfar** [comment]
@pixelzoom I don't think the degrees symbol should be translatable -- it's a mathematical symbol. There is precedent for this in `trig-tour` which also doesn't allow localization of `\u00B0`, see [AngleReadoutRow.js](https://github.com/phetsims/trig-tour/blob/master/js/trig-tour/view/readout/AngleReadoutRow.js#L153). 

![image](https://user-images.githubusercontent.com/8419308/63666979-5dd4f900-c78f-11e9-85ab-04671112a509.png)

**Comment by pixelzoom** [comment]
OK, closing.
