### ISSUE TITLE
BaseVector.reset reaches into superclass

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/vector-addition#114]
Noticed while working on https://github.com/phetsims/vector-addition/issues/109. 

`BaseVector` implements `reset` like this:

```js
    reset() {
      this.tailPositionProperty.reset();
      this.angleDegreesProperty && this.angleDegreesProperty.reset();
      this.magnitudeProperty && this.magnitudeProperty.reset();
      this.yComponentProperty && this.yComponentProperty.reset();
      this.xComponentProperty && this.xComponentProperty.reset();
    }
```

But `BaseVector` does not own `this.tailPositionProperty`.  That Property is defined in `RootVector`, it's grandparent class.   

So `RootVector` should implement `reset`:

```js
    /**
     * @public
     */
    reset() {
      this.tailPositionProperty.reset();
    }
```

And `BaseVector` should override like this:

```js
    /**
     * @public
     * @override
     */ 
    reset() {
      super.reset();
      this.angleDegreesProperty && this.angleDegreesProperty.reset();
      this.magnitudeProperty && this.magnitudeProperty.reset();
      this.yComponentProperty && this.yComponentProperty.reset();
      this.xComponentProperty && this.xComponentProperty.reset();
    }
```

**Comment by pixelzoom** [comment]
Oh dear -- `this.tailPositionProperty` is a DerivedProperty.  A DerivedProperty should never be reset directly, it's dependencies should be reset.  But apparently that's not enforced.  I'll create an axon issue.

**Comment by pixelzoom** [comment]
My bad, `this.tailPositionProperty` is a Vector2Property.  It's `this.tipPositionProperty` that is a DerivedProperty.  

But now I'm wondering why `RootVector` wouldn't reset both `this.tailPositionProperty` and `this.vectorComponentsProperty`.   I.e.:

```js
    /*
     * @public
     */
    reset() {
      this.tailPositionProperty.reset();
      this.vectorComponentsProperty.reset();
    }
```


@brandonLi8 any insight?

**Comment by brandonLi8** [comment]
@pixelzoom `RootVector` doesn't have a reset method (right now) because on the first 3 screens, the only vectors that are "reset" are Vector Sums.

Hence, `RootVector` doesn't have reset while `VectorSum` is the first class that implements it.

However, I don't see a reason why a reset method would harm in `RootVector`.

**Comment by pixelzoom** [comment]
Thanks @brandonLi8.  I'll go ahead and add `this.vectorComponentsProperty.reset()` to RootVector's `reset` method.

**Comment by brandonLi8** [comment]
@pixelzoom make sure to delete the reset method in `VectorSum`.

**Comment by pixelzoom** [comment]
Thanks @brandonLi8.  `EquationVector` also needs modification of its `reset` method.

**Comment by pixelzoom** [comment]
Tested manually and with `?fuzz`.  I don't see any problems related to `reset`, so closing.
