### ISSUE TITLE
pixel polishing for leader lines

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/vector-addition#120]
@ariel-phet mentioned that he thought the leader lines could use some pixel polishing.   These are the lines that extend vertically and horizontally from the vector to the projections of its components on the axes.   These lines are solid red for the selected vector, dashed black for the unselected vectors.  See screenshot below.

<img width="976" alt="screenshot_1348" src="https://user-images.githubusercontent.com/3046552/63471895-bd4ca500-c42d-11e9-9493-19ea2d18841d.png">

**Comment by pixelzoom** [comment]
I've thought about this some, and I don't have a suggestion that I feel is clearly better.  But here are my conclusions:

* The bit I dislike the most is the use of red `#D64F00` for the selected vector. It's a "significant" color, and it's not color-coded to anything. You might consider simply using solid black.  See screenshot below.
* I think the black dashed lines for unselected vectors works nicely and looks good.  

Assigning to @ariel-phet and @arouinfar to decide how to proceed.

<img width="975" alt="screenshot_1349" src="https://user-images.githubusercontent.com/3046552/63472248-be320680-c42e-11e9-87c0-513c2e0099ea.png">

**Comment by pixelzoom** [comment]
Above I said:
> The bit I dislike the most is the use of red `#D64F00` for the selected vector. It's a "significant" color, and it's not color-coded to anything. 

In fact, there is something that's red -- there is a red set of vectors in the _Lab_  screen.  And in the screenshot below, there is no relationship at all between the red projection lines and those red vectors. So I think that red is really inappropriate to use for the projection lines.

<img width="976" alt="screenshot_1352" src="https://user-images.githubusercontent.com/3046552/63472930-e91d5a00-c430-11e9-97bf-3a07cf27f11d.png">

**Comment by brandonLi8** [comment]
@pixelzoom said:
> So I think that red is really inappropriate to use for the projection lines.

I agree. We never discussed this at any meetings I was present in, so I just threw that together for the time being.

My recommendations would be:
- Make the lines a good amount thicker
- I like @pixelzoom's suggestion of making the liens black
- I'm unsure if we should completely remove the line dash. Maybe a different line dash?

**Comment by ariel-phet** [comment]
@pixelzoom yes, this was not polished yet, and your suggestions are good, please move ahead with solid black leader lines for the selected vector and black dashed lines for unselected, as shown in your screenshot.

**Comment by pixelzoom** [comment]
Done, as shown in https://github.com/phetsims/vector-addition/issues/120#issuecomment-523670446.  @ariel-phet or @arouinfar please review in master. Close if it looks OK.

**Comment by pixelzoom** [comment]
8/22/19 design meeting: good
