### ISSUE TITLE
check performance of moving the graph's origin

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/vector-addition#125]
When the graph's origin (green sphere) is moved, the current implementation recreates the grid, axes, and  tick marks.   This is relatively expensive, and could be a performance issue. 

Has performance of moving the origin been vetted?  If not, recommended to check performance and responsiveness now on any performance-challenged platforms, using [1.0.0-dev.13](https://phet-dev.colorado.edu/html/vector-addition/1.0.0-dev.13/phet/vector-addition_en_phet.html).  Use a configuration that has both x & y axes.

**Comment by pixelzoom** [comment]
One obvious optimization is how the tick marks are created.  It currently iterates over every 1 unit, checking to see if that unit is a major tick.  E.g. for the x axis:

```js
    getUpdatedTicksShape( graphModelBounds, modelViewTransform ) {

      // Create ticks along the axis
      const xAxisTicksShape = new Shape();

      // x-axis ticks, add them on every major tick
      for ( let xValue = graphModelBounds.minX; xValue <= graphModelBounds.maxX; xValue++ ) {
        const isMajor = xValue % ( MAJOR_TICK_SPACING ) === 0;

        // The origin has a longer tick
        if ( xValue === 0 ) {
          xAxisTicksShape.moveTo( xValue, -TICK_LENGTH ).verticalLineTo( TICK_LENGTH );
        }
        else if ( isMajor ) {
          xAxisTicksShape.moveTo( xValue, -TICK_LENGTH / 2 ).verticalLineTo( TICK_LENGTH / 2 );
        }
      }
      return modelViewTransform.modelToViewShape( xAxisTicksShape );
    }
  }
```

It would be more efficient to determine the value of the first major tick, then iterate and add `MAJOR_TICK_SPACING`.

**Comment by pixelzoom** [comment]
There's also no reason to call `setTailAndTip` on the axes when the origin it moved.  That results in an unnecessary change to Shape.  It's should be sufficient to simply translate the axes to correspond to the new location of the origin.

**Comment by pixelzoom** [comment]
I tried to just translate the axes instead of calling `setTailAndTip`, and it got complicated.  So I bailed.  I will revisit if there is a performance problem.

**Comment by pixelzoom** [comment]
Raising priority. This is important to evaluate soon, so that we know whether the graph implementation needs to be reworked.

**Comment by KatieWoe** [comment]
- [ ] Win 10 chrome
- [ ] Win 10 firefox
- [ ] Win 10 edge
---
- [ ] Win 7 chrome
- [ ] Win 7 firefox
- [ ] Win 7 internet explorer
---
- [ ] Mac 10.14 chrome
- [ ] Mac 10.14 safari
---
- [ ] Mac 10.13 chrome
- [ ] Mac 10.13 safari
---
- [ ] Mac 10.12 chrome
- [ ] Mac 10.12 safari
---
- [ ] Mac 10.11 chrome
- [ ] Mac 10.11 safari
---
- [ ] Mac 10.10 safari
---
- [ ] Chrome OS
---
- [ ] iOS 12
- [ ] iOS 11

**Comment by KatieWoe** [comment]
Possible Issues (will update comment as found):
Win 10 Firefox, FPS drops below 50, sometimes to 30, when moving origin when components are projected on the x/y axis.  Doesn't feel particularly noticeable.

**Comment by KatieWoe** [comment]
Note that I'm just looking at performance for this.  Let me know if/how you want me to record any bugs I find while doing this.

**Comment by arouinfar** [comment]
@KatieWoe if you run into any obvious bugs while testing the performance, please report them.

**Comment by KatieWoe** [comment]
No iOS 11 device in the office to test on currently.  I'm fairly happy with the test results as is.  Overall, most combinations showed the same fps drops as described above, but everything felt good in use.  The point may have lagged behind a bit, but not much and I think it was acceptable.  The only example that seemed problematic in use to me was Win 10 Edge.  @arouinfar for check and confirmation.

**Comment by arouinfar** [comment]
Thanks @KatieWoe!

@KatieWoe demoed Win10/Edge for me, and I played a bit on iOS 11. 

Win10/Edge lags a bit when dragging the origin with projection-style components and all checkboxes on. Since this is a lower-use platform, Edge is on its deathbed, and there isn't any realistic use case for rapidly moving the origin over-and-over, I don't think it's worth investing any resources into.

Testing a similar situation in iOS 11 had much better performance and no noticeable lag.

@pixelzoom I think this is probably safe to close, but passing back to you just in case.

**Comment by pixelzoom** [comment]
I'm OK to close.
