### ISSUE TITLE
improve visual cues for sum vectors

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/vector-addition#126]
Somewhat related to #124 (concerns about direct manipulation of vectors)... 

Consider revisiting the representation of sum vectors.  Sum and non-sum vectors behave very differently for direct manipulation.  But they don't look sufficiently different.   There currently are 2 visual cues:

*  There's a black outline on sum vectors. But that same outline is used in Component radio button icons, which apply to sum and non-sum vectors. 
* Sum vectors are a slightly different (darker) color. The color might be sufficient for the sum of the red vectors, but it's too subtle for the sum of the blue vectors (see screenshot below).

<img width="579" alt="screenshot_1354" src="https://user-images.githubusercontent.com/3046552/63478927-1970f280-c449-11e9-9606-f13ce14066ab.png">

**Comment by pixelzoom** [comment]
8/22/19 design meeting:  I will try some darker shades with same hue.

**Comment by pixelzoom** [comment]
I tweaked the colors and stroke width for the vectors, see example in the 2 screenshots below.   The component vectors have been using transparency (`opacity: 0.75`), and that's not going to work well when we switch to dashed lines.  But I'll be able to switch to an opaque color that looks the same.

@arouinfar please review, let me know if you think this is an improvement.

<img width="1033" alt="screenshot_1359" src="https://user-images.githubusercontent.com/3046552/63642860-1e20eb00-c683-11e9-9be6-a2c2289d8f18.png">
<img width="1034" alt="screenshot_1360" src="https://user-images.githubusercontent.com/3046552/63642861-22e59f00-c683-11e9-96b1-422c5dee3847.png">

**Comment by arouinfar** [comment]
@pixelzoom the screenshots in https://github.com/phetsims/vector-addition/issues/126#issuecomment-524582021 look really nice to me. Thanks!

I don't believe these changes are in master, so back to @pixelzoom.

**Comment by pixelzoom** [comment]
Yes, these changes have been in master for quite awhile.  Closing.
