### ISSUE TITLE
improve usability by reducing graph range

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/vector-addition#127]
In #124, I said:

> * It's very difficult to use on touch devices.  ...
> * Everything is too small for this type of direct manipulation. Consider reducing the graph range and making everything significantly larger.

The current graph size is 60x40 units.  Unless there's some pedagogical reason for needing that much range, consider the following changes:

* Reduce the range of the graph.
* Increase the head size and tail width of vectors, on the graph and in toolboxes.
* Increase touchAreas, and possibly mouseAreas, for vector heads and tails.
* Increase the size of the origin manipulator. Compare to manipulators in Graphing Lines.
* Increase the font size used to label vectors on the graph.

**Comment by pixelzoom** [comment]
8/22/19 design meeting:  Try 50 units horizontal.

**Comment by pixelzoom** [comment]
I was playing around with reducing the range of the graph, as we decide in 8/22/19 design meeting, reducing the x range to 50 units.  

I made these changes:

```js
// VectorAdditionConstants
- DEFAULT_GRAPH_BOUNDS: new Bounds2( -5, -5, 55, 35 )
+ DEFAULT_GRAPH_BOUNDS: new Bounds2( -5, -5, 45, 30 ),

// Graph
- const MODEL_TO_VIEW_SCALE = 12.45;
+ const MODEL_TO_VIEW_SCALE = 14.5;
```

And the origin is then displayed in the incorrect y location, in the middle of two grid lines.  My guess is that there's code that assumes that the height (and width?) of `DEFAULT_GRAPH_BOUNDS` are even numbers, but I can't find that code. 

@brandonLi8 any pointers to where I might look?

<img width="1035" alt="screenshot_1365" src="https://user-images.githubusercontent.com/3046552/63656575-dec1cf80-c752-11e9-944a-88255574525c.png">

**Comment by pixelzoom** [comment]
Ah, it's probably this code in Explore1DGraph:

```js
  // graph bounds for 'Explore 1D' - origin is at the center
  const EXPLORE_1D_GRAPH_BOUNDS = new Bounds2( -DEFAULT_GRAPH_BOUNDS.width / 2,
    -DEFAULT_GRAPH_BOUNDS.height / 2,
    DEFAULT_GRAPH_BOUNDS.width / 2,
    DEFAULT_GRAPH_BOUNDS.height / 2 );
```

**Comment by pixelzoom** [comment]
I also noticed that the major horizontal grid lines are missing in the above screenshot.  Any idea why a non-even height would cause that to happen?

**Comment by brandonLi8** [comment]
> I also noticed that the major horizontal grid lines are missing in the above screenshot.

I see the horizontal major lines every 5. Not sure what you are referring to.

**Comment by pixelzoom** [comment]
In the screenshot in https://github.com/phetsims/vector-addition/issues/127#issuecomment-524668623, there are _vertical_ major lines every 5, but there are no _horizontal_ major lines.

**Comment by brandonLi8** [comment]
@pixelzoom.
```
        //----------------------------------------------------------------------------------------
        // Create the Horizontal Grid Lines.
        for ( let yValue = graphMinY; yValue <= graphMaxY; yValue++ ) {

          const isMajor = ( yValue % MAJOR_TICK_SPACING === 0 );
          if ( isMajor ) {
            majorGridLinesShape.moveTo( graphMinX, yValue ).horizontalLineTo( graphMaxX );
          }
          else {
            minorGridLinesShape.moveTo( graphMinX, yValue ).horizontalLineTo( graphMaxX );
          }
        }
```
the above code is in graphNode and loops from a integer to an integer.

**Comment by pixelzoom** [comment]
Yep, that's it.  I was just about to paste the same code fragment.

**Comment by pixelzoom** [comment]
I'm guessing that in Explore1D, there's a desire to start with the origin in the center of the graph. If that's the case, then width and height must be even numbers.  So I added an assertion to verify that in fd53569e036909e445b908f62f75c9b30fe7a452.

**Comment by arouinfar** [comment]
Looks like this is still in progress, so I'll unassign myself for now.

**Comment by pixelzoom** [comment]
8/29/19 design meeting @ariel-phet @arouinfar @kathy-phet:

* Proceed with changes in https://github.com/phetsims/vector-addition/issues/127#issuecomment-525429932.  
* OK for graph to move down on Equations screen.

**Comment by pixelzoom** [comment]
@arouinfar ready for review in [1.0.0-dev.15]().  Representative screenshots are shown below. 

Notes:
* This includes work on #134 (layout of stuff to right of graph).  If you have comments about that, please note in #134.
* Issue #128 (layout of stuff above graph in Equations screen) is still a work in progress.  

<img width="1056" alt="screenshot_1464" src="https://user-images.githubusercontent.com/3046552/64888095-55057380-d627-11e9-9c57-cd02ff28b655.png">
<img width="1056" alt="screenshot_1465" src="https://user-images.githubusercontent.com/3046552/64888100-5afb5480-d627-11e9-8672-b5bc558caa31.png">
<img width="1052" alt="screenshot_1466" src="https://user-images.githubusercontent.com/3046552/64888104-5d5dae80-d627-11e9-9ba8-f37f1aabc351.png">
<img width="1055" alt="screenshot_1467" src="https://user-images.githubusercontent.com/3046552/64888106-5fc00880-d627-11e9-9e5c-1fbcf581ce0d.png">

**Comment by arouinfar** [comment]
The updated grid size is feeling really good @pixelzoom.
