### ISSUE TITLE
inconsistent labeling of vectors for scenes

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/vector-addition#131]
In the _Explore 1D_ screen, switch between horizontal and vertical axis changes the vector label sets from ['a', 'b', 'c' ] to [ 'd', 'e', 'f' ] respectively.  Ditto for switching between Cartesian and Polar scenes in the _Equation_ screen.

But in the _Explore 2D_ scene, switching between  Cartesian and Polar scenes results in no change to the vector label set.  They are both ['a', 'b', 'c' ].   Should this be changed, so that the Polar scene uses labels [ 'd', 'e', 'f' ]  ?

This is not a new issue, it was present in 1.0.0-dev.11.

**Comment by pixelzoom** [comment]
I'm fairly certain that the symbols should change when switching between Cartesian and Polar, so I went ahead and did this.  Cartesian is [a,b,c], Polar is [d,e,f]. See screenshots below.  

@arouinfar please review, close if OK, ask me to revert if this is not desired. 

<img width="1033" alt="screenshot_1366" src="https://user-images.githubusercontent.com/3046552/63656910-f8b1e100-c757-11e9-8818-ecad421b8baf.png">
<img width="1032" alt="screenshot_1367" src="https://user-images.githubusercontent.com/3046552/63656915-01a2b280-c758-11e9-9630-b0958b2793aa.png">

**Comment by arouinfar** [comment]
Good catch @pixelzoom! 

> I'm fairly certain that the symbols should change when switching between Cartesian and Polar, so I went ahead and did this. Cartesian is [a,b,c], Polar is [d,e,f]. See screenshots below.

This is indeed the desired behavior, so closing.
