### ISSUE TITLE
put scene radio buttons and vector toolbox in same location on all screens?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/vector-addition#132]
Explore2D, Lab, and Equation screens all have the scene radio button at lower-right, above the Reset All button.  For example:

<img width="1035" alt="screenshot_1361" src="https://user-images.githubusercontent.com/3046552/63642958-dbf8a900-c684-11e9-875a-bf493616aa9b.png">

Equation1D screen has the scene radio button in a totally different place, below the panel at upper-right:

<img width="1033" alt="screenshot_1363" src="https://user-images.githubusercontent.com/3046552/63642990-5c1f0e80-c685-11e9-872c-6eee28acddbd.png">

Should the Equation1D scene radio buttons be moved, to be consistent with the other screens?

**Comment by pixelzoom** [comment]
It might also be nice if the vector toolbox was always in the same place (just above the scene buttons) in the first 3 screens.  It currently jumps around.

**Comment by pixelzoom** [comment]
@arouinfar I went ahead and did this.  The scene radio buttons are always at the lower-right, above the Reset All button.  And the vectors toolbox is always above the scene radio buttons.   If this looks like a good layout to you, please assign back to me for a bit more polishing and code cleanup.

**Comment by brandonLi8** [comment]
@pixelzoom if this is something that stays, should the radio buttons be the same size?

Currently it looks like:
![image](https://user-images.githubusercontent.com/42391580/63645548-09157d80-c6be-11e9-9c36-d81366508b44.png)

Which is slightly smaller than the coordinateSnapModeRadioButtons:
![image](https://user-images.githubusercontent.com/42391580/63645552-1a5e8a00-c6be-11e9-86c2-739f248ccbce.png)

I already have a function in `VectorAdditionIconFactory` that creates the same size icon for the coordinateSnapMode icons and the componentStyle icons.

So this can be easily changed:

instead of this:
```
      if ( graphOrientation === GraphOrientations.HORIZONTAL ) {
        return new ArrowNode( 0, 0, options.arrowLength, 0, options.arrowOptions );
      }
      else if ( graphOrientation === GraphOrientations.VERTICAL ) {
        return new ArrowNode( 0, 0, 0, options.arrowLength, options.arrowOptions );
      }
```
it would be this: (createRadioButtonIcon defaults to the 'normal' size)
```
      if ( graphOrientation === GraphOrientations.HORIZONTAL ) {
        return createRadioButtonIcon( new ArrowNode( 0, 0, options.arrowLength, 0, options.arrowOptions ) );
      }
      else if ( graphOrientation === GraphOrientations.VERTICAL ) {
        return createRadioButtonIcon( new ArrowNode( 0, 0, 0, options.arrowLength, options.arrowOptions ) );
      }
```

**Comment by pixelzoom** [comment]
> ... should the radio buttons be the same size?

Yep. When I mentioned "a bit more polishing", making scene radio buttons have uniform dimensions was one of the things that I had in mind.    Thanks for the pointers to relevant code in `VectorAdditionIconFactory`.

**Comment by brandonLi8** [comment]
Also another small thing which goes under the  "a bit more polishing" criterion;

The x-location for the tool box in `Explore1D` and `Explore2D` is slightly different. This is most likely because the Control Panel is a different width, and will be different widths on translated versions.

**Comment by pixelzoom** [comment]
The x location for the toolbox is probably different because it's relative to the scene radio buttons, which are a slightly different size in the Explore1D scene.

**Comment by brandonLi8** [comment]
@pixelzoom was it decided to make all `VectorCreatorPanels` the same size? In the design doc pictures, it is slightly smaller for the Lab screen.

**Comment by pixelzoom** [comment]
It was decided that I should take a stab at polishing the layout of all screens.  If @arouinfar doesn't like the changes, they can be easily reverted.  In any case, you can expect to see quite a few more layout changes.

**Comment by arouinfar** [comment]
This all looks good to me @pixelzoom. The one caveat is that the locations may still shift a bit as we pixel polish, but we'll still want to maintain consistency across the screens.
