### ISSUE TITLE
Different location for Vector Values Toggle Box on Explore 1D

### ISSUE THREAD

**Issue by brandonLi8** [phetsims/vector-addition#133]
Noticed while playing with the sim; On `Explore1D` the x location of the `VectorValuesToggleBox` is slightly different for the horizontal and the vertical scene.

It is hard to tell from screen shots, but it is easy to tell when switching between the 2 scenes.

Is this intentional? In my opinion, they should be in the same spot.

**Comment by pixelzoom** [comment]
Got it thanks.  Yes, they should be in the same location.

**Comment by brandonLi8** [comment]
Oh also, in `SceneNode` there is this:
```
const vectorValuesToggleBox = new VectorValuesToggleBox( graph, options.vectorValuesToggleBoxOptions );
      vectorValuesToggleBox.centerX = graphNode.centerX;
```
The `VectorValuesToggleBox` is aligned in the graphNode.centerX.

Should it instead be aligned to the actual visual center (graphModelBounds.centerX after transformed to view)?

This is what it looks like now:
![image](https://user-images.githubusercontent.com/42391580/63645806-26991600-c6c3-11e9-9571-c227f313fc71.png)

As you can see, the panel has more margin to the left than to the right (relative to the visual graph)

**Comment by pixelzoom** [comment]
Yep, it should be aligned to graphModelBounds.centerX in view coordinates.

**Comment by pixelzoom** [comment]
The difference between horizontal and vertical was introduced when I change GraphNode to only create the axes that it needs.   The incorrect centering was a problem in 1.0.0-dev.11 (baseline). 

Fixed in the above commit.  Closing.

**Comment by brandonLi8** [comment]
@pixelzoom it was decided when @arouinfar and I had a design meeting to make the `VectorValuesToggleBox` larger only for the `Equation` screen.

**Comment by pixelzoom** [comment]
And at last week's (8/22) design meeting, they asked me to polish everything above the graph in the Equations screen, see https://github.com/phetsims/vector-addition/issues/128.    So I'll tag that commit with #128 and re-close this issue.
