### ISSUE TITLE
layout of stuff to right of graph

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/vector-addition#134]
When reviewing the sim with @ariel-phet, he also mentioned that the layout of stuff to the right of the graph could use some polishing.   Examples from [1.0.0-dev.11](https://phet-dev.colorado.edu/html/vector-addition/1.0.0-dev.11/phet/vector-addition_en_phet.html) are shown below.  He wanted me to try some other alignments, possibly horizontally centering the panels and radio button group. 

<img width="1028" alt="screenshot_1369" src="https://user-images.githubusercontent.com/3046552/63694776-6b60a200-c7d4-11e9-8dfe-e7ab42d40f91.png">

<img width="1035" alt="screenshot_1370" src="https://user-images.githubusercontent.com/3046552/63694958-ca261b80-c7d4-11e9-910e-ff4d081faafa.png">

**Comment by pixelzoom** [comment]
Due to changes for #110, the Base Vectors accordion box is currently overlapping the snap mode radio buttons. This is a known problem and will be addressed.

**Comment by pixelzoom** [comment]
Discussed layout with @arouinfar via Zoom.  After doing #127, the eraser button will be moved below the lower-right corner of the graph.   Layout for all screens will then be similar to the Equation screenshot below.  Vector toolboxes will be left aligned with the graph control panel.

<img width="916" alt="screenshot_1460" src="https://user-images.githubusercontent.com/3046552/64879930-4f526280-d614-11e9-813a-4a3838eedadf.png">

**Comment by pixelzoom** [comment]
@arouinfar ready for review in [1.0.0-dev.15](https://phet-dev.colorado.edu/html/vector-addition/1.0.0-dev.15/phet/vector-addition_en_phet.html).  Representative screenshots are shown below. 

Notes:
* This includes work on #127 (improve usability by reducing graph range).  If you have comments about that, please note in #134.
* Issue #128 (layout of stuff above graph in Equations screen) is still a work in progress.  

<img width="1056" alt="screenshot_1464" src="https://user-images.githubusercontent.com/3046552/64888095-55057380-d627-11e9-9c57-cd02ff28b655.png">
<img width="1056" alt="screenshot_1465" src="https://user-images.githubusercontent.com/3046552/64888100-5afb5480-d627-11e9-8672-b5bc558caa31.png">
<img width="1052" alt="screenshot_1466" src="https://user-images.githubusercontent.com/3046552/64888104-5d5dae80-d627-11e9-9ba8-f37f1aabc351.png">
<img width="1055" alt="screenshot_1467" src="https://user-images.githubusercontent.com/3046552/64888106-5fc00880-d627-11e9-9e5c-1fbcf581ce0d.png">

**Comment by arouinfar** [comment]
@pixelzoom the layout is looking really nice! Thanks for taking the lead on cleaning up the layout.
