### ISSUE TITLE
add cueing arrows to vector head

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/vector-addition#136]
To address https://github.com/phetsims/vector-addition/issues/124, and from 8/22/19 design meeting with @arouinfar @ariel-phet @kathy-phet:

Put cueing arrows around the head of the selected vector. As soon as you've rotated or scaled any vector, no more cueing arrows. Per screen. For Explore 1D, there's only a scale cue. No cues in Equation screen, since there is no direct manipulation of rotation and scale.

Scale arrow is double headed. Rotation is two curved arrows.

**Comment by arouinfar** [comment]
@pixelzoom let's defer this issue until after interviews.

Slack conversation with @ariel-phet 
>Amy Rouinfar 1:54 PM
I was talking to CM about Vector Addition, and we were looking over the remaining issues. He hasn’t implemented the cueing arrows yet, but I’m not so sure that they are 100% necessary.
I’ve recruited a bunch of students from intro chem who mostly haven’t taken any physics (or if they have, most have only had non-AP high school physics). We could interview and see
>
>Ariel Paul 1:55 PM
I generally saw those as a "wouldn't do any harm" feature. But I am fine without them if used by students without issue
>
>Amy Rouinfar 1:55 PM
No, they certainly won’t harm anything
But it’s a question of timelines
>
>Ariel Paul 1:55 PM
Your call
>
>Amy Rouinfar 1:55 PM
VA needs to get wrapped up soon, I know
I’d like to try interviews without
>
>Ariel Paul 1:56 PM
I am totally on board with that approach
>
>Amy Rouinfar 1:56 PM
Sounds good, thanks

**Comment by arouinfar** [comment]
I haven't seen any issues with vector scaling, rotation, or translation in interviews. I'm going to go ahead and close this issue.
