### ISSUE TITLE
inconsistent use of weighted font for NumberPicker labels

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/vector-addition#137]
In the _Equation_ screen, the NumberPickers labels (e.g **a<sub>x</sub> =**) use a weighted (bold) font.  This is inconsistent with all other occurrences of these symbols, and with the how the base vectors are labeled on the graph.   Screenshot:

<img width="920" alt="screenshot_1378" src="https://user-images.githubusercontent.com/3046552/63741140-fbdcc800-c850-11e9-8ce7-175690780ab2.png">

**Comment by arouinfar** [comment]
Good catch @pixelzoom! The bolding was not intentional. Looks good in master.
