### ISSUE TITLE
Reset All does not reset expanded/collapsed state of accordion boxes

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/vector-addition#138]
This was a problem in 1.0.0-dev.11, so not something that was introduced.

In all screens, the state of the Vector Values accordion box is not reset when the Reset All button is pressed.  

The Equation screen has the same problem with the Equation accordion box and the Base Vectors accordion box.

For every "scene", there are separate expand/collapse states for every accordion box.

@arouinfar please specify:
* Whether each scene has its own expanded/collapsed state for the accordion boxes, or whether they are linked.
* What is supposed to happen when the Reset All button is pressed.

**Comment by arouinfar** [comment]
> Whether each scene has its own expanded/collapsed state for the accordion boxes, or whether they are linked.

I see no reason to have separate expanded/collapsed states between the scenes. If the accordion box is expanded in one scene, then it can stay expanded in the other. 

>What is supposed to happen when the Reset All button is pressed.

The screen should return to its default state. 
* Vector Values: Open (all screens)
* Equation: Open
* Base Vectors: Closed

**Comment by pixelzoom** [comment]
@arouinfar done for all accordion boxes, please verify in master.

**Comment by arouinfar** [comment]
👍
