### ISSUE TITLE
disable eraser button when the graph is empty

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/vector-addition#139]
Should the erase button be disabled when the graph is empty?

<img width="912" alt="screenshot_1384" src="https://user-images.githubusercontent.com/3046552/63742862-6bee4c80-c857-11e9-8c3e-490c5c849025.png">

**Comment by pixelzoom** [comment]
On hold until we resolve #150 (sum vector behaves strangely with eraser button).

**Comment by pixelzoom** [comment]
Addressed in above commit. @arouinfar please verify in master.

**Comment by arouinfar** [comment]
Looks good in master, thanks @pixelzoom.
