### ISSUE TITLE
align baselines of text elements

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/vector-addition#140]
In the Equation screen, there's an alignment problem with coefficients in the Vector Values accordion box.  See below.   The coefficients for the x and y components are sitting noticeably below the baseline.   It's also a tiny bit off for the magnitude.

<img width="507" alt="screenshot_1386" src="https://user-images.githubusercontent.com/3046552/63743143-88d74f80-c858-11e9-8abf-122f23f22fb7.png">

**Comment by jonathanolson** [comment]
The Canvas bounds are actually computed well and seem accurate. Due to the italics and size of the glyph, it's a bit wider than the "normal" bounds method would detect.

Since for SVG we're providing the text length manually (to be able to match the Canvas text display), it happens that at least Chrome is wildly distorting the text when `lengthAdjust:spacingAndGlyphs` is set and `textLength` is a bit longer than it expects.

I'm going to do a bit more investigation, however it's likely that I'll want to suppress the length adjustment for SVG Text when we're using accurate Canvas bounds, as the display wouldn't match the Canvas appearance anyways.

**Comment by jonathanolson** [comment]
Implemented my above thoughts, which should fix this issue. @pixelzoom can you verify?

**Comment by pixelzoom** [comment]
Thanks @jonathanolson.  Looking good in branch 'boundsMethodAccurate' #147.  Do you think it's safe to rely on `boundsMethod: 'accurate'` and proceed with replacing `FormulaNode` usages with `ArrowOverSymbolNode`?

**Comment by jonathanolson** [comment]
I think it would be best to use the `boundsMethod: 'accurate'` setup instead of FormulaNode, but we may have issues that arise like https://github.com/phetsims/scenery/issues/22, and the detection is somewhat slow (if that's a performance issue). I think the tradeoffs seem worth it.

**Comment by pixelzoom** [comment]
In the above commit, I replaced FormulaNode (and therefore KaTex dependency) with ArrowOverSymbolNode.  Remaining layout issues to address:

- [ ] VectorValuesToggleBox, e.g.:

<img width="508" alt="screenshot_1440" src="https://user-images.githubusercontent.com/3046552/64452425-5decc700-d0b4-11e9-9cd3-7f9dd6dec060.png">

- [ ] EquationToggleBox, e.g.:

<img width="262" alt="screenshot_1442" src="https://user-images.githubusercontent.com/3046552/64452497-7c52c280-d0b4-11e9-824d-9f3ae82469b5.png">


- [ ] VectorLabelNode, e.g.:

<img width="235" alt="screenshot_1441" src="https://user-images.githubusercontent.com/3046552/64452461-6cd37980-d0b4-11e9-8522-835707016388.png">

**Comment by pixelzoom** [comment]
The discovery that `HBox` has option `align: 'origin'` went a long way towards improving the alignment.   But I still haven't figure out how to keep baselines aligned when text is separated by NumberPickers and NumberDisplays.

**Comment by pixelzoom** [comment]
Yesterday, @arouinfar and I discussed the remaining cases where baselines do not align.  Here are examples and conclusions.

(1) In the "Vector Values" accordion box, the baselines of the 'b' symbols are not aligned, ditto for the theta symbol.  @arouinfar said that this good enough.

<img width="491" alt="screenshot_1476" src="https://user-images.githubusercontent.com/3046552/64893965-bd5b5180-d635-11e9-9a82-d72d1ce79b45.png">

(2)  In the Equation accordion box, the baselines of 'a', 'b', and 'c' are not aligned. @arouinfar said this is reasonable, since the symbols are vertically centered on their respective pickers.

<img width="254" alt="screenshot_1475" src="https://user-images.githubusercontent.com/3046552/64894038-ee3b8680-d635-11e9-894f-c62d1d20f6d1.png">

(3) In the "Base Vectors" accordion box, the baselines of 'd' and 'e' are not aligned with the theta symbol.  @arouinfar said that this is good enough.

<img width="184" alt="screenshot_1477" src="https://user-images.githubusercontent.com/3046552/64894180-44102e80-d636-11e9-8b86-98bb570b18e4.png">

Assigning to @arouinfar to confirm that I've captured the above decisions correctly, and that alignment is generally looking good in master.

**Comment by arouinfar** [comment]
Thanks for checking in @pixelzoom. The alignment of the screenshots in https://github.com/phetsims/vector-addition/issues/140#issuecomment-531387933 (and master) all look reasonable to me. The alignment of the text with respect to the spinners/readouts looks well-positioned. If hold up a piece of paper to my screen, I can see that the baselines aren't perfectly aligned. 

While I appreciate @pixelzoom's eye for detail, I don't think it's worth spending any more time/resources in trying to manually align the baselines any further.
