### ISSUE TITLE
change behavior of Equation radio buttons

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/vector-addition#148]
This issue concerns these radio buttons on the Equation screen:

<img width="401" alt="screenshot_1406" src="https://user-images.githubusercontent.com/3046552/63901389-98be7300-c9c1-11e9-80bb-4f9be0a8b1e1.png">

Currently, each equation has its own associated scene, with a different set of vectors, coefficients, and (soon see #https://github.com/phetsims/vector-addition/issues/113#issuecomment-524053483) graph origin.    The goal was to be able to support cases like "discover that 1a + 2b = c is the same as 1a - -2b = c".  

The downsides to this are:
* It's difficult/awkward to set things up to meet the learning goals
* The learning goals only work for the first 2 equations. "a + b + c = 0" is unclear. 
* Drag constraints on the vectors get in the way when trying to set things up.
* It's a confusing UX to have (equation) scenes inside of (Cartestian/Polar) scenes.
* The implementation is complicated and buggy, see https://github.com/phetsims/vector-addition/issues/113.

I've discussed with @ariel-phet and @arouinfar separately so far.  And we're all leaning towards changing how these radio buttons work.  This also involves changing the learning goal to something like  "compare how 'c' changes with different equations using the same coefficients".  Instead of scenes:
* One graph, one origin, one set of coefficients.
* Selected radio button determines how "c" or "f" is computed.

@arouinfar suggested discussing this at design meeting.  If we don't make this change, we have some serious design and implementation work to do.

**Comment by pixelzoom** [comment]
8/29/19 design meeting @arouinfar @ariel-phet @amanda-phet @kathy-phet 

* Radio buttons change how 'c' and 'f' are computed
* Preserve tail location of 'c' and 'f'

**Comment by pixelzoom** [comment]
Behavior has been changed as described above.  @arouinfar @ariel-phet please review in master with high priority.   This issue deals with the behavior - if there are layout/polish issues, please comment in #128.

**Comment by arouinfar** [comment]
@pixelzoom the behavior of the equation radioButtonGroup is looking good in master!

**Comment by arouinfar** [comment]
Reviewed over Zoom with @ariel-phet, and he also gave this a 👍
