### ISSUE TITLE
change drag bounds for vectors

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/vector-addition#152]
8/29/19 design meeting @arouinfar @ariel-phet @kathy-phet:

- [x] Keep the tail within 1 unit of the graph bounds.  

- [x] Do not snap vector back into graph bounds on pointer down.

- [x] Remove from graph based on cursor position, not based on tip position.

- [x] Delete doc/images/vector-tail-drag-bounds.png

**Comment by pixelzoom** [comment]
Note to self: Will probably delete doc/images/vector-tail-drag-bounds.png

**Comment by pixelzoom** [comment]
First thing to do will be to change `Vector.getConstrainedTailBounds` to this:

```js
    /**
     * Gets the constrained bounds of the tail. The tail must be within 1 unit of the edge of the graph.
     * See https://github.com/phetsims/vector-addition/issues/152
     * @private
     */
    getConstrainedTailBounds() {
      return this.graph.graphModelBounds.eroded( 1 );
    }
```

**Comment by pixelzoom** [comment]
Implemented as requested in design meeting.  Note that if you click on a vector's head (to scale or rotate that is outside the graph bounds, then the head _does_ snap to the bounds of the graph.  This feels right to me, since if a vector's head is inside the graph bounds, it's constrained to the graph bounds. 

@arouinfar please review in master.  If you need to compare to the original behavior, see [1.0.0-dev.14](https://phet-dev.colorado.edu/html/vector-addition/1.0.0-dev.14/phet/vector-addition_en_phet.html).

**Comment by arouinfar** [comment]
@pixelzoom generally everything is behaving nicely. 

I've noticed that once a vector is popped off the grid, it won't necessarily retain its length when being placed back on the grid. The vector will get truncated, lobbing off the parts that were off-grid.
![longvector](https://user-images.githubusercontent.com/8419308/64732949-08902b80-d4a1-11e9-80e9-86437dcfbd9f.gif)

This interaction feels a little strange to me, especially when comparing to the behavior of translating a vector around the grid. If the tip goes off-grid (but the cursor stays on-grid), the vector will not be truncated.

I could see a situation where a vector is grabbed closer to its tip, is accidentally dragged off-grid, but then the user moves their cursor to keep the vector on-grid. If they're not careful with their cursor position when dropping the vector back onto the grid, the vector could get truncated.

**Comment by pixelzoom** [comment]
Good catch @arouinfar, I hadn't noticed it and agree that it feels wrong.

**Comment by pixelzoom** [comment]
Assigning to @ariel-phet in case he wants to weigh in on this.

**Comment by arouinfar** [comment]
@pixelzoom master is looking good to me

**Comment by ariel-phet** [comment]
I think these changes all look good. Closing.
