### ISSUE TITLE
visually differentiate base vectors

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/vector-addition#153]
8/29/19 design meeting @arouinfar @ariel-phet @kathy-phet 

Let's try making the base vectors look different.  Start with solid gray.

**Comment by pixelzoom** [comment]
Screenshot below of  the new look for base vectors. @arouinfar please verify in master.

<img width="762" alt="screenshot_1427" src="https://user-images.githubusercontent.com/3046552/64136543-39e16b00-cdc0-11e9-8e7a-3e3b4509fde2.png">

**Comment by arouinfar** [comment]
@pixelzoom looks good to me, but I'll hold off on closing until we can review in conjunction with #159.

**Comment by arouinfar** [comment]
`BASE_VECTOR_COLOR_PALLETE` can be found here:
https://github.com/phetsims/vector-addition/blob/master/js/common/VectorAdditionColors.js#L104

**Comment by pixelzoom** [comment]
You should also be aware that, in addition to colors in `VectorAdditionColors`, opacities are specified in `VectorAdditionConstants` under "Constants for Vectors".   I think it would a good idea to unify those by moving the opacities into the alpha channel of the color specifications.  E.g. `componentFill: 'rgba( 120, 200, 255, 0.75 )'` instead of `componentFill: 'rgb( 120, 200, 255 )',` and `opacity: 0.75`.

**Comment by pixelzoom** [comment]
#158 is also relevant to this, where we need to confirm whether components are shown for base vectors.

**Comment by pixelzoom** [comment]
We could also do something totally different for base vectors, like stroke (outline) them instead of filling them.  For example, see below.  And if that's not obvious enough, we could change the label on the "Show Base Vectors" checkbox to include an icon. 

<img width="917" alt="screenshot_1453" src="https://user-images.githubusercontent.com/3046552/64733764-93255a80-d4a2-11e9-9679-ce1b3967dea9.png">

**Comment by arouinfar** [comment]
@pixelzoom I really like the stroked base vectors! The color makes the connection clear, but the appearance is also distinctly different from the other vectors and their components. It also completely removes the similarity between the base vector and the components of **c** and **f**, which are also gray (seen in https://github.com/phetsims/vector-addition/issues/153#issuecomment-528512738).

I also like the iconic checkbox in the Base Vectors accordion menu. While descriptive, "Show Base Vectors" is definitely verbose and will likely end up cramped in some locales. The icon is a bit less clear than the string, but I think once the user turns it on, the meaning will be clear.

@ariel-phet @kathy-phet what do you think of the screenshots in https://github.com/phetsims/vector-addition/issues/153#issuecomment-530558305?

**Comment by pixelzoom** [comment]
@arouinfar would you like the checkbox centered or left justified?  Screenshots below.  It's currently centered in master, if you want to test drive. Please assign back to me, because your answer determines how I'll clean up the layout code.

<img width="183" alt="screenshot_1457" src="https://user-images.githubusercontent.com/3046552/64872322-380b7900-d604-11e9-942f-c733080515b8.png"> <img width="183" alt="screenshot_1459" src="https://user-images.githubusercontent.com/3046552/64872328-3b066980-d604-11e9-84d0-4f2aca8956fa.png">

**Comment by pixelzoom** [comment]
@arouinfar replied on Slack:

> I prefer left-aligned. It’s a bit easier to overlook the center-aligned checkbox.

**Comment by pixelzoom** [comment]
Checkbox is now left aligned in master. @arouinfar please review.

**Comment by arouinfar** [comment]
> I might make the vector a tad thinner (so less white)

@ariel-phet there have been several changes to master since https://github.com/phetsims/vector-addition/issues/153#issuecomment-530558305, and the base vectors now look like this:
![image](https://user-images.githubusercontent.com/8419308/64988210-32be6080-d888-11e9-891e-9f8e2f2aa32b.png)

With the updated vector appearances, the base vectors are already a bit thinner. Currently, the dimensions also appear to be identical to the regular vectors.
![image](https://user-images.githubusercontent.com/8419308/64987701-00603380-d887-11e9-8f9f-11861ecf8149.png)

Personally, I think the base vectors are looking pretty good in their current state, but if you would like to go thinner @ariel-phet, let me know.

**Comment by arouinfar** [comment]
> Checkbox is now left aligned in master. @arouinfar please review.

Looks good in master @pixelzoom, thanks!

**Comment by ariel-phet** [comment]
Looks good to me in master, closing
