### ISSUE TITLE
Use merge instead of extend

### ISSUE THREAD

**Issue by brandonLi8** [phetsims/vector-addition#154]
There are multiple files that use the new `merge` from `PhetCore`. But some of the files are still nesting extend calls, for example in `CurvedArrowNode`:

```
      options = _.extend( {

        arrowheadWidth: 8,  // {number} the arrowhead width (before rotation)
        arrowheadHeight: 6, // {number} the arrowhead height (before rotation)

        arcOptions: null, // {Object|null} defaults filled in bellow
        arrowOptions: null // {Object|null} defaults filled in bellow,

      }, options );

      options.arcOptions = _.extend( {
        stroke: VectorAdditionColors.BLACK,
        lineWidth: 1.75
      }, options.arcOptions );

      options.arrowOptions = _.extend( {
        fill: VectorAdditionColors.BLACK
      }, options.arrowOptions );
```

Here are the files that are doing this:
- [ ] `ComponentVectorNode.js`
- [ ] `CurvedArrowNode.js`

I believe these should use merge for consistency.

**Comment by pixelzoom** [comment]
Thanks @brandonLi8. I'll inspect all `_.extend` calls ands covert as needed.

**Comment by pixelzoom** [comment]
`_.extend` should be converted to `merge` for:

- [ ] ComponentVectorNode
- [ ] CurvedArrowNode
- [ ] SumComponentVectorNode

**Comment by pixelzoom** [comment]
Done in the above commit.  I also removed some unnecessary options passed to `CurvedArrowNode`, which were the same as the defaults.
