### ISSUE TITLE
fix position of label for zero-magnitude vectors

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/vector-addition#156]
A sum vector with zero magnitude should not have its label centered on its tail position, as in the screen shot below.  The label should be positioned as if a non-zero magnitude were present.  Note that this might only be relevant when the vector is at (0,0).
  
<img width="898" alt="screenshot_1409" src="https://user-images.githubusercontent.com/3046552/63908315-024b7b00-c9dc-11e9-92dc-87fe4161e5bc.png">

**Comment by pixelzoom** [comment]
This is currently being done in RootVectorNode:

```js
      if ( rootVector.magnitude === 0 ) { // don't do anything if the magnitude is 0
        this.labelNode.center = modelViewTransform.modelToViewDelta( Vector2.ZERO );
        return;
      }
```

**Comment by arouinfar** [comment]
@pixelzoom let's go with (a). 

I think it's nice, and pedagogically helpful, for the the tail of the sum to start out at the origin. 

The sum label occluding the origin dot is unlikely to be common, especially when first interacting with the sum. 
* The sum is off by default
* The whole point of the sim is for vectors to be in the play area, and it's unlikely that the sum would start off at zero.
* Moving the origin isn't really that important on Explore 1D. The dot is there for consistency and some added flexibility.
* The sum label is easily dragged away from the origin dot, or can simply be turned off if it's in the way.
