### ISSUE TITLE
should components be shown for base vectors?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/vector-addition#158]
In the Equations screen, there are crruently no component vectors shown for base vectors. See screenshot below. Is this what its desired, or should the setting of the "Components" radio buttons also apply to base vectors.

<img width="920" alt="screenshot_1428" src="https://user-images.githubusercontent.com/3046552/64136807-4f579480-cdc2-11e9-90ba-695c5652df02.png">

**Comment by arouinfar** [comment]
Early on we had decided not to show the components for the base vectors. We didn't want the base vectors to get confused for the vectors in the equation, and we also had some concerns about the visual clutter.

However, the learning goal for showing the base vector is to understand the meaning of a scalar multiple. For example, `3a` is the same as saying 3*`a`. I could see wanting to extend this to the component level, but I do still worry about adding clutter.

I think it would be good to double check with @ariel-phet and @kathy-phet and see if they still feel the same.

**Comment by pixelzoom** [comment]
Implementation wise, it looks like it's going to be non-trivial to show component vectors for the base vectors.

**Comment by ariel-phet** [comment]
@pixelzoom I agree with @arouinfar that it would be adding quite a bit of clutter. Given that in cartesian mode you "set" the components of the base vector, as well as that it would be a nontrivial change to the code, I think I would opt for not showing the components.

**Comment by pixelzoom** [comment]
This was originally assigned to @ariel-phet and @kathy-phet for feedback.  Is @kathy-phet onboard with this decision?

**Comment by kathy-phet** [comment]
I am good with not showing the components for the base vectors. It’s actually my preference, in general. Thanks for asking.

**Comment by pixelzoom** [comment]
There is consensus that no component vectors will be shown for base vectors.  That is the current behavior, so no changes are needed. Closing.
