### ISSUE TITLE
What color should the component vectors be for 'c' and 'f'? 

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/vector-addition#159]
In the Equations screen, vectors 'c' and 'f' are black. But their components are shown using the same color (blue) as the other vectors.  See screenshot below. This seems incorrect.  What color should the component vectors be for 'c' and 'f'? 

<img width="920" alt="screenshot_1428" src="https://user-images.githubusercontent.com/3046552/64136876-b5dcb280-cdc2-11e9-955d-f138565753c1.png">

**Comment by arouinfar** [comment]
Great point @pixelzoom. The color of component vectors should be related to the parent vector. In the case of `c` and `f` on the Equation Screen, that would mean dark gray.

I realize this may cause some conflict with the updated Base Vector colors, but we can asses once the component vector colors are updated.

**Comment by pixelzoom** [comment]
Looks like this is going to be complicated.  The current implementation requires that the components for all vectors in a "vector set" (including the sum vectors) must use the same colors for their component vectors.

**Comment by pixelzoom** [comment]
`VectorColorPalette` now has the ability to specify optional colors for the components of the sum vector.    For the Equations screen, the sum components are currently set to `rgb( 130, 130, 130 )`, and are easily changed in `VectorAdditionColors`.   

@arouinfar please review in master.

**Comment by arouinfar** [comment]
Looks great to me @pixelzoom! I think `rgb(130, 130, 130)` is the right choice for **c** and **f** components.
![image](https://user-images.githubusercontent.com/8419308/64368433-8fdc2b80-cfd7-11e9-8860-51c8624fc4e3.png)

I'm a bit concerned that the gray used for the base vectors is a bit too similar, so I will tinker with `VectorAdditionColors` in #153.
