### ISSUE TITLE
Very long sum arrow

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/vector-addition#161]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Chrome
**Problem description**
Found during https://github.com/phetsims/vector-addition/issues/125.  Related to https://github.com/phetsims/vector-addition/issues/106.
When you add a large number of vectors in the lab screen, the sum vector can be exceedingly long.  When click on it to adjust it, it tries to jump into the graph as described in #106.  However, when the sum is still too long to fit in the grid, it can't be moved or observed beyond this.
**Steps to reproduce**
1. Go to the lab screen
2. Pull out a large number of the same color type of vectors (example uses 20)
3. Turn on the corresponding sum vector
4. Click on and try to move sum vector

**Visuals**
![verylongsumarrow](https://user-images.githubusercontent.com/41024075/64206047-a73fdb00-ce56-11e9-8c56-efc63df6950f.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Vector Addition‬
URL: https://phet-dev.colorado.edu/html/vector-addition/1.0.0-dev.13/phet/vector-addition_en_phet.html
Version: 1.0.0-dev.13 2019-08-22 01:15:13 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by arouinfar** [comment]
Thanks for reporting @KatieWoe. In #152 we decided to change the drag bounds of vectors so that only the tail needs to remain on the grid, which would improve this interaction. 

We're still going to lose the tips of really large sums, but the interaction should feel much smoother.
