### ISSUE TITLE
Arrows on Equation Screen can be very off the grid

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/vector-addition#162]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Chrome
**Problem description**
Found during https://github.com/phetsims/vector-addition/issues/125.  Seems like a more severe version of https://github.com/phetsims/vector-addition/issues/113.
When you change equations the three vectors choose their location seemingly dependent on the origin.  However, if the origin has moved they can be significantly outside of the grid.  It can also be difficult to predict where that location will be.
**Steps to reproduce**
1. Go to the equation screen
2. Move the origin to the top right corner
3. Choose a new equation
4. Click the arrows outside of the graph
5. Move origin around and repeat

**Visuals**
![jumpingarrows](https://user-images.githubusercontent.com/41024075/64207079-1cacab00-ce59-11e9-8fc4-6387dc22c0ad.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Vector Addition‬
URL: https://phet-dev.colorado.edu/html/vector-addition/1.0.0-dev.13/phet/vector-addition_en_phet.html
Version: 1.0.0-dev.13 2019-08-22 01:15:13 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by KatieWoe** [comment]
Also note, reset all does not solve this.

**Comment by arouinfar** [comment]
Thanks for reporting @KatieWoe. This does indeed look like an extension of #113. Fortunately, these issues are now moot because of the changes coming in #148 -- the equation buttons will no longer be separate scenes.
