### ISSUE TITLE
C or F vectors disappear when reset all is used

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/vector-addition#163]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Chrome
**Problem description**
Found during https://github.com/phetsims/vector-addition/issues/125.
When you hit the orange reset all button on the Equation screen it causes the C or F vector (depending on the scene) to disappear.  The label is still there.  Changing the size of one of the other vectors will make it reappear.
**Steps to reproduce**
1. Go to the Equation screen
2. Hit the reset all button
3. Go to the angle scene

**Visuals**
![nomorecf](https://user-images.githubusercontent.com/41024075/64214769-f560d880-ce6e-11e9-9042-00c7a704a3c3.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Vector Addition‬
URL: https://phet-dev.colorado.edu/html/vector-addition/1.0.0-dev.13/phet/vector-addition_en_phet.html
Version: 1.0.0-dev.13 2019-08-22 01:15:13 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by arouinfar** [comment]
Nice find @KatieWoe. Scanning the repo, I don't think there's already an issue for this, so I'll assign @pixelzoom.

**Comment by arouinfar** [comment]
Looks like this was fixed in #129, but the commits came after dev.13 (version used for performance testing in #125) was published. The bug isn't present in master, so closing.
