### ISSUE TITLE
Vectors are hard to grab with touch

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/vector-addition#164]
Found during https://github.com/phetsims/vector-addition/issues/125.  When trying to pick up a vector either from the toolboxes or to move to a new location on the grid, it can be very difficult.  Trying to pick up a new vector from the toolboxes could be particularly frustrating.  Was using Leibniz (iOS 12.4.1).

**Comment by arouinfar** [comment]
Thanks @KatieWoe. We are working to address this issue in https://github.com/phetsims/vector-addition/issues/127.
