### ISSUE TITLE
incorrect labeling of magnitudes in Base Vectors accordion box

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/vector-addition#169]
In 1.0.0-dev.11 (baseline), and still in master, the Base Vectors accordion box looks like this for the polar snap mode:

<img width="176" alt="screenshot_1444" src="https://user-images.githubusercontent.com/3046552/64452639-c9cf2f80-d0b4-11e9-9a28-74caa25460a6.png">

@arouinfar shouldn't the magnitudes be labeled as |d&#8407;| and |e&#8407;|, with a vector arrow over each symbol?

**Comment by arouinfar** [comment]
@pixelzoom that's definitely a typo. The magnitude labels should have the arrow on top of the 'd' and 'e', as we do for the magnitude in the vector values panel.

**Comment by pixelzoom** [comment]
Fixed in the above commit, see screenshot below.  Alignment will be adjusted as part of https://github.com/phetsims/vector-addition/issues/140.

<img width="175" alt="screenshot_1445" src="https://user-images.githubusercontent.com/3046552/64481595-0b430600-d1ad-11e9-8a35-c465ea31e56d.png">
