### ISSUE TITLE
LAB SCREEN and Display Vector Panel

### ISSUE THREAD

**Issue by veillette** [phetsims/vector-addition#17]
For Explore1D and Explore2D, the vectors have a label which can be used to display the properties on the panel:
![image](https://user-images.githubusercontent.com/7633344/59137310-711cb900-8944-11e9-993f-3d46cffeddd6.png)

How should we handle the case of the lab screen where the vectors do not have a label?

**Comment by arouinfar** [comment]
@veillette on the Lab screen, vectors will have a label only when they are active. For regular vectors, the label would be "v", and for the sum the label would be "s".

**Comment by veillette** [comment]
We added a v label for Lab Screen.
![image](https://user-images.githubusercontent.com/7633344/59689565-dd51b500-91ad-11e9-89e0-7c926c3d254f.png)
Closing
