### ISSUE TITLE
label with coefficient overlaps vector

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/vector-addition#172]
This occurs in 1.0.0-dev.12 (baseline) and continues to occur in master. In the _Equations_ screen, setting a coefficient other than 1 results in the label overlapping the vector. 

Here's vector 'b' with coefficient 1:

<img width="141" alt="screenshot_1450" src="https://user-images.githubusercontent.com/3046552/64732717-8ef83d80-d4a0-11e9-8ae2-63b5469384b6.png">

Here's vector 'b' with coefficient 2. Note the slight overlap.

<img width="206" alt="screenshot_1451" src="https://user-images.githubusercontent.com/3046552/64732725-915a9780-d4a0-11e9-8753-0bd1d44ebbbb.png">

Here's vector 'b' with coefficient -2. Note that the overlap is greater, due to the minus sign.

<img width="155" alt="screenshot_1452" src="https://user-images.githubusercontent.com/3046552/64732936-0332e100-d4a1-11e9-8d66-7cec20296f8d.png">

I'm not sure if this is significant or worth addressing, so assign to @arouinfar to decide.

**Comment by arouinfar** [comment]
Thanks for checking @pixelzoom. I think the overlap is slight enough to be acceptable. The alternative would be to move the label out from the vector a bit more, but then it would look a bit dislocated from the vector on the other screens (or when the coefficient is 1).
