### ISSUE TITLE
move selected vector and all of its pieces to the front

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/vector-addition#173]
#19 and #91 deal with how to layer vectors on the graph.  @arouinfar and I discuss on Zoom, and decided that the most logical/flexible approach is to move the selected vector and all of its pieces (components, angle indicator, label) to the front.    This will allow the user to control which vector is "on top", and ensure drag access to the selected vector's tip and tail.

The back-to-front order for the selected vector's pieces is:

* components
* component labels
* main vector 
* angle indicator
* main vector label

We suspect that this may be nontrivial. Components, main vectors, and sum vectors currently appear to be rendered in separate layers (all main vectors in from of all components, and all sum vectors in front of all main vectors ). This results in an odd "interleaved" look when components are visible.

**Comment by pixelzoom** [comment]
Thinking about this more...  I think we may want to keep all component vectors in their own layer, behind main vectors.  I'll start with that approach to see how it looks.

**Comment by pixelzoom** [comment]
Discussed with @ariel-phet today on Zoom, and we're back to thinking that the correct thing to do is to move the selected vector _and its components_  to the front.

**Comment by pixelzoom** [comment]
Discussed with @ariel-phet today on Zoom, and we're back to thinking that the correct thing to do is to move the selected vector _and its components_  to the front.  Otherwise it can be difficult to see component labels due to interleaving with other vectors, e.g.:

<img width="217" alt="screenshot_1484" src="https://user-images.githubusercontent.com/3046552/64979230-82932c80-d874-11e9-8da0-500d487a0ccc.png">

**Comment by pixelzoom** [comment]
In the above commits, the selected vector pops to the front.  Unfortunately it's components pop to the front later, so the components are now in front of the selected vector.  I'll solve that problem next.

**Comment by pixelzoom** [comment]
This is resolved in master.  When any vector is selected, it moves to front, along with all of its "pieces" (components, labels, angle indicator).  All selectable vectors (main, sum, base) are treated identically.  

@arouinfar please review in master.  (Note that #94 is related and still in progress.)

**Comment by arouinfar** [comment]
Master is looking good @pixelzoom!
