### ISSUE TITLE
add θ symbol to angle checkbox icon

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/vector-addition#175]
... to strengthen the connection to θ in the "Vector Values" accordion box.

**Comment by pixelzoom** [comment]
Done in the above commit, see screenshot below.  @arouinfar please review. If you don't like this for some reason, it's easy to revert. 

<img width="793" alt="screenshot_1463" src="https://user-images.githubusercontent.com/3046552/64886307-17065080-d623-11e9-97d6-83ee1add339c.png">

**Comment by arouinfar** [comment]
Thanks @pixelzoom. I think adding the theta to the icon is a nice touch, so let's keep it.
