### ISSUE TITLE
polish the origin manipulator

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/vector-addition#176]
After we're done fiddling with #127:

* resize the origin manipulator so that it's not too inviting
* optimize its pointer areas - touchArea and (possibly) mouseArea

**Comment by pixelzoom** [comment]
I've adjusted the origin manipulator in the above commit. See screenshot below.  Notes:
* The origin manipulator's diameter is specified in model coordinates, and is currently `0.8`.
* The origin manipular's `touchArea` is a function of the  is diameter, and is currently `2 * diameter` or `1.6`. 
* The origin manipulator currently has no `mouseArea` specified, so it defaults to the manipulator's diameter, or `0.8`.

@arouinfar @ariel-phet  please review in master.

<img width="916" alt="screenshot_1478" src="https://user-images.githubusercontent.com/3046552/64894982-6f941880-d638-11e9-8b25-ca15f3b937de.png">

**Comment by ariel-phet** [comment]
Checked in Master, all is looking good to me for the manipulator.

**Comment by arouinfar** [comment]
Agreed, the origin manipulator looks good and is easy to grab on an iPad.
