### ISSUE TITLE
use dashed arrows for component vectors

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/vector-addition#177]
This was explored a bit in #84 (branch: dashedComponent), but there was no specific issue for this.  According to @ariel-phet, this is a "must have".

**Comment by pixelzoom** [comment]
`RootVector` is the base class for drawing a vector and its labels.  Adding support for dashed component vectors involves adding an options like `{string} arrowType: 'solid'|'dashed'`. If we use common code, the `arrowType` values would correspond to `ArrowNode` (solid) and `LineArrowNode` (dashed).

I took a pass at this, and ran into many non-trivial problems:
  
* `ArrowNode` and `LineNode` have different APIs (different options, different methods).

* `LineNode` doesn't support zero-magnitude vectors, which are present through the sim.  This support would need to be added, currently blocked by https://github.com/phetsims/scenery-phet/issues/532. 

* `LineNode` doesn't support a solid arrow head.  Adding this support will be a nontrivial project. Here's what using `LineNode` currently looks like:

<img width="141" alt="screenshot_1469" src="https://user-images.githubusercontent.com/3046552/64892163-ed542600-d630-11e9-9c24-f3c5b9b5c341.png">

* When components fall on the axes, they look awful, and `LineNode` has no way to "fill in" the gaps in the dashed tail.

<img width="312" alt="screenshot_1470" src="https://user-images.githubusercontent.com/3046552/64892198-0230b980-d631-11e9-94bf-9ced78f5f78a.png">

* Things get weird when components overlap. For example:

<img width="130" alt="screenshot_1473" src="https://user-images.githubusercontent.com/3046552/64892457-ad417300-d631-11e9-8398-37bc3297a511.png"> <img width="200" alt="screenshot_1474" src="https://user-images.githubusercontent.com/3046552/64892471-b29ebd80-d631-11e9-948f-7314f8854d49.png">

* The sim uses `ArrowNode.shape` to dilate `touchArea`. No such field exists for `LineNode`, and it cannot exist because `LineNode` can't be drawn using 1 `Shape`. In `RootVectorNode`, this would need to be short-circuited for component vectors, which is probably OK since they are not interactive:

```js
      if ( rootVector.magnitude > 0  ) {
        // Make the arrow easier to grab
        this.arrowNode.mouseArea = this.arrowNode.shape.getOffsetShape( ARROW_MOUSEAREA_OFFSET );
      }
```

**Comment by pixelzoom** [comment]
@ariel-phet @arouinfar based on the experience in https://github.com/phetsims/vector-addition/issues/177#issuecomment-531380247, we have 3 choices:

(1) Leave as is, with solid components.
(2) Modify `LineArrowNode` to support this sim's needs.
(3) Create a new type of arrow to support this sim's needs.


In either case, it's not clear what "this sim's needs" are.  The current suggestion of "do something and we'll tweak it" is not an option.   Please provide mockups that show how you'd like component vectors to look for the "component style" options, and in situations where components do and do not overlap.

**Comment by pixelzoom** [comment]
@ariel-phet @arouinfar @kathy-phet  Based on the experience in https://github.com/phetsims/vector-addition/issues/177#issuecomment-531380247, we have 3 choices:

(1) Leave as is, with solid components.
(2) Modify `LineArrowNode` to support this sim's needs.
(3) Create a new type of arrow to support this sim's needs.

@ariel-phet has previously indicated that (1) is not an option that he's willing to accept. 

Options (2) and (3) are both a significant amount of work, and will certainly delay the start of Natural Selection. It's not clear what "this sim's needs" are, so the current suggestion of "do something and we'll tweak it" is not a path forward.   If you'd like to pursue options (2) or (3), please provide mockups that show how you'd like component vectors to look for the "component style" options, and in situations where components do and do not overlap.

**Comment by pixelzoom** [comment]
Another option:

(4) Modify `ArrowNode` to support dashed tail, described as a single `Shape`, with continued support for all `Path` options (`fill`, `stroke`, etc.)  

This is my current favorite option.  Adding a solid head to `LineArrowNode` is contrary to the original purpose (and name) of that node, and I'd rather not deal with modifying it, and switching between `ArrowNode` and `LineNode`.   How I approach this option depends on how you want to treat gaps in the dash when vectors overlap each other, or overlap the axes.  So mockups are still needed.

**Comment by pixelzoom** [comment]
Discussed with @ariel-phet via Zoom.  We're going to proceed with option (4), adding `tailDash` feature to `ArrowNode`.  This will be generally useful in other future sims. Since @ariel-phet is confident that we won't need to be anything about filling spaces in the dash, I will proceed without mockups.

Notes:
* `tailDash` value will be similar to `SCENERY/Line` `lineDash`, e.g. `tailDash: [ 3, 2]`
* dash will be constructed from tail to tip, so that any partial dash (or space) is near the tip
* component vectors will be fully opaque, so I'll convert color palettes so that the hues look the same

**Comment by pixelzoom** [comment]
After hours of trying, adding a `tailDash` option to `ArrowNode` proved to be not feasible at this time, see https://github.com/phetsims/scenery-phet/issues/533.  So I implemented a sim-specific solution, that meets only the needs of this sim.  See [DashedArrowNode](https://github.com/phetsims/vector-addition/blob/master/js/common/view/DashedArrowNode.js).

The next step is to refined the `tailDash` pattern and colors for component vectors.  

The `tailDash` is currently `[ 6, 4 ]` and lives in [VectorAdditionConstants](https://github.com/phetsims/vector-addition/blob/master/js/common/VectorAdditionConstants.js).

Colors are all opaque, and live in [VectorAdditionColors](https://github.com/phetsims/vector-addition/blob/master/js/common/VectorAdditionColors.js) -- look for "componentFill" and "sumComponentFill".

@ariel-phet @arouinfar please review in master and let me know what you'd like to change.

**Comment by pixelzoom** [comment]
I forgot to mention, there's one wart that I'm planning to address.  The dashed tail currently extends past the vector head.  E.g.:

<img width="209" alt="screenshot_1486" src="https://user-images.githubusercontent.com/3046552/64998671-50002880-d8a2-11e9-8bcd-eaabfd268cfb.png">

**Comment by pixelzoom** [comment]
In the above commit, the tail length is adjusted so that it doesn't overlap the tip. See example screenshot below, compare to  https://github.com/phetsims/vector-addition/issues/177#issuecomment-531988432.

<img width="141" alt="screenshot_1489" src="https://user-images.githubusercontent.com/3046552/65001143-96a65080-d8ab-11e9-8e61-f19e494a5c90.png">

**Comment by pixelzoom** [comment]
Hmm... https://github.com/phetsims/vector-addition/commit/e3528b934c5097e140f2c20e76a85d476f5ac264 broke the _Explore 2D_ screen icon, and the tip-to-tail Components icon.

<img width="152" alt="screenshot_1490" src="https://user-images.githubusercontent.com/3046552/65010936-d894be00-d8ce-11e9-8322-7c80650d9d77.png">
<img width="166" alt="screenshot_1491" src="https://user-images.githubusercontent.com/3046552/65010940-db8fae80-d8ce-11e9-9371-c0121dc9999f.png">

**Comment by pixelzoom** [comment]
Issues mentioned in https://github.com/phetsims/vector-addition/issues/177#issuecomment-532050404 are fixed in the above commit.

**Comment by pixelzoom** [comment]
@ariel-phet and I (via Zoom) discussed some tweaks to the dash and colors. Before making those changes, I've published [1.0.0-dev.16](https://phet-dev.colorado.edu/html/vector-addition/1.0.0-dev.16/phet/vector-addition_en_phet.html).

**Comment by ariel-phet** [comment]
Removing my assignment until next iteration is ready to discuss

**Comment by arouinfar** [comment]
I'll also unassign myself until the changes mentioned in https://github.com/phetsims/vector-addition/issues/177#issuecomment-532347191 are ready for review.

**Comment by pixelzoom** [comment]
Tail dash has been adjusted. Colors will be handled in #184. 

@arouinfar and @ariel-phet please review this issue for:
* how the dashed arrows are working for component vectors
* whether [6,3] is an acceptable dash pattern

If those things are good, then we can close this issue, and address colors in #184.

**Comment by ariel-phet** [comment]
Personally, I think this is all looking quite good, we do need to dial in the colors (as will be done in #184), but all this work feels correct to me.

**Comment by arouinfar** [comment]
The dashed components are looking good to me, thanks @pixelzoom @ariel-phet! The dash pattern and relative component/axis weight looks good, even for the projected components. ![image](https://user-images.githubusercontent.com/8419308/65171984-5bba2f00-da09-11e9-86e7-326497c3ac1b.png)
