### ISSUE TITLE
make axes thinner

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/vector-addition#178]
... requested by @ariel-phet.

**Comment by pixelzoom** [comment]
Changes in master, as suggested by @ariel-phet via Zoom:

* axes tailWidth reduced from 3 to 1.5
* vectors tailWidth increased from 3 to 3.5
* major grid lineWidth reduced from 1.8 to 1.5 (must be <= axes tailWidth)
* minor grid lineWidth reduced from 1.2 to 1

@arouinfar please review in master, compare to [1.0.0-dev.15](https://phet-dev.colorado.edu/html/vector-addition/1.0.0-dev.15/phet/vector-addition_en_phet.html).

**Comment by arouinfar** [comment]
The changes all look really clean, thanks @ariel-phet @pixelzoom!
