### ISSUE TITLE
fix cursors

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/vector-addition#179]
Cursor for translate is a 4-way arrow (✥), used for vectors and origin manipulator.

Cursor for vector rotate/scale is a hand: <img width="33" alt="screenshot_1483" src="https://user-images.githubusercontent.com/3046552/64976598-f3cfe100-d86e-11e9-8d8a-8225133e5f12.png">

Current problems:

* translate cursor changes to a rotate/scale cursor when drag starts, for vectors and origin
* vector label is interactive, but shows no  cursor, should show the "translate" cursor
* vector toolboxes use a rotate/scale cursor, but does a translate

**Comment by pixelzoom** [comment]
Fixed in master, @arouinfar please review.

**Comment by arouinfar** [comment]
Looks good in master @pixelzoom
