### ISSUE TITLE
Z-ordering and graph setup

### ISSUE THREAD

**Issue by brandonLi8** [phetsims/vector-addition#18]
![image](https://user-images.githubusercontent.com/42391580/59164591-1b731880-8acc-11e9-902d-323d2d1db664.png)
Right now, the sum is behind the vectors, which isn't correct.

Since we are creating `graph.js` model (similar to graphing lines), the vectors observable array is going to live inside this model so that on 1d each scene has its own observable array.
Thus I think it makes since to put the vectors as children inside the `graph.js` node instead of the `commonScreenView` (where they are now). @veillette thoughts?

I can work on `graph.js` on monday, but this would change a lot of view's api. We would in a lot of cases have to pass the graph along with model stuff.

Here is a list of things I think should live in graph.js model
- upperLeftPositionProperty,
- sumVisibleProperty
- vectorSum
- vectors
- gridModelBounds
- gridVisibleProperty
- valuesVisibleProperty
- angleVisibleProperty
- vectorOrientationProperty
(basically the common model is now graph.js, all of the above in my opinion are specific to a single graph, and very from scene to scene and should thus be in graph.js. The commonModel now just creates and instantiates this graph. In the case of the 1dmodel it would just create 2 graph.js @veillette thoughts?)

**Comment by brandonLi8** [comment]
Now that I think about it, the sum node should be created in `graph.js` as-well, since each scene in 1D has its own sum. 

If this is the case, every vector node would be created in graphNode.js. 

The problem with this is that:
1. GraphNode is already large, and is only getting larger (we can split into separate modules if needed. 2. The zOrdering is still wrong because the vectorNodes are created with the drop of the decoyIcon and are created after, which means the sum will still be behind the vectors

**Comment by veillette** [comment]
I think this issue is conflating two aspects that are separate and distinct. 
(1) The z -ordering of the vectors and vector sum
(2) How to show incorporate scenes within a screen

**Comment by veillette** [comment]
The previous commit shows how we can puth all the vectors within a particular scenery layer such as they are always under the vector sum.

**Comment by brandonLi8** [comment]
Looks good, but should we still put all vectors in graph node?

**Comment by veillette** [comment]
To tackle the second point you raised, I agree that adding the vector Nodes  and vectorSumNode on the commonSCreenView is inappropriate if we want scenes.

**Comment by brandonLi8** [comment]
Got it, I can work on `graph.js` on monday and perhaps moving the vectorLayer that you just made over to graphNode.js

**Comment by veillette** [comment]
And I also concur that the vectors (sum and regular vectors) ahould be attached to a separate scenery Node (that is not the commonScreenView) but probably different than GraphNode since GraphNode is already so large. GraphNode would be a logical place to put it though if it wasn't already so large.

**Comment by brandonLi8** [comment]
We can create a module called something like vectorNodesLayer and add it as a child inside of graph node. GraphNode.js would only add 2 lines, one is importing the module and the other is adding it.

**Comment by veillette** [comment]
This idea is in the right direction. 
Ultimately though we may need to refactor the names as the name VectorNodesLayer does not suggest that it is a parent of the graphNode so it is somewhat misleading, but structurally I agree that this is the correct  approach to start supporting scenes.

**Comment by veillette** [comment]
Scenes are now supported and the Z-order is tracked in a separate issue (#19). Closing
