### ISSUE TITLE
increase length of vector for Sum checkbox icon

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/vector-addition#180]
While looking at the sim via Zoom with @ariel-phet, he suggested increasing length of vector for Sum checkbox icon.   This was prompt by the longer vector icons that we used for the 'show base vectors' checkbox in #153.

**Comment by pixelzoom** [comment]
Increased vector length from 22 to 30.  @arouinfar please review in master.  Before after screenshots below.

Before:

<img width="226" alt="screenshot_1481" src="https://user-images.githubusercontent.com/3046552/64976172-e23a0980-d86d-11e9-840e-fa75f907d19a.png"> <img width="222" alt="screenshot_1482" src="https://user-images.githubusercontent.com/3046552/64976179-e5cd9080-d86d-11e9-99cd-63150a8dfa74.png">

After:

<img width="232" alt="screenshot_1479" src="https://user-images.githubusercontent.com/3046552/64976194-ecf49e80-d86d-11e9-97a9-3129dac254d6.png"> <img width="224" alt="screenshot_1480" src="https://user-images.githubusercontent.com/3046552/64976200-ef56f880-d86d-11e9-8bf5-f0183b3fdea9.png">

**Comment by arouinfar** [comment]
Looks great @pixelzoom!
