### ISSUE TITLE
adjust vector colors

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/vector-addition#184]
After changing component vectors to have dashed tails in https://github.com/phetsims/vector-addition/issues/177, @ariel-phet and I discussed color palette changes via Zoom.  This issue is to track those changes.

**Comment by pixelzoom** [comment]
Goals:
* Good contrast
* Good differentiation and association of colors.
* Differentiation between sum components and non-sum components.

Changes we discussed and that I'll proceed with:
* Now that component vectors are dashed, use the same color for main vector and its components. 
* Use 'black' for sum vector and its components in _Explore 1D_, _Explore 2D_, and _Equation_ screens. This provides nice contrast. 
* For the the _Lab_ screen, we have 2 sums, so we need to different colors for sum vector and its components.  Try using dark shades of the main vector colors.

Things we discussed but abandoned:
* For _Lab_ screen, we tried sum vectors that are black with a stroke that matches the main vector color. This didn't look bad.  But it gave us no way to differentiate the sum components, because dashed vectors cannot be stroked.

**Comment by arouinfar** [comment]
> Differentiation between sum components and non-sum components.

Yes! This is something that has really been concerning me when reviewing the dashed components. 

> Now that component vectors are dashed, use the same color for main vector and its components.

:+1:

> Use 'black' for sum vector and its components in Explore 1D, Explore 2D, and Equation screens. This provides nice contrast.
> For the the Lab screen, we have 2 sums, so we need to different colors for sum vector and its components. Try using dark shades of the main vector colors.

I'm not so sure I like this direction. Yes, black has nice contrast, but **c** and **f** not necessarily sums. Dashed black is also more challenging on the grid, so I would like to use it sparingly. It also concerns me that Lab screen would be different from Explore 1D and Explore 2D. I would rather use darker shades of of the vector color on Explore 1D, Explore 2D, and Lab, and leave the Equations screen black.

**Comment by pixelzoom** [comment]
[1.0.0-dev.16](https://phet-dev.colorado.edu/html/vector-addition/1.0.0-dev.16/phet/vector-addition_en_phet.html) was publish before any color changes were made.

[1.0.0-dev.17](https://phet-dev.colorado.edu/html/vector-addition/1.0.0-dev.17/phet/vector-addition_en_phet.html) contains the changes suggested by @ariel-phet.   I also used 'black' for the Component radio button icons, since associating them with any specific vector color seemed incorrect/misleading. 

Unfortunately, I received @arouinfar's concerns about the sum vector changes after I had done this work.  I can revert and/or make further changes, but I'd like to have a consensus before I make further changes.   Assigning to @arouinfar and @ariel-phet to work on that consensus.

**Comment by pixelzoom** [comment]
@ariel-phet @arouinfar In the above commits:

* Colors have been reverted to 1.0.0-dev.16 
* I created separate (independent) color palettes for each screen.  You will find them towards the bottom of  [VectorAdditionColors.js](https://github.com/phetsims/vector-addition/blob/master/js/common/VectorAdditionColors.js).
* At the top of [VectorAdditionColors.js](https://github.com/phetsims/vector-addition/blob/master/js/common/VectorAdditionColors.js), you'll find constants `BLUE`, `PURPLE`, `RED`, `GREEN`.  If you change these, they apply to all color palettes.

Please use this to experiment with colors in your working copy. If you're not comfortable with editing the .js file, then we'll need to discuss adding a `ColorProfile` so that you can edit via vector-addition-colors.html.

**Comment by ariel-phet** [comment]
So it sounds like @arouinfar is on the same page in terms of matching colors of vectors and their components. It seems then we just need the right strategy of choosing colors. Just for reference, some screenshots, of what to me is an example of a pedagogically vital case. 

With black sum vectors:

![black](https://user-images.githubusercontent.com/4051174/65086722-1c8bcf80-d970-11e9-88b5-23ed0ca3a7c7.PNG)

with darker blue sum vectors

![blue](https://user-images.githubusercontent.com/4051174/65086731-244b7400-d970-11e9-8ff0-a71f9951adb5.PNG)

And darker in the case of the magenta

![magenta](https://user-images.githubusercontent.com/4051174/65086740-2b728200-d970-11e9-9ad3-f816832f1bce.PNG)

To me, the black certainly wins the contrast goal, but I understand the concerns @arouinfar raised. It seems that if we go with the theme of lightening the main vectors a touch, using darker shade sum vectors, and then using black vectors for *c* and *f* on the equations screen we will be good to go, and meet all goals well. So up to @arouinfar and I to come up with some colors we think work well.

**Comment by ariel-phet** [comment]
Worked with @arouinfar, she will be putting color choices into this issue. I think we also decided we would like to use the blue for Component radio buttons, the black and gray just looks a little too muted.

**Comment by arouinfar** [comment]
@pixelzoom we decided to change the red to pink, and use a darker shade for the sum on Explore 1D, Explore 2D, and Lab. We would like to keep **c** and **f** black on the Equations screen.

| Basic Color | Sum Color |
| --- | --- | 
| BLUE, no change | `rgb( 5, 85, 125 )` |
| PURPLE, no change | `rgb( 84, 2, 128 )` |
| `rgb( 255, 53, 133 )` | `#800133` (The equivalent rgb value in Illustrator -- `rgb( 128, 1, 151 )` -- shows up purple in my local copy and in the GitHub preview, which is why I've provided a hexcode.) |
| GREEN, no change | `rgb( 2, 75, 0 )` |




Here are some screenshots of the colors that @ariel-phet and I decided on.
![image](https://user-images.githubusercontent.com/8419308/65169684-42fb4a80-da04-11e9-80ef-1e3c6d075394.png)
![image](https://user-images.githubusercontent.com/8419308/65169720-5c03fb80-da04-11e9-9b16-4cf346254fe6.png)
![image](https://user-images.githubusercontent.com/8419308/65169559-03ccf980-da04-11e9-8eaa-d1e5fa00761b.png)
![image](https://user-images.githubusercontent.com/8419308/65169650-31b23e00-da04-11e9-944a-5eef2ea943ff.png)

**Comment by pixelzoom** [comment]
@arouinfar thanks for the clear specification! Updated in master and [1.0.0-dev.19](https://phet-dev.colorado.edu/html/vector-addition/1.0.0-dev.19/phet/vector-addition_en_phet.html). Please review.

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/vector-addition/issues/184#issuecomment-532787291, @arouinfar said:
> `#800133` (The equivalent rgb value in Illustrator -- `rgb( 128, 1, 151 )` -- shows up purple in my local copy and in the GitHub preview, which is why I've provided a hexcode.)

I investigated this. `#800133` is `rgb( 128, 1, 51 )`, not `rgb( 128, 1, 151 )` -- the blue components are different. So I'm guess that this was due to a typo when copying values from Illustrator.

**Comment by arouinfar** [comment]
dev.19 looks great, thanks @pixelzoom!

> I investigated this. #800133 is rgb( 128, 1, 51 ), not rgb( 128, 1, 151 ) -- the blue components are different. So I'm guess that this was due to a typo when copying values from Illustrator.

🤦‍♀ well, at least that explains things!
