### ISSUE TITLE
format of class names is different in comments

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/vector-addition#186]
For some reason, class names do not appear in camelcase in comments, e.g `VectorCreatorPanel`.  Instead, spaces are added between the words, e.g. "Vector Creator Panel".  Here's an example in SceneNode:

```js
    /**
     * Adds a Vector Creator Panel to the scene.
     * @public
     * @param {VectorCreatorPanel} vectorCreatorPanel
     */
    addVectorCreatorPanel( vectorCreatorPanel ) {
      assert && assert( vectorCreatorPanel instanceof VectorCreatorPanel, `invalid vectorCreatorPanel: ${vectorCreatorPanel}` );

      this.addChild( vectorCreatorPanel );
      vectorCreatorPanel.moveToBack(); // move to back to ensure that this.vectorContainer remains in front
    }
```

This is pervasive in the code. It has made it very difficult to rename things, and I've fixed some of these as I've encountered them.  But there are undoubtedly some comments that are now out of sync with class names.  I'm not sure that it's worth the cost to fix this, but wanted @brandonLi8 to be aware of this for future coding.

**Comment by pixelzoom** [comment]
And it's not only class names.  Here's another example, `activeVectorProperty` vs "active vector Property" in `VectorValuesToggleBox`.      This would have made it difficult to make the change that I considered in https://github.com/phetsims/vector-addition/issues/182.

```js
      // Observe changes to when the graphs active vector Property changes to update the panel.
      // Doesn't need to be unlinked since the panel exists for the entire simulation.
      graph.activeVectorProperty.link( ( activeVector, oldActiveVector ) => {
```

**Comment by brandonLi8** [comment]
@pixelzoom, thank you. Really good to know. I will keep this in mind next time.

**Comment by pixelzoom** [comment]
I've been fixing these as I encounter them, but it's unlikely that I'll take the time to address all of them.

**Comment by pixelzoom** [comment]
I've been through all of the code, and I think that most (all?) of these have been addressed. So closing.
