### ISSUE TITLE
eraser button is inconsistent for sum vectors

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/vector-addition#187]
This has been bothering me since we implemented https://github.com/phetsims/vector-addition/issues/139.  

It seems odd that the sum vector(s) remain on the graph after pressing the eraser button. Perhaps pressing the eraser button should uncheck the Sum checkbox(es), and remove the sum vector(s) from the graph?  

For example, the current behavior is:
1. Got to the Lab screen.
2. Check both "Sum" checkboxes; the eraser button is still disabled.
3. Put a blue and red vector on the graph.
4. Press the eraser button. The eraser button is disabled, but the sum vectors remain on the graph.

Proposed behavior:
1. Got to the Lab screen.
2. Check both "Sum" checkboxes; the eraser button is becomes enabled.
3. Put a blue and red vector on the graph.
4. Press the eraser button. The eraser button is disabled, the "Sum" checkboxes are unchecked, and the sum vectors are removed from the graph.

So the state of the eraser button would include _all_ vectors, and pressing the eraser button would remove _all_ vectors from the graph.

@arouinfar your opinion?

**Comment by pixelzoom** [comment]
Note to self: Visibility of sum vector labels is set in `SumVector`:

```js
      // @private {function} isSymbolDisplayed - function to check if the sum vector should display its symbol.
      // The sum vector only displays the symbol when either a vector in its vector set is active, the sum is active, or
      // the activeVectorProperty.value is null
      this.isSymbolDisplayed = () => {
        return vectorSet.vectors.some( vector => vector === graph.activeVectorProperty.value )
               || graph.activeVectorProperty.value === this
               || graph.activeVectorProperty.value === null;
      };
```

**Comment by pixelzoom** [comment]
Raising priority, since we're trying to get into dev testing by 10/1.

**Comment by pixelzoom** [comment]
Discussed with @arouinfar on Zoom.  We're going to try hiding the sum vector(s) when there are no other vectors on the graph.  That should address this weirdness, and the buggy behavior in #160.

**Comment by pixelzoom** [comment]
Addressed  in the above commit.  The sum vector will only be displayed when the Sum checkbox is checked _and_ the sum is defined. 

@arouinfar please review in master.

**Comment by pixelzoom** [comment]
Rats, this is not totally fixed -- the value is being shown when "Values" is checked.

<img width="532" alt="screenshot_1502" src="https://user-images.githubusercontent.com/3046552/65535963-b3e8a980-debf-11e9-9f19-7f6899b07639.png">

**Comment by pixelzoom** [comment]
Fixed again :)  I had to introduce a new BooleanProperty in SumVector, `isDefinedProperty`.

@arouinfar please review in master.

**Comment by pixelzoom** [comment]
Fix also appears in https://phet-dev.colorado.edu/html/vector-addition/1.0.0-dev.20/phet/vector-addition_en_phet.html.

**Comment by arouinfar** [comment]
Looks good in master and dev.20 @pixelzoom, thanks!

**Comment by pixelzoom** [comment]
Reopening.  When "Values" is checked, the sum component vector values (and leader lines) are still being displayed.  For example:

<img width="1020" alt="screenshot_1518" src="https://user-images.githubusercontent.com/3046552/65634610-d9e37c00-df9b-11e9-9c45-ba3710afcc21.png">

**Comment by pixelzoom** [comment]
Moved the issue described in https://github.com/phetsims/vector-addition/issues/187#issuecomment-535185087 to https://github.com/phetsims/vector-addition/issues/195. Re-closing,
