### ISSUE TITLE
how to display vector with zero angle

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/vector-addition#189]
@arouinfar is this what you want displayed for a vector that has 0 angle? Just checking.

<img width="177" alt="screenshot_1495" src="https://user-images.githubusercontent.com/3046552/65258256-d2196880-dabf-11e9-9178-85f6c0548d87.png">

**Comment by arouinfar** [comment]
@pixelzoom generally, yes that looks good to me, though we may want to keep the label below the vector as we do for small angles. This will help avoid collision issues between the angle readout and the vector label for small vectors..
![image](https://user-images.githubusercontent.com/8419308/65261389-6639fe80-dac5-11e9-8775-52299c8e0fa4.png)

**Comment by pixelzoom** [comment]
OK. General layout and overlap to be addressed in #93, so closing this issue.
