### ISSUE TITLE
generalize GridBox

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/vector-addition#190]
`GridLayoutBox` (used for layout of the Components radio buttons) looks nice, and I think it will be a candidate for migrating to scenery-phet or scenery.  So I'm going to spend a little time on cleanup and generalization.

**Comment by pixelzoom** [comment]
Generalization has been done.

**Comment by pixelzoom** [comment]
Renamed to `GridBox`.

**Comment by pixelzoom** [comment]
Next steps is either:

(1) Stop here and let the next person who needs GridBox move it to a common-code repo.

(2) Decide which common-code repo it belongs in and move it now. 

Labeling for developer meeting to decide.

**Comment by pixelzoom** [comment]
@ariel-phet if you'd like to make a decision, feel free to preempt developer discussion.

**Comment by samreid** [comment]
Does the GridBox assume its children are all the same size?  To explore this question, I started with scale 0.2 and bumped it up by 0.2 for each button, and the result looked like this:

<img width="250" alt="image" src="https://user-images.githubusercontent.com/679486/65657140-6ebb9900-dfdf-11e9-84a1-771dc5120949.png">

Is this as expected?

**Comment by zepumph** [comment]
I'm curious what @jonathanolson did in area model, because I thought there was this sort of component there. Does the generalization that @pixelzoom worked on here support your use case?

**Comment by pixelzoom** [comment]
> Does the GridBox assume its children are all the same size? 

Apparently it does.  That would need to be fixed, presumably with an AlignGroup.

**Comment by pixelzoom** [comment]
> Does the GridBox assume its children are all the same size? 

Apparently it does.  That would need to be fixed, presumably with an AlignGroup.

And I'm guessing that it made that assumption because it was an inner type of a radio button group, where all buttons are the same size.

**Comment by pixelzoom** [comment]
In the commits above, `AlignGroup` and `AlignBox` are used to ensure that each cell in the grid is the same size, and that nodes are aligned in those cells based on options `xAlign` and `yAlign`.  

Examples:

`{ xAlign: 'center', yAlign: 'center' }` (the defaults):

<img width="181" alt="screenshot_1533" src="https://user-images.githubusercontent.com/3046552/65712318-022eb180-e054-11e9-90c2-0cc6d1662005.png">

`{ xAlign: 'left', yAlign: 'top' }`:

<img width="182" alt="screenshot_1534" src="https://user-images.githubusercontent.com/3046552/65712341-0d81dd00-e054-11e9-8956-64b4b149d2d2.png">

`{ xAlign: 'right', yAlign: 'bottom' }`:

<img width="183" alt="screenshot_1532" src="https://user-images.githubusercontent.com/3046552/65712354-15418180-e054-11e9-8135-050c911881cf.png">

**Comment by pixelzoom** [comment]
Here's an example with option `columns: 3`.  Children are processed in row-major order, so cells are filled from top-to-bottom, left-to-right.

<img width="189" alt="screenshot_1535" src="https://user-images.githubusercontent.com/3046552/65714208-e5947880-e057-11e9-8a3f-445edd3b1d07.png">

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/vector-addition/issues/190#issuecomment-535348091, @zepumph said:
> I'm curious what @jonathanolson did in area model, because I thought there was this sort of component there. Does the generalization that @pixelzoom worked on here support your use case?

I'd also like to hear from @jonathanolson.

**Comment by jonathanolson** [comment]
> Does the generalization that @pixelzoom worked on here support your use case?

This looks useful, and could probably be used in GenericLayoutSelectionNode. I had the simple case where every icon was the same size, so it could just use HBoxes in a VBox.

**Comment by pixelzoom** [comment]
@jonathanolson would you recommend moving this to scenery or scenery-phet?

**Comment by jonathanolson** [comment]
I think scenery would be the best option (as we already have pure-layout there).

One thing that's helpful about our current layout containers is that you can change their children and they re-layout. Would that be an option for GridBox?

**Comment by pixelzoom** [comment]
Changing children _could_ be an option, but it's not currently supported.  And it (probably?) wouldn't be the same API as `LayoutBox/HBox/VBox`, since it's not a subclass of `LayoutBox`.  Suggestions for the API?

**Comment by jonathanolson** [comment]
In an ideal world, I'd imagine it would function similarly to LayoutBox, but with the differences based on it being a grid.

**Comment by pixelzoom** [comment]
`GridBox` has 1 child, a `VBox` that handles layout of the rows (`HBox`).  So if we want to support the same "dynamic children" API as LayoutBox, where's going to have to do some "clever" things to support `addChild`, `removeChild`, `getChildren`, etc. -- essentially to make the children of `GridBox` look different than reality.

**Comment by jonathanolson** [comment]
Very true, those constraints change things. That sounds like a good API to me.

**Comment by samreid** [comment]
But `GridBox` would still have `addChild`/`removeChild` etc.  Would we just ask that clients not call those?

**Comment by jonathanolson** [comment]
> But GridBox would still have addChild/removeChild etc. Would we just ask that clients not call those?

Presumably. An alternative would be to reimplement it fully so it doesn't rely on the child containers.

**Comment by samreid** [comment]
> An alternative would be to reimplement it fully so it doesn't rely on the child containers.

I know it was quick and easy to make an initial implementation based on a VBox of HBoxes, but it seems a good idea to investigate implementing the layout without needing child containers.

**Comment by pixelzoom** [comment]
> But GridBox would still have addChild/removeChild etc. Would we just ask that clients not call those?

There would be no harm in using addChild/removeChild.  But they would decorate the GridBox, rather than change its contents.

> I know it was quick and easy to make an initial implementation based on a VBox of HBoxes, but it seems a good idea to investigate implementing the layout without needing child containers.

That's not something I'm interested in.  If that's the consensus, then we'll leave `GridBox` in vector-addition, and the next developer who needs a grid layout can decide how to proceed.

**Comment by samreid** [comment]
> There would be no harm in using addChild/removeChild. But they would decorate the GridBox, rather than change its contents.

We may decide that is accptable behavior, but it would be different than the behavior in VBox or HBox (which organizes elements added with `addChild`).

**Comment by pixelzoom** [comment]
I've implemented the API described in https://github.com/phetsims/vector-addition/issues/190#issuecomment-538019011.  It took ~10 minutes, and the implementation is straightforward.

**Comment by pixelzoom** [comment]
I've implemented the API described in https://github.com/phetsims/vector-addition/issues/190#issuecomment-538019011.  It took ~10 minutes, and the implementation is straightforward.   

If someone wants to pursue a more complicated implementation, go for.  But this seems like a very appropriate application of `HBox` and `VBox`.  And I don't feel that matching the LayoutBox API is worth the added complexity and costs.

**Comment by zepumph** [comment]
I think I mostly agree with @pixelzoom, but I'm also curious about a "half" solution where we factor out a way to change the Node list, and call some sort of "updateView" function which recreates the H/Vboxes. Would this cover all of the dynamic cases we come across?

**Comment by samreid** [comment]
I'm not sure how the preceding comment could work.  If you call `addChild`, it cannot simply `update` itself with all of `this.children` because they are doubly-nested in the containers.  At a minimum, we would need steps to gather children from the hbox and vboxes, and I'm not sure that's desirable.

**Comment by pixelzoom** [comment]
Dev meeting 10/10/19 consensus:

Lots of questions and disagreement on what the API for `GridBox` should be.  So this is going to remain in vector-addition, and the next developer who needs a grid layout can use this as inspiration (or not) for something that everyone is comfortable with putting in scenery.

Closing.
