### ISSUE TITLE
Highlight component labels/values for selected vector.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/vector-addition#192]
@ariel-phet discussed with @arouinfar. Consensus is that this would be good, especially for cases like this where labels overlap:

<img width="766" alt="screenshot_1516" src="https://user-images.githubusercontent.com/3046552/65617937-bcea8100-df7a-11e9-92f7-09bc35c675b0.png">

**Comment by pixelzoom** [comment]
Ugh. This turns out to be really difficult.  A label can be highlighted only if the vector is selected.  And component vectors cannot be selected.   Relevant code in VectorLabelNode:

```js
        // Active vectors have different background colors
        this.backgroundRectangle.fill = ( this.activeVectorProperty.value === this.rootVector ) ?
                                        VectorAdditionColors.ACTIVE_VECTOR_LABEL_BACKGROUND :
                                        this.rootVector.vectorColorPalette.labelBackgroundFill;
```

**Comment by pixelzoom** [comment]
I solved this by moving the responsibility for highlight labels from `VectorLabelNode` to `VectorNode` and `ComponentVectorNode`.  

@arouinfar please verify in [1.0.0-dev.22](https://phet-dev.colorado.edu/html/vector-addition/1.0.0-dev.22/phet/vector-addition_en_phet.html).

**Comment by arouinfar** [comment]
This is looking really nice @pixelzoom!

The highlighting makes things so much clearer when it crowded situations like this.
![labels](https://user-images.githubusercontent.com/8419308/65635431-896d1e00-df9d-11e9-862b-077280ccdcca.gif)
