### ISSUE TITLE
Default magnitude in polar mode is non-integer

### ISSUE THREAD

**Issue by arouinfar** [phetsims/vector-addition#193]
On Explore 2D and Lab the default magnitude of the vectors in polar mode is a non-integer (left). Clicking on the tip will correct this issue (right).
<img src="https://user-images.githubusercontent.com/8419308/65624493-430cc480-df87-11e9-818c-5c463619d156.png" width=200> <img src="https://user-images.githubusercontent.com/8419308/65624541-5ae44880-df87-11e9-97a7-e43b51ffbe2d.png" width=200>

There's a similar issue on the Equation screen. On startup, vector **e** shows a magnitude of 7.1, but its base vector is correct. 
![image](https://user-images.githubusercontent.com/8419308/65624618-80715200-df87-11e9-833e-e2efd2cde18f.png)

Changing the coefficient of in front of vector **e** will correct this issue.
<img src="https://user-images.githubusercontent.com/8419308/65624985-2cb33880-df88-11e9-8fd1-9051ec5c73d8.png" width=200>

It looks like these vectors are being given the cartesian coordinates of <5, 5> on startup, rather than the appropriate <7, 45°> in polar coordinates.

**Comment by pixelzoom** [comment]
This doesn't appear to be a problem in [1.0.0-dev.12](https://phet-dev.colorado.edu/html/vector-addition/1.0.0-dev.12/phet/vector-addition_en_phet.html), so must have been introduced since I started working on the sim.

**Comment by pixelzoom** [comment]
I'm not sure how this was ever working.  I found no evidence of initial vectors being created in polar form with magnitude 7.    Maybe there was something that created them in Cartesian coordinates, then snapped to polar.  In any case, it's addressed in the above commit. 

@arouinfar please review in [1.0.0-dev.23](https://phet-dev.colorado.edu/html/vector-addition/1.0.0-dev.23/phet/vector-addition_en_phet.html).

**Comment by arouinfar** [comment]
Thanks @pixelzoom. This is all looking good. However, now that I look at it a bit more, I think it might be better to choose a default magnitude where the vector tip isn't so close to a grid intersection so the difference between the cartesian scene is more noticeable. 

![image](https://user-images.githubusercontent.com/8419308/65706577-fe952d80-e047-11e9-85b7-1072181153cf.png)

@pixelzoom can you bump up the default magnitude of polar vectors to 8? This would apply to all screens with a polar scene.

**Comment by arouinfar** [comment]
Looks like I may have spoken a bit too fast. On the Equations screen, let's bump the magnitude of **e** up to 8, but leave **d** alone.

I noticed that **d** was vertical on the Equations screen, and is now horizontal. I'd like to keep that change, as it helps visually differentiate the cartesian and polar scenes a bit more.

**Comment by pixelzoom** [comment]
Done in master, @arouinfar please review.

**Comment by arouinfar** [comment]
@pixelzoom can you apply the change to all polar vectors on the Explore 2D & Lab screens too?

**Comment by pixelzoom** [comment]
Done, @arouinfar please verify in master.  Check all vectors in all screens, because I created shared constant values for initial vector components, magnitude, and angle in `VectorAdditionConstants`.

**Comment by arouinfar** [comment]
I checked all screens and vector types, and the initial values are all looking correct. Thanks @pixelzoom!
