### ISSUE TITLE
sum component values and leader lines are displayed for undefined sum

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/vector-addition#195]
Bug related to changes in https://github.com/phetsims/vector-addition/issues/187. 

When "Values" is checked, the sum component vector values (and leader lines) are still being displayed in [1.0.0-dev.20](https://phet-dev.colorado.edu/html/vector-addition/1.0.0-dev.20/phet/vector-addition_en_phet.html.).  For example:

<img width="1020" alt="screenshot_1518" src="https://user-images.githubusercontent.com/3046552/65634610-d9e37c00-df9b-11e9-9c45-ba3710afcc21.png">

**Comment by pixelzoom** [comment]
Fixed, @arouinfar please verify in [1.0.0-dev.25](https://phet-dev.colorado.edu/html/vector-addition/1.0.0-dev.25/phet/vector-addition_en_phet.html).

**Comment by arouinfar** [comment]
I'm unable to reproduce in dev.25, closing.
