### ISSUE TITLE
finalize placement of radio buttons in the Equation accordion box

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/vector-addition#196]
In https://github.com/phetsims/vector-addition/issues/128, we decided that the location of the radio buttons in the Equation accordion box would be determined based on interviews.  See that issue for discussion of pros and cons, starting at https://github.com/phetsims/vector-addition/issues/128#issuecomment-535214148.

The `equationButtons` query parameter takes values `left` and `right` (the default), which determines where the radio buttons are placed in the Equation accordion box.   Here's a comparison, reproduced from https://github.com/phetsims/vector-addition/issues/128#issuecomment-535249068:

With `?equationButtons=left`:

<img width="739" alt="screenshot_1525" src="https://user-images.githubusercontent.com/3046552/65644364-474dd780-dfb1-11e9-81df-dff25cf00fcc.png">
<img width="742" alt="screenshot_1526" src="https://user-images.githubusercontent.com/3046552/65644373-4ae15e80-dfb1-11e9-9bda-d1d6790f3d1c.png">
<img width="740" alt="screenshot_1527" src="https://user-images.githubusercontent.com/3046552/65644380-4e74e580-dfb1-11e9-8346-547d022c1ecd.png">

With `?equationButtons=right` (the default):

<img width="742" alt="screenshot_1528" src="https://user-images.githubusercontent.com/3046552/65644391-5765b700-dfb1-11e9-9669-27baac90213c.png">
<img width="741" alt="screenshot_1529" src="https://user-images.githubusercontent.com/3046552/65644396-592f7a80-dfb1-11e9-9e3b-53fc6b0cd575.png">
<img width="738" alt="screenshot_1530" src="https://user-images.githubusercontent.com/3046552/65644398-5a60a780-dfb1-11e9-9656-f8f9387dee70.png">

**Comment by pixelzoom** [comment]
The current vote on this (as I understand it) is:

* @arouinfar - button on right
* @ariel-phet - whatever @arouinfar decides
* @kathy-phet - buttons on left
* @pixelzoom - buttons on left

**Comment by arouinfar** [comment]
> @arouinfar - buttons on right

My opinion is a bit more nuanced. I think buttons on left looks better, but I suspect buttons on right might be preferable flow-wise if the goal is for students to experiment with the coefficients in the equation before cycling through equations. 

My plan is use `?equationButtons=left` in interviews. If I notice flow issues in the first 2 interviews, I'll switch to `?equationButtons=right` in the subsequent interviews.

I'm in the process of scheduling interviews in the Oct 2-8 window. So far, I have 3 volunteers, but I'll probably have a few more volunteers by the end of the day.

**Comment by pixelzoom** [comment]
> My plan is use ?equationButtons=left in interviews.

Would you like me to make that the default?  The default is currently `right`.

**Comment by arouinfar** [comment]
@pixelzoom I am perfectly fine with appending `?equationButtons=left` to the URL, but if you are planning on publishing a new dev version in the next day or two, please change the default to `left`.

**Comment by pixelzoom** [comment]
Default changed to `?equationButtons=left` in [1.0.0-dev.29](https://phet-dev.colorado.edu/html/vector-addition/1.0.0-dev.29/phet/vector-addition_en_phet.html).

**Comment by arouinfar** [comment]
Thanks @pixelzoom!

**Comment by pixelzoom** [comment]
In the above commit, I prevented the contents of the Equation accordion box from shifting around when switching between Cartesian and Polar scenes.  This change is present in [1.0.0-dev.30](https://phet-dev.colorado.edu/html/vector-addition/1.0.0-dev.30/phet/vector-addition_en_phet.html).

**Comment by pixelzoom** [comment]
1.0.0-dev.30 has some problems related to memory management changes for #87.  Please use [1.0.0-dev.31](https://phet-dev.colorado.edu/html/vector-addition/1.0.0-dev.31/phet/vector-addition_en_phet.html) for interviews.

**Comment by arouinfar** [comment]
I've completed 4 interviews with the equation buttons on the left and I have not seen any flow issues, so let's keep the buttons on the left. The default is currently `left` but I imagine we may want to delete the query parameter, so back to @pixelzoom.

**Comment by pixelzoom** [comment]
Thanks @arouinfar. `equationButtons` query parameter has been removed, closing.
