### ISSUE TITLE
multitouch testing

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/vector-addition#197]
... wherein I will attempt to do a thorough multitouch shakedown, and identify any issues.

**Comment by pixelzoom** [comment]
Some thibgs to check:

Actions that should cancel any interactions that are in progress:
- [ ] press Reset All button
- [ ] press Eraser button
- [ ] select Cartesian or polar radio button
- [ ] select horizontal or vertical radio button (Explore 1D)

All screens:
- [ ] directly manipulate multiple vectors simultaneously
- [ ] vector with simultaneous translation and scale/rotation interactions
- [ ] drag vector while changing Values and Angle checkboxes
- [ ] drag vector while changing Component radio buttons
- [ ] unchecking "Sum" cancels any interactions with the sum vector that are in progress

Equation screen:
- [ ] change equation radio buttons while holding down coefficient pickers
- [ ] change equation radio buttons while holding down base vector pickers
- [ ] hold down coefficient and base vector pickers
- [ ] unchecking "c" or "f" cancels any interactions with those vectors that are in progress
- [ ] collapsing the Equation accordion box cancels interactions with pickers
- [ ] collapsing the Base Vectors accordion box cancels interactions with pickers

**Comment by pixelzoom** [comment]
Failing interactions:

> - [ ] directly manipulate multiple vectors simultaneously

Selection behaves oddly. Instead of staying with the vector that was most-recently selected, it jumps around to the vector that was most-recently transformed.

> - [ ] unchecking "Sum" cancels any interactions with the sum vector that are in progress

Interaction is not cancelled; you can continue manipulating a sum vector while it's invisible.

**Comment by pixelzoom** [comment]
I've completed the checklist in https://github.com/phetsims/vector-addition/issues/197#issuecomment-535779200, and created issues for failing cases.

@arouinfar @ariel-phet can you think of any other scenarios that I missed?

**Comment by arouinfar** [comment]
@pixelzoom the list in https://github.com/phetsims/vector-addition/issues/197#issuecomment-535779200 looks very comprehensive to me. I cannot think of anything else to add.

**Comment by pixelzoom** [comment]
All associated issues (#200, #201, #202) have been addressed.

**Comment by ariel-phet** [comment]
@pixelzoom it might be captured in the above list but the only thing I could think of was having the sum behave correctly when multiple vectors are manipulated simultaneously, but that might be implicit in your handling. Otherwise looks comprehensive to me.

**Comment by pixelzoom** [comment]
Thanks @ariel-phet. Yes, the sum does behave correctly when multiple vectors are manipulated simultaneously. 

Closing.
