### ISSUE TITLE
overlapping labels blend into each other

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/vector-addition#198]
When vector labels overlap, they start to blend together. For example, at lower-right the overlapping labels could be read as "55.0":

<img width="1020" alt="screenshot_1537" src="https://user-images.githubusercontent.com/3046552/65729656-52ba0500-e07c-11e9-9970-34b9dbf1bca1.png">

How about putting a subtle stroke around the labels, just a tad darker to make it clear where the borders of the labels are?  For example:

<img width="1015" alt="screenshot_1536" src="https://user-images.githubusercontent.com/3046552/65729706-72e9c400-e07c-11e9-9e08-f5c0bbe93fbb.png">

In the above, the colors in `VectorAdditionColors` are:

```js
    ACTIVE_VECTOR_LABEL_BACKGROUND_FILL: 'rgb( 240, 240, 100 )',
    ACTIVE_VECTOR_LABEL_BACKGROUND_STROKE: 'rgb( 230, 230, 90 )',
    INACTIVE_VECTOR_LABEL_BACKGROUND_FILL: 'rgb( 235, 235, 235 )',
    INACTIVE_VECTOR_LABEL_BACKGROUND_STROKE: 'rgb( 215, 215, 215 )',
```

**Comment by pixelzoom** [comment]
Pushed to master, @arouinfar please review.  If you want to experiment, change the above strokes in your working copy in `VectorAdditionColors`.   A value of `null` means "no stroke".

**Comment by arouinfar** [comment]
@pixelzoom this is a really nice design change. I think the stroke in master is perfect. Let's go with that.

**Comment by pixelzoom** [comment]
Glad you like it!
