### ISSUE TITLE
Vectors do not reappear  in the vector panel upon pressing ResetAll Button

### ISSUE THREAD

**Issue by veillette** [phetsims/vector-addition#20]
Pressing the resestAll button should reset the simulation to its initial state. Currently, the visibility of the icons in the vector panel cannot be easily reset.

**Comment by brandonLi8** [comment]
7a4add0d676d9c03f5c29042377fa09efdae0348

**Comment by brandonLi8** [comment]
b841af99434a0e16a6cb3716ac50b1173d887eff

**Comment by veillette** [comment]
work is done. Closing
