### ISSUE TITLE
most-recently selected vector does not remain selected

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/vector-addition#200]
Related to #197, multitouch testing.

While manipulating 2 or more vectors, the vector that was most-recently selected does not remain selected.  Instead, the selection jumps around to the vector that was most-recently transformed.   This causes the yellow highlight to move around, and the selection shown in the "Vector Values" toggle box to change.

**Comment by pixelzoom** [comment]
Steps to reproduce, on an iPad or other touch devices:

1. start sim, go to _Explore 2D_ screen
2. drag vector 'a' to graph
3. drag vector 'b' to graph
4. touch down on vector 'a' (do not release), 'a' will be highlight and displayed in "Vector Values"
5. touch down on vector 'b' (do not release), 'a' will be highlight and displayed in "Vector Values"
6. move vector 'a' while holding 'b' still. 'a' will appear highlighted and displayed in "Vector Values"
7.  move vector 'a' while holding 'b' still. 'a' will appear highlighted and displayed in "Vector Values"
8. repeat steps 6 & 7 and note how selection moves back and forth between 'a' and 'b'
9. move 'a' and 'b' at the same time, and note how (less obviously) selection moves back and forth between 'a' and 'b'

**Comment by pixelzoom** [comment]
The problem is in Vector.js:

```js
    moveTipToPosition( tipPosition ) {
      this.graph.activeVectorProperty.value = this;
      ...
    }

    moveTailToPosition( tailPosition ) {
      this.graph.activeVectorProperty.value = this;
      ...
    }
```

So every time a vector is transformed, it becomes the active (selected) vector.

**Comment by pixelzoom** [comment]
Fixed in the above commit by setting `activeVectorProperty` in the `start` methods VectorNode's two DragListeners.

So for multitouch, you can interact with N vectors at the same time.  But whichever one you grab last is the one that is "selected"; that is, highlighted and displayed in "Vector Values".  Does that sound acceptable to you @arouinfar?

**Comment by arouinfar** [comment]
> So for multitouch, you can interact with N vectors at the same time. But whichever one you grab last is the one that is "selected"; that is, highlighted and displayed in "Vector Values". Does that sound acceptable to you @arouinfar?

That sounds perfectly reasonable to me @pixelzoom.
