### ISSUE TITLE
Explore 1D screen icon polish

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/vector-addition#204]
@arouinfar how would you feel about making the bottom vector in the _Explore 1D_ screen icon a little longer?  My eye tells me there's too much whitespace.

<img width="967" alt="screenshot_1552" src="https://user-images.githubusercontent.com/3046552/65900308-f3f1d580-e372-11e9-8588-a00e96089d54.png">

**Comment by arouinfar** [comment]
We could make it a bit longer @pixelzoom, so long as its magnitude is ≤ 50% of the top vector.

**Comment by pixelzoom** [comment]
Pushed to master, screenshot below.  Length of bottom vector is 50% of top vector. @arouinfar please review. 

<img width="1022" alt="screenshot_1551" src="https://user-images.githubusercontent.com/3046552/65900260-d15fbc80-e372-11e9-9536-fe8d3934cf1c.png">

**Comment by arouinfar** [comment]
👍
