### ISSUE TITLE
review pointer areas

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/vector-addition#205]
From the master checklist #1:

> - [ ]  Carefully review `?showPointerAreas`

**Comment by pixelzoom** [comment]
After the fix and tweaks for vector pointer areas in #206, pointer areas are looking good to me.   Over to @arouinfar for sign-off.

**Comment by pixelzoom** [comment]
@ariel-phet would like this assigned to him too.

**Comment by arouinfar** [comment]
The pointerAreas are all looking good to me @pixelzoom. I didn't have any issues with touch on the iPad. On mobile, checkboxes occasionally took an extra tap to toggle, but I think that's acceptable.

**Comment by ariel-phet** [comment]
@arouinfar @pixelzoom all looking quite good, but I would suggest dilating the eraser button slightly, a bit hard for me to click on mobile. Maybe split the difference between the white space between the graph and the button for the dilation.

No need to reassign to me @pixelzoom, if you make this change, feel free to go ahead and close.

**Comment by pixelzoom** [comment]
Slack:

Chris Malley 1:15 PM
Re https://github.com/phetsims/vector-addition/issues/205#issuecomment-536706598…  Are you asking for  touchArea dilation of the eraser button only, or also mouseArea?

Ariel Paul 1:15 PM
apologies, just touchArea

**Comment by pixelzoom** [comment]
In the above commit, the eraser button `touchArea` is dilated as requested, identical in all screens that have an eraser button.  Example screenshot below. 

Closing, reopen if anything appears to be amiss.

<img width="1000" alt="screenshot_1554" src="https://user-images.githubusercontent.com/3046552/65908983-c57cf600-e384-11e9-8814-8bc1e37803cb.png">
