### ISSUE TITLE
improve vector scale/rotate interaction

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/vector-addition#206]
Related to #205, review pointer areas...

In VectorNode, an invisible scenery.Circle is added to vectors, and it's this Circle that is grabbed when the vector is scaled/rotated.    

I added code to stroke this Circle in 'red' with `?dev`, and it looks like this:

<img width="153" alt="screenshot_1543" src="https://user-images.githubusercontent.com/3046552/65810776-3a291800-e16c-11e9-9349-eca4e707e850.png">

So this seems to be one reason why it's difficult to grab the tip.  The Circle is the wrong size (its diameter should be at least as big as the vector's head), and it's not placed properly.

**Comment by pixelzoom** [comment]
Here's a step in the right direction, where the Circle's diameter matches the head height:

<img width="153" alt="screenshot_1543" src="https://user-images.githubusercontent.com/3046552/65810811-a60b8080-e16c-11e9-99af-48e2757dd257.png">

But I'm wondering...  Why are we using a Circle? Why not use another invisible arrow, that consists of a head and stubby tail?   @arouinfar is there some design reason for using a Circle? 

Another wart is that VectorNode creates this Circle regardless of whether the vector can be scaled/rotated.

**Comment by pixelzoom** [comment]
I replaced the circle with a triangle that matches the vector's head.  And it is created only if the vector can be scaled/rotated. 

If you run with `?dev`, the triangle will be stroked with 'red', so you can verify that it is aligned with the vector's head.  For example:

<img width="358" alt="screenshot_1548" src="https://user-images.githubusercontent.com/3046552/65811251-ac9cf680-e172-11e9-8018-93404840e28a.png">

This triangle has its own separate pointer area dilations, which are currently defined in `VectorAdditionConstants` like this:

```js
// dilation of vector head pointer areas, for vectors that can be scales/rotated
VECTOR_HEAD_TOUCH_AREA_DILATION: 8,
VECTOR_HEAD_MOUSE_AREA_DILATION: 6,
```

So with `?showPointerAreas`, it looks like this, with a bit more dilation for `touchArea`:

<img width="340" alt="screenshot_1549" src="https://user-images.githubusercontent.com/3046552/65811264-fdacea80-e172-11e9-8317-b771a852effd.png">

@arouinfar please review in [1.0.0-dev.26](https://phet-dev.colorado.edu/html/vector-addition/1.0.0-dev.26/phet/vector-addition_en_phet.html), let me know what you think.

**Comment by arouinfar** [comment]
> @arouinfar is there some design reason for using a Circle?

No, there was never a design specification for circles. The triangular pointerAreas look good to me.
