### ISSUE TITLE
pixel polishing

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/vector-addition#208]
@arouinfar @ariel-phet please review [1.0.0-dev.28]( https://phet-dev.colorado.edu/html/vector-addition/1.0.0-dev.28/phet/vector-addition_en_phet.html) and identify any pixel polishing that should be done prior to dev testing.  Please create a GitHub issue for each request, linked to this issue.  Feel free to contact me on Slack if you feel it would be more efficient to tweak in real time.

If there are any requests related to the 'Equation' accordion box, keep in mind that its layout has yet to be finalized. See https://github.com/phetsims/vector-addition/issues/196.

**Comment by ariel-phet** [comment]
I think things are looking quite good. The colors all seem to be working, even in pretty "busy" situations, and the dashes for components are also looking good. No polishes for me.

**Comment by arouinfar** [comment]
Thanks for checking in @pixelzoom. I think the pixels have all been sufficiently polished! I don't have any further requests.
