### ISSUE TITLE
Add cartesian and polar mode icon to IconFactory

### ISSUE THREAD

**Issue by veillette** [phetsims/vector-addition#21]
![image](https://user-images.githubusercontent.com/7633344/59204055-d1db0a00-8b6d-11e9-867c-82422f2479e9.png)

**Comment by brandonLi8** [comment]
@veillette what screens do these icons appear in

**Comment by arouinfar** [comment]
@brandonLi8 @veillette these icons will appear on the Explore 2D, Lab, and Equations screens.

**Comment by veillette** [comment]
@brandonLi8 commited them in https://github.com/phetsims/vector-addition/commit/7c127bcac3e587ad948b1baaa96db508baf30864 but forgot to tag it

**Comment by veillette** [comment]
So far we have
![image](https://user-images.githubusercontent.com/7633344/59354957-260ff680-8cf4-11e9-97dd-c88f010a489c.png)

I'll leave this open as this is work in progress. The text of the icon "1" is missing in some places.

**Comment by brandonLi8** [comment]
This looks mostly correct now.
