### ISSUE TITLE
labels for long vectors are off screen

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/vector-addition#212]
Currently, a vector's label is centered along the length of the vector.  This works (and looks) great in most cases, for example: 

<img width="899" alt="screenshot_1558" src="https://user-images.githubusercontent.com/3046552/65994095-ca5aac00-e44f-11e9-8b69-1004d759acd1.png">

But in the _Equation_ screen, it's possible to create some really long vectors. For example, setting the pickers to maximum values results in something like the screenshot below.  And in cases like this, you can't see the labels on the sum vector or its component vectors. 

@arouinfar do you want to live with this, or change the positioning algorithm for labels? 

<img width="902" alt="screenshot_1557" src="https://user-images.githubusercontent.com/3046552/65993750-10fbd680-e44f-11e9-9f14-533009affce1.png">

**Comment by pixelzoom** [comment]
When a vector is selected, we change its label to yellow.  So when a vector's label is off screen, there's also no feedback when the vector is selected.

**Comment by pixelzoom** [comment]
Here's another example, where you can't tell which vector is 'a' vs 'b'. 

<img width="901" alt="screenshot_1559" src="https://user-images.githubusercontent.com/3046552/65994461-8ddb8000-e450-11e9-9da6-305f51f42111.png">

The user could move 'a' and 'b' to see their labels, as in the screenshot below.  But because of the constraint that a vector's tail must be on the graph. it's impossible to move 'c' enough to see its label. 

<img width="899" alt="screenshot_1560" src="https://user-images.githubusercontent.com/3046552/65994520-be231e80-e450-11e9-819f-fedc1da99fd6.png">

**Comment by pixelzoom** [comment]
I discussed with @arouinfar via Zoom.   

We don't want to enforce the label to always be on the graph, because that will look lousy for shorter vectors that are placed near the edge of the graph. And we don't mind the user having to move the vectors if they want the labels to be on the graph.

We do want to apply the same fix to _all_ vectors, including component vectors.

We decided to center the label on `Math.min( vector.min, MAX_MAGNITUDE )`.   I've currently set `MAX_MAGNITUDE` to be the width of the graph, which is 50, and that seems to work nicely.   If we want to do more tweaking, I'll add a query parameter.

@arouinfar please review in master or [1.0.0-dev.33](https://phet-dev.colorado.edu/html/vector-addition/1.0.0-dev.33/phet/vector-addition_en_phet.html).

**Comment by pixelzoom** [comment]
We might also consider using the diagonal length of the graph for `MAX_MAGNITUDE`.  Using the graph's width will cause the label to not be centered for some vectors that do fit on the graph. For example:

<img width="1014" alt="screenshot_1561" src="https://user-images.githubusercontent.com/3046552/66072644-a9a75a80-e512-11e9-9ece-43de1d42634c.png">

**Comment by arouinfar** [comment]
@pixelzoom the general approach is working quite nicely.
![image](https://user-images.githubusercontent.com/8419308/66083428-85a34380-e529-11e9-8c12-27fefc757d98.png)

> We might also consider using the diagonal length of the graph for `MAX_MAGNITUDE`

Yes, I agree. Can you update `MAX_MAGNITUDE` to match the vector shown in https://github.com/phetsims/vector-addition/issues/212#issuecomment-537628386?

**Comment by pixelzoom** [comment]
Adjusted as requested - this feels better. Also renamed the constant to `MAX_LABEL_VECTOR_MAGITUDE`.

@arouinfar please verify in master or [1.0.0-dev.34](https://phet-dev.colorado.edu/html/vector-addition/1.0.0-dev.34/phet/vector-addition_en_phet.html).

**Comment by arouinfar** [comment]
👍

**Comment by arouinfar** [comment]
Looks great @pixelzoom. This was a really nice polish, thanks for suggesting!
