### ISSUE TITLE
add transparency to vector label backgrounds

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/vector-addition#214]
@kathy-phet reported that she's like to see some transparency in the vector label backgrounds.

**Comment by pixelzoom** [comment]
We played with this in realtime, in there was consensus that it looked good. 

Here are the current values in `VectorAdditionColors`:

```js
    ACTIVE_VECTOR_LABEL_BACKGROUND_FILL: 'rgba( 240, 240, 100, 0.8 )', // yellow
    ACTIVE_VECTOR_LABEL_BACKGROUND_STROKE: 'rgba( 230, 230, 90, 0.8 )', // slightly darker yellow
    INACTIVE_VECTOR_LABEL_BACKGROUND_FILL: 'rgba( 235, 235, 235, 0.5 )', // gray
    INACTIVE_VECTOR_LABEL_BACKGROUND_STROKE: 'rgba( 215, 215, 215, 0.5 )', // slightly darker gray
```

@arouinfar @ariel-phet @kathy-phet please review in master or [1.0.0-dev.36](https://phet-dev.colorado.edu/html/vector-addition/1.0.0-dev.36/phet/vector-addition_en_phet.html).

**Comment by arouinfar** [comment]
@pixelzoom I'm happy with how things look in dev.36. @kathy-phet @ariel-phet would you also like to review?

**Comment by ariel-phet** [comment]
I think all looks quite good. No need to wait for @kathy-phet on this one. Closing
