### ISSUE TITLE
Can't scale vectors outside of graph

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/vector-addition#215]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/QA/issues/434.  Doesn't feel wrong, but does seem to contradict the model document.  The document says:
> scale a vector by dragging its tip (can be dragged outside the graph's grid)

However, while you can move the vector so it extends beyond the grid, you can't drag the tip out itself. If you try to drag the tip while it is outside the graph it will jump inside the graph. I think the current behavior is preferable, but am documenting here due to the seeming contradiction.

**Visuals**
![cantdragout](https://user-images.githubusercontent.com/41024075/66226673-9de5a080-e698-11e9-9cd0-8eb9f18a3fb6.gif)

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Vector Addition‬
URL: https://phet-dev.colorado.edu/html/vector-addition/1.0.0-dev.36/phet/vector-addition_all_phet.html
Version: 1.0.0-dev.36 2019-10-03 17:23:25 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

**Comment by pixelzoom** [comment]
Sorry, model.md is incorrect.  Dragging the vector's head is (intentionally) constrained to the bounds of the graph.  I've updated model.md in the above commit.  Please review, and close if it looks OK.
