### ISSUE TITLE
Minor pointer area overlap

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/vector-addition#216]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/QA/issues/434
Likely already discussed, and minor enough that I don't personally recommend any changes.  Feel free to close after review.  When a vector partially or fully covers the origin point on the graph, that point can be difficult or impossible to move without moving the vector above it.  I think this is preferable to the alternative however.

**Visuals**
![cantgrabpoint](https://user-images.githubusercontent.com/41024075/66228730-6a594500-e69d-11e9-9493-88093a234f4c.png)
![hardtograbpoint](https://user-images.githubusercontent.com/41024075/66228731-6cbb9f00-e69d-11e9-875c-ef369857b807.png)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Vector Addition‬
URL: https://phet-dev.colorado.edu/html/vector-addition/1.0.0-dev.36/phet/vector-addition_all_phet.html
Version: 1.0.0-dev.36 2019-10-03 17:23:25 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by pixelzoom** [comment]
@ariel-phet had some strong opinions on the size of the origin manipulator and its touch area, so I'm assigning him to this issue too.    For reference, our decision about the origin manipulator can be found in https://github.com/phetsims/vector-addition/issues/176.

My recommendation is to do nothing here. If you can't grab the origin manipulator (which is clearly _under_ the vector), then move the vector.

**Comment by arouinfar** [comment]
Thanks @KatieWoe. 

If we were to dilate the touch area of the origin manipulator any further, the bounds would spill over into the neighboring grid squares, which could easily result in accidental grabs. Like @pixelzoom,  I'm inclined to leave things as they are.

**Comment by ariel-phet** [comment]
Agreed, I appreciate pointing out this potential issue, but I don't think it is a concern. Closing
