### ISSUE TITLE
Vector being in graph depends on mouse/finger position

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/vector-addition#217]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/QA/issues/434
When dragging a vector around, it will stick to the graph if you drop it withing bounds and return to the tool box if you drop it out of bounds.  However, which happens depends on the mouse or finger position, not on the vector's position.  So if you drag near the tail, most of the vector can be out of the graph and still stick (this is expected and works well).  However, if you drag closer to the tip, that same vector will not go as far out of the graph before it returns. This is more noticeable with long vectors.
**Steps to reproduce**
1. Go to the second or third screen
2. Drag out a vector and put it on the graph
3. Grab the vector close to the tail and drag up.  Note when it stops sticking to the graph
4. Repeat, but this time grab closer to the tip (without changing vector direction)

**Visuals**
![bitoddvectordrop](https://user-images.githubusercontent.com/41024075/66232450-16069300-e6a6-11e9-85c0-a518439c3117.gif)
![egregiousdrop](https://user-images.githubusercontent.com/41024075/66232456-199a1a00-e6a6-11e9-9ec2-883d428445f4.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Vector Addition‬
URL: https://phet-dev.colorado.edu/html/vector-addition/1.0.0-dev.36/phet/vector-addition_all_phet.html
Version: 1.0.0-dev.36 2019-10-03 17:23:25 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by pixelzoom** [comment]
@KatieWoe thanks for reporting.

This is behaving as specified - whether a vector is on/off the graph depends on pointer position, not vector position.   @arouinfar let me know if you want to change the behavior, or close as "won't fix".

**Comment by arouinfar** [comment]
This is indeed the desired behavior, but thanks for check @KatieWoe. If the cursor leaves the bounds of the grid, the vector pops out.
