### ISSUE TITLE
Vectors are removed from graph calculations as the mouse leaves the graph

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/vector-addition#219]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Edge (or any)
**Problem description**
For https://github.com/phetsims/QA/issues/434. Related to behavior described in https://github.com/phetsims/vector-addition/issues/217.
When the mouse leaves the graph area while dragging a vector, it stops being used for calculating things like sum vectors.  Even if the mouse is moved back into the graph, the vector isn't recognized until it is dropped on the graph.

**Visuals**
![prematuredrop](https://user-images.githubusercontent.com/41024075/66242998-1f045e00-e6c0-11e9-9a66-9cb7bb7286d7.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Vector Addition‬
URL: https://phet-dev.colorado.edu/html/vector-addition/1.0.0-dev.36/phet/vector-addition_all_phet.html
Version: 1.0.0-dev.36 2019-10-03 17:23:25 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36 Edge/18.18362
Language: en-US
Window: 1536x751
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Microsoft (Microsoft Edge)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by pixelzoom** [comment]
@KatieWoe what is the behavior that you expected? 

This is behaving as specified, and is related to #217.   When a vector leaves the graph, a drop shadow appears to indicate that it is no longer on the graph, and no longer contributes to the sum.  And until a vector is dropped on the graph, it will not contribute to the sum. @arouinfar let me know if you want to change the behavior, or close as 'won't fix'.

**Comment by arouinfar** [comment]
This is the desired behavior @KatieWoe.  We allow the tips of vectors to be translated off-grid to allow very long vectors to be arranged tip-to-tail. However, if the cursor also goes off-grid, we must assume the user wants to return the vector to the toolbox. The drop-shadow indicates the vector is not currently part of the model, and similar strategies have been used in other sims.
