### ISSUE TITLE
Vector.js should contains the logic for vectorOrientation 

### ISSUE THREAD

**Issue by veillette** [phetsims/vector-addition#22]
The projection modes of the vectors along the x and the y (Explore1D) and noProjection should be handled in the model vector. 

The vectorAttributesProperty should be mulltilink to the vectorOrientationProperty.

**Comment by veillette** [comment]
I set the vectorOrientation within VectorNode rather than Vector. In this way, it was possible to simply pass a purely horizontal or vertical projection to the model. I like the simplicity of the approach.

Currently, the vertical mode does not work very well since (in master) the vectors are set horizontally rather than vertically.

**Comment by brandonLi8** [comment]
resolved with 6cad3d256726033818b6229126ccb11aef0e9ec2

**Comment by veillette** [comment]
This is  no longer relevant after the refactoring.closing
