### ISSUE TITLE
Vector Values focuses on vectors not in use

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/vector-addition#220]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Chrome/Edge or any
**Problem description**
For https://github.com/phetsims/QA/issues/434
The Vector Values description will show descriptions of vectors in or returning to the toolbox under certain circumstances. If the vector is picked up and returned without ever being put on the graph, this will happen. If it is removed from the graph this bug does not occur.  While the bugged vector is returning to the box you can see the vector values description rapidly change as the vector shrinks to fit the tool box.
**Steps to reproduce**
1. Go to any of the first three screens
2. Pick up a vector from the tool box
3. Immediately drop it and watch the description
4. Repeat, but move the vector to a location other than the graph

**Visuals**
![focusingonunusedvectors](https://user-images.githubusercontent.com/41024075/66244483-dea7de80-e6c5-11e9-8e13-49242cc3dede.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Vector Addition‬
URL: https://phet-dev.colorado.edu/html/vector-addition/1.0.0-dev.36/phet/vector-addition_all_phet.html
Version: 1.0.0-dev.36 2019-10-03 17:23:25 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by pixelzoom** [comment]
This looks like a legitimate bug.   A vector should not become selected (and therefore appear in the 'Vector Values' accordion box) until it is dropped on the graph.

**Comment by pixelzoom** [comment]
This problem was introduced while fixing #200, and it's resolved in the above commit.

@KatieWoe please verify in master or [1.0.0-dev.37](https://phet-dev.colorado.edu/html/vector-addition/1.0.0-dev.37/phet/vector-addition_en_phet.html).  If all looks well, you can close this issue.

**Comment by KatieWoe** [comment]
Looks good on master
