### ISSUE TITLE
screenshots

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/vector-addition#222]
This is a new sim, so it needs a main and alternate screenshots.

**Comment by arouinfar** [comment]
I'll take screenshots when we get to rc.1.

**Comment by arouinfar** [comment]
Here's a first pass at screenshots. I think the main screenshot is a bit too boring, but it is pretty close to the Flash version. Leaving self-assigned for a bit longer in case inspiration strikes.

Main:
![Vector Addition screenshot (4)](https://user-images.githubusercontent.com/8419308/67066542-47647180-f130-11e9-9183-307689117539.png)

Alternates:
![Vector Addition screenshot (5)](https://user-images.githubusercontent.com/8419308/67066543-47647180-f130-11e9-8ab1-9da189312312.png)
![Vector Addition screenshot (7)](https://user-images.githubusercontent.com/8419308/67066545-47647180-f130-11e9-8c29-d1f0097a673e.png)
![Vector Addition screenshot (9)](https://user-images.githubusercontent.com/8419308/67069471-6c5de200-f13a-11e9-81e2-e281e2dc507a.png)

**Comment by arouinfar** [comment]
Polished these up a bit more, ready for you @KatieWoe.

![Vector Addition screenshot (1)](https://user-images.githubusercontent.com/8419308/67431907-76506c80-f5a2-11e9-83f7-931136c74995.png)
![Vector Addition screenshot (2)](https://user-images.githubusercontent.com/8419308/67431908-76506c80-f5a2-11e9-8e98-28b2bad3dad3.png)
![Vector Addition screenshot (7)](https://user-images.githubusercontent.com/8419308/67066545-47647180-f130-11e9-8c29-d1f0097a673e.png)
![Vector Addition screenshot (3)](https://user-images.githubusercontent.com/8419308/67431910-76506c80-f5a2-11e9-9726-7f0afc7dcff4.png)

**Comment by KatieWoe** [comment]
Screenshots for this sim:
![vector-addition-screenshot](https://user-images.githubusercontent.com/41024075/67439545-bff58300-f5b3-11e9-9fae-e0cbf5bcfb4c.png)
![vector-addition-screenshot-alt1](https://user-images.githubusercontent.com/41024075/67439546-bff58300-f5b3-11e9-9d15-5c3056c0f92e.png)
![vector-addition-screenshot-alt2](https://user-images.githubusercontent.com/41024075/67439547-bff58300-f5b3-11e9-86e8-6dcbc4e0b3fc.png)
![vector-addition-screenshot-alt3](https://user-images.githubusercontent.com/41024075/67439548-c08e1980-f5b3-11e9-9157-92f2c35e405a.png)

**Comment by pixelzoom** [comment]
@KatieWoe are you checking these into GitHub, or would you like me to?

**Comment by KatieWoe** [comment]
I will unless you want to.  I was just about to start.  This comment is just so it can easily be seen in the issue in case I missed something by accident.

**Comment by pixelzoom** [comment]
Go for it!

**Comment by KatieWoe** [comment]
Done in above commits
