### ISSUE TITLE
change behavior of "on axis" components representation

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/vector-addition#225]
#224 is a prerequisite to this issue.

"On axis" currently projects all components vectors onto the x and y axes.  In the past this was thought of as an axis projection, but it was discovered (late in the game) that this should be thought of as a projection "near" the axis, where each component vector is easy to see (similar to the Flash sim version).

* Each component vector will be offset from its related axis
* Offsets will be incremented based on position in the VectorSet's `this.vectors` array; when this array changes, recompute, requires observing `this.vectors.lengthProperty`. (Alternative if that doesn't look good: Compute offsets based on tail positions, requires observing all tail positions.)
* "parent" vectors will be below the x axis, to the left of y axis
* sum components will be above the x axis, to the right of y axis
* offset will be such that tails do not overlap, OK for heads to overlap
* vectors from the 2 vector sets in Lab screen should not overlap, so each vector set will have a different starting offset (including sum)
* component vectors still move when origin moves
* leader lines still stop at axes (Alternative if this doesn't look good: make leader lines go to vector.)
* OK if things start to look chaotic with large numbers of vectors, values visible, etc.

In addition to the above:
- [x] rename ComponentVectorStyles.ON_AXIS to something else

**Comment by pixelzoom** [comment]
Notes to self...

Location of the components for PROJECTION mode is set in `ComponentVector` `updateComponent`.

For x components:

```js
        else if ( componentStyle === ComponentVectorStyles.PROJECTION ) {

          // From parent tailX to parent tipX. However its y value is 0 since it is on the x-axis
          this.setTailXY( parentTail.x, 0 );
          this.setTipXY( parentTip.x, 0 );
        }
```

For y components:

```js
        else if ( componentStyle === ComponentVectorStyles.PROJECTION ) {

          // Same tailY, however its x value is 0 since it is on the y-axis
          this.setTailXY( 0, parentTail.y );
          this.setTipXY( 0, parentTip.y );
        }
```

The `0` values will be replaced with an offset, provided via `options` and via a `setProjectionOffset` method.

**Comment by pixelzoom** [comment]
@arouinfar @ariel-phet @kathy-phet please review with high priority.

This change took ~5 hours, and can be reviewed in master and [1.0.0-dev.40](https://phet-dev.colorado.edu/html/vector-addition/1.0.0-dev.40/phet/vector-addition_en_phet.html). I'm certain that it will need polishing. 

Notes:

* All offsets and spacing are specified in model coordinates, not view (pixel) coordinates. Offset and spacing are relative to the vector's location, not the boundaries of its shape.
* For sum vectors in all screens, initial offset from each axis is 0.5, and spacing between sum component vectors is 0.5.  
* For non-sum vectors in all screens, initial offset from each axis is -0.5.
* For the _Explore 2D_ and _Equation_ screens, spacing between component vectors is 0.7, so that they will not overlap. See _Explore 2D_ screenshot below.
* For the _Lab_ screen, spacing for component vectors of the same color is 0.4.  Spacing between vectors of all colors is therefore half of that (0.2) so that vectors of different colors are interleaved. See _Lab_ screenshot below.
* Interleaving of vector sets in the _Lab_ screen quickly results in an unusable mess. See (This interleaving gets to be quite the mess with large numbers of vectors; see https://github.com/phetsims/vector-addition/issues/224#issuecomment-541181204 for a related question and example.
* Component vector offsets for all vectors on the graph are adjusted whenever a vector is removed from the graph. For example, drop 'a' and 'b' onto the graph. Drop 'a' back into the toolbox, and the component vector offsets for 'b' will be adjusted.
* Since they are relative to the axes, projected component vectors continue to move when the origin moves. 
* Width of leader lines has been decreased from 1 to 0.5.
* Leader lines extend to the tips and tails of the projected vectors, they do not stop at the axes. This was what was easiest (required no change), and (seeing it in context) I think it's the right thing to do, especially with large numbers of vectors.  If you want something different here, plan on another 2 hours of work.

<img width="842" alt="screenshot_1590" src="https://user-images.githubusercontent.com/3046552/66679066-8d01d580-ec2a-11e9-9f1a-debe8fb6af0e.png">

<img width="842" alt="screenshot_1591" src="https://user-images.githubusercontent.com/3046552/66679141-b91d5680-ec2a-11e9-9817-deccf632144a.png">

**Comment by kathy-phet** [comment]
Overall, I like this approach. It can get messy - but its easier to make a productive explanation than when everything was directly on the axis. It gets messier looking when you move the axis grid point, but I think that is just the way this one will be.

**Comment by ariel-phet** [comment]
To me, for the pedagogically "useful" cases (shown below), I think everything is able to be parsed. Sure things can get messy if you just throw a bunch of vectors out, but this view is really to elucidate the idea of vector addition. In a sandbox such as the 2d Lab, things can get messy if you wish in lots of circumstances, and lots of representations, but I think that is just part of having a sandbox.

Overall, I don't have any tweaks, it is all looking good to me, and I think the leader lines running past the access works quite well.

![Explore 2d](https://user-images.githubusercontent.com/4051174/66856709-078c6700-ef43-11e9-9306-ea6225fbbadc.png)
![2d lab](https://user-images.githubusercontent.com/4051174/66856723-0ce9b180-ef43-11e9-9bca-b332a1fbd586.png)

**Comment by ariel-phet** [comment]
@pixelzoom looking at the above, I suppose if I were to make any tweak it would be the following (see if you agree)

Perhaps put the sum projections a bit closer to the axis, my thinking in the 2 Lab picture would be to move the blue sum as close as possible while having a pixel or so of negative space for the head of the arrow and the axis. And then have the red projection of the sum be spaced such that its head does not overlap. I think it is also fine as is, but that might be a touch cleaner for the sum.

**Comment by pixelzoom** [comment]
I've implemented @ariel-phet's suggestion in the above commit.  I've moved the first sum and the first non-sum components closer to the axes, but with a couple of pixels of space separating them from the axes.  In the _Lab_ screen, the sum components don't overlap, but they do touch. This looked better to me than moving the 2nd sum further away -- let me know if you really want space between the heads of the sum.  

Screenshots below that show the same "pedagogically useful cases" that @ariel-phet set up in https://github.com/phetsims/vector-addition/issues/225#issuecomment-542332794.

<img width="955" alt="screenshot_1593" src="https://user-images.githubusercontent.com/3046552/66858318-4374fb80-ef46-11e9-9fb6-934872c4c0fc.png">

<img width="956" alt="screenshot_1594" src="https://user-images.githubusercontent.com/3046552/66858323-44a62880-ef46-11e9-88fb-5937d6711756.png">

**Comment by ariel-phet** [comment]
@pixelzoom that looks great to me, no need to have space between the sum component heads.

I am fine with closing this issue.

**Comment by pixelzoom** [comment]
Unassigning @kathy-phet, since she responded in https://github.com/phetsims/vector-addition/issues/225#issuecomment-541198018.

**Comment by arouinfar** [comment]
> To me, for the pedagogically "useful" cases (shown below), I think everything is able to be parsed. Sure things can get messy if you just throw a bunch of vectors out, but this view is really to elucidate the idea of vector addition. In a sandbox such as the 2d Lab, things can get messy if you wish in lots of circumstances, and lots of representations, but I think that is just part of having a sandbox.

I completely agree @ariel-phet.

@pixelzoom I think the tweaks in https://github.com/phetsims/vector-addition/issues/225#issuecomment-542342063 are a nice touch and tighten things up a bit. 

Thanks for thinking of this design @ariel-phet, and nice execution @pixelzoom. I think we can go ahead and close this issue.
