### ISSUE TITLE
change initial values for vectors

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/vector-addition#227]
@arouinfar said (paraphrasing) in 10/10/19 design meeting:

> In interviews, the fact that vectors come out of the toolbox with the same angle is problematic. Especially in Cartesian mode, where a + b + c don't exactly add up to sum (7.1 + 7.1 + 7.1 = 21.2).

Change request:

_Explore 2D_ screen:
Cartesian, <x,y>: a=<6,8> b=<8,6>, c=<0,-5>
Polar, <mag,angle>: d=<8,30>, e=<8,60>, f=<5,-90>

_Lab_ screen:
Cartesian: all vectors <8,6>
Polar: no change

**Comment by pixelzoom** [comment]
For _Explore 2D_ screen, initial components are created in `Explore2DVectorCreatorPanel`.

For _Lab_ screen, initial components are created in `LabVectorCreatorPanel`.

**Comment by pixelzoom** [comment]
Initial vector values have been modified as requested.  @arouinfar please review in [1.0.0-dev.39](https://phet-dev.colorado.edu/html/vector-addition/1.0.0-dev.39/phet/vector-addition_en_phet.html).   @ariel-phet and @kathy-phet feel free to have a look too, but with high priority.

**Comment by kathy-phet** [comment]
>Explore 2D screen:
Cartesian, <x,y>: a=<6,8> b=<8,6>, c=<0,-5>
Polar, <mag,angle>: d=<8,30>, e=<8,60>, f=<5,-90>

I like these overall, but I would recommend that c be <0,-10> and f be <10, -90>. 

This is partially driven by playing with the sim on my phone. I found that the small vectors are covered entirely by my finger and it is nice to start with something long enough that that will not be the case. 

Is the pinch to zoom work that @jessegreenberg has been doing behind a query parameter, or not in master yet. I was wondering how it would behave in this sim - just to see, not to publish.

**Comment by jessegreenberg** [comment]
Sorry, it is currently still in a branch.

**Comment by arouinfar** [comment]
Generally looking good @pixelzoom. 

> I like these overall, but I would recommend that c be <0,-10> and f be <10, -90>.

Agree for **c**, but for **f** I would go with <8, -90> since the other polar vectors have a magnitude of 8. I think it's nice for the vector sets to have the same default magnitudes.

@pixelzoom let's update **f** to <8, -90> on Explore 2D.

**Comment by pixelzoom** [comment]
*c* and *f* changed as requested for _Explore 2D_ screen. @arouinfar please verify in master.

**Comment by arouinfar** [comment]
Thanks @pixelzoom. Looks good in master.
