### ISSUE TITLE
change vector colors

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/vector-addition#228]
In 10/10/19 design meeting, @kathy-phet reported that she can't tell the difference between sum vector colors.  She showed some alternative colors that she had in mind. @arouinfar and @kathy-phet will work together to revise colors.

You can experiment with colors in [VectorAdditionColors.js](https://github.com/phetsims/vector-addition/blob/master/js/common/VectorAdditionColors.js).  See also [VectorColorPalette.js](https://github.com/phetsims/vector-addition/blob/master/js/common/model/VectorColorPalette.js) for documentation of fields that are available in color palettes.

**Comment by pixelzoom** [comment]
@kathy-phet mentioned adding a stroke to sum vectors.  That's supported, but may not be obvious from looking at VectorAdditionColors.js.   

To add a stroke color, you'll need to add a `sumStroke` field to each `VectorColorPalette` that is created in VectorAdditionColors.js.  For example, this will put a black stroke around sum vectors for the "blue" palette (and note the comma that was added at the end of the line before `sumStroke`):

```js
    BLUE_COLOR_PALETTE: new VectorColorPalette( {
      mainFill: BLUE,
      sumFill: 'rgb( 5, 85, 125 )', // darker blue
      sumStroke: 'black'
    } ),
```

By default, the stroke width is 1.  If you want to change that, you'll need to do that in SumVectorNode.js.  Locate this chunk of code:

```js
      options = merge( {
        arrowOptions: _.extend( {}, VectorAdditionConstants.VECTOR_ARROW_OPTIONS, {
          cursor: 'move',
          fill: vector.vectorColorPalette.mainFill,
          stroke: vector.vectorColorPalette.mainStroke
        } )
      }, options );
```

Then add a `lineWidth` value, like this (note comma added to end of preceding line):

```js
      options = merge( {
        arrowOptions: _.extend( {}, VectorAdditionConstants.VECTOR_ARROW_OPTIONS, {
          cursor: 'move',
          fill: vector.vectorColorPalette.mainFill,
          stroke: vector.vectorColorPalette.mainStroke,
          lineWidth: 0.5
        } )
      }, options );
```

**Comment by arouinfar** [comment]
@kathy-phet and I iterated on the colors quite a bit, but I have a few more options to try out. I'll make a final recommendation sometime tomorrow.

**Comment by arouinfar** [comment]
@pixelzoom here are the final colors. The `mainFill` of the blue and green palettes are the same as before, but all other colors have changed. The `RED_COLOR_PALETTE` is now orange, so it may need renaming. 

```js

    BLUE_COLOR_PALETTE: new VectorColorPalette( {
      mainFill: BLUE,
      sumFill: '#0a46fa' // darker blue
    } ),

    PURPLE_COLOR_PALETTE: new VectorColorPalette( {
      mainFill: '#f149ff',
      sumFill: '#a200de' // darker purple
    } ),

    RED_COLOR_PALETTE: new VectorColorPalette( {
      mainFill: '#ff9023', // red
      sumFill: '#d20000' // darker red
    } ),

    GREEN_COLOR_PALETTE: new VectorColorPalette( {
      mainFill: 'rgb( 5, 200, 0 )', // green
      sumFill: '#058200' // darker green
    } ),

```
Here are the updated colors in context
![image](https://user-images.githubusercontent.com/8419308/67027169-50b8f400-f0c6-11e9-8ee4-c9795af7d272.png)
![image](https://user-images.githubusercontent.com/8419308/67027223-69c1a500-f0c6-11e9-8bc9-ae1cd7d9e549.png)

**Comment by pixelzoom** [comment]
Colors have been changed as requested in master.  PURPLE_COLOR_PALETTE is now PINK_COLOR_PALETTE, and RED_COLOR_PALETTE is now ORANGE_COLOR_PALETTE.  I also change PURPLE to PINK and set it to `#f149ff` so that the _Equation_ screen has the correct color.

The colors overall are a nice improvement.  The only one that stood out to me is the red sum vector in the ORANGE_COLOR_PALETTE, see screenshot below. When I made the changes, I thought I had a bug because the sum wasn't some shade of orange.   But if I'm the only one bothered by this, I'll defer.

Back to @arouinfar for review in master.

<img width="993" alt="screenshot_1599" src="https://user-images.githubusercontent.com/3046552/67029252-308b3400-f0ca-11e9-8466-5cc679d72259.png">

**Comment by arouinfar** [comment]
@pixelzoom thanks for the feedback. I agree that the orange palette isn't as unified as the others. The sum does have a bit too much red, so I've taken it more towards burnt orange `#e63c00`. I briefly tested this combination out on the projector in G126, and the contrast was ok. The contrast isn't as good as the red-orange sum in master, but I do think it looks better on computer screens and is ok on a projector. @kathy-phet can you take a look and let me know what you think?

Master:
![Vector Addition screenshot (3)](https://user-images.githubusercontent.com/8419308/67064566-3dd70b80-f128-11e9-970c-f6062a91fbbd.png)

Changing the sumFill to `#e63c00`
![Vector Addition screenshot (2)](https://user-images.githubusercontent.com/8419308/67064565-3dd70b80-f128-11e9-9137-b5b895b6ff67.png)

**Comment by pixelzoom** [comment]
So that @kathy-phet can compare in context...

[1.0.0-dev.43](https://phet-dev.colorado.edu/html/vector-addition/1.0.0-dev.43/phet/vector-addition_en_phet.html) uses a saturated red `#d20000`.

[1.0.0-dev.44](https://phet-dev.colorado.edu/html/vector-addition/1.0.0-dev.44/phet/vector-addition_en_phet.html) uses the adjusted color `#e63c00`.

Both of those look more "red" than "orange" to me, which weakens the color associations. But I understand the contrast problem.

**Comment by kathy-phet** [comment]
@pixelzoom @arouinfar - My preference is to use the former better contrast version - the red one (dev.43). 

The orange/red contrast was the weakest when Amy and I did the projection tests of all of the pairs on the projector. I would prefer to prioritize keeping the greater contrast. Orange/red is very hard to get a good visible contrast. When the arrows get small, on my phone, the red (dev.43) also provides more visible contrast.

**Comment by pixelzoom** [comment]
I've reverted to `#d20000`.  @arouinfar feel free to close if we're done here.

**Comment by arouinfar** [comment]
Thanks for the feedback @kathy-phet and the revert @pixelzoom. Nothing else to do here.
