### ISSUE TITLE
change order of Components radio buttons

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/vector-addition#229]
Move tip-to-tail button to upper-right of grid.

**Comment by pixelzoom** [comment]
@arouinfar please review in master.

Before:

<img width="172" alt="screenshot_1581" src="https://user-images.githubusercontent.com/3046552/66603501-9119ee80-eb69-11e9-8373-e28e029dafd3.png">

After:

<img width="170" alt="screenshot_1580" src="https://user-images.githubusercontent.com/3046552/66603506-937c4880-eb69-11e9-844a-17747b9204c5.png">

**Comment by arouinfar** [comment]
👍
