### ISSUE TITLE
angle checkbox bug

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/vector-addition#230]
@arouinfar thinks she observed a bug with the angle checkbox in interviews. She will look at her notes and try to reproduce.

**Comment by arouinfar** [comment]
@pixelzoom I've found two angle-related bugs in dev.41. Turning angles off and then back on will fix both bugs.

## Zero-magnitude bug
If a vector's magnitude becomes zero and then later increases to something non-zero, it will lose its angle readout. 

### Method 1
1. Equation screen.
2. Turn on Angles
![image](https://user-images.githubusercontent.com/8419308/66872990-9b225f80-ef64-11e9-8fe4-184da99b55ec.png)

3. Use equation spinner to change coefficient of **a** from 1 to -1. Notice that **a** no longer has an angle readout.
![image](https://user-images.githubusercontent.com/8419308/66873040-b2614d00-ef64-11e9-9f83-3e79736cbc9b.png)

### Method 2
1. Explore 2D
2. Drag out **b** and **c**. 
3. Turn on Sum and Angles
![image](https://user-images.githubusercontent.com/8419308/66873690-4bdd2e80-ef66-11e9-86cc-e8fcc4c7c932.png)
4. Rotate **b** to <0, 10> so it cancels out **c**.
![image](https://user-images.githubusercontent.com/8419308/66873743-7333fb80-ef66-11e9-8a2e-d192773b7ea9.png)
5. Drop **a** into the play area. Notice that the sum no longer has an angle readout.
![image](https://user-images.githubusercontent.com/8419308/66873793-9b235f00-ef66-11e9-839d-7b74fd91a484.png)

## Turning on Angles while play area is empty

### Method 1
1. Explore 2D
2. Turn on Angles
3. Drag out a vector
4. Turn on the sum. Notice the sum doesn't have an angle readout.
![image](https://user-images.githubusercontent.com/8419308/66873977-0ff69900-ef67-11e9-9c30-e5a2d68dfc47.png)

### Method 2
1. Explore 2D
2. Turn on Angles & Sum
3. Drag out a vector. The sum is missing the angle readout.
![image](https://user-images.githubusercontent.com/8419308/66874030-34eb0c00-ef67-11e9-9cc1-a6cf39e47a9b.png)

**Comment by pixelzoom** [comment]
VectorAngleNode needed some general cleanup, particularly wrt the handling of visibility.  I did that in the above commits, and the problems are resolved.  

@arouinfar please verify in master.

**Comment by arouinfar** [comment]
Looks fixed in master @pixelzoom.
