### ISSUE TITLE
use of Property subclasses in type expressions and type checking

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/vector-addition#233]
Related to code review #231.

> - [ ] Look for cases where the use of type expressions involving Property subclasses are incorrect.  Because of the structure of the `Property` class hierarchy, specifying type-specific Properties (`{BooleanProperty}`, `{NumberProperty}`,...) may be incorrect, because it precludes values of type `{DerivedProperty}` and `{DynamicProperty}`.   Similarly, use of `{DerivedProperty}` and `{DynamicProperty}` precludes values of (e.g.) `{BooleanProperty}`. Especially in common code, using `{Property,<TYPE>}` is typically correct, unless some specific feature of the `Property` subclass is required.  For example, `{Property.<boolean>}` instead of `{BooleanProperty}`.

There are quite a few of these, and also quite a few type-checking assertions.

For example, in `VectorAngleNode`:

```js
    /**
     * @param {Vector} vector - the model for the vector that the angle represents
     * @param {BooleanProperty} anglesVisibleProperty
     * @param {Graph} graph
     */
    constructor( vector, anglesVisibleProperty, graph ) {

      assert && assert( vector instanceof Vector, `invalid vector: ${vector}` );
      assert && assert( anglesVisibleProperty instanceof BooleanProperty, `invalid anglesVisibleProperty: ${anglesVisibleProperty}` );
      assert && assert( graph instanceof Graph, `invalid graph: ${graph}` );
```
<br>

In the case of `anglesVisibleProperty`, there's nothing in the implementatition of `VectorAngleNode ` (other than the type checking) that requires a `{BooleanProperty}`; any `{Property.<boolean>}` will do. 

I take credit for this (anti?) pattern.  I did this throughout gas-properties, mainly for the benefits of type-checking, and that sim was apparently consulted when working on vector-addition.

**Comment by pixelzoom** [comment]
This issue is a special case of this more general checklist item:

> - [ ] Prefer the most basic/restrictive type expression when defining APIs. For example, if a client only needs to know that a parameter is `{Node}`, don’t describe the parameter as `{Rectangle}`.

In this case, `{Property.<boolean>}` is the most basic type. `{BooleanProperty}` adds validation and PhET-iO instrumentation, but that functionality is generally not used in the constructors in question.  

That said, a few notes:

(1) If this were common code, then I'd change these type expressions and type-checking assertions. But since this is not common code, I see no benefit in doing so.

(2) Using sim-specific types does buy us something value: type checking.  Other developers may disagree, but I think the value of type-checking in sim-specific code is a good argument for specifying (e.g.) `{BooleanProperty}` instead of `{Property.<boolean>}`.

(3) When this sim is instrumented for PhET-iO, the arguments to most (all?) of these params will in fact be instances type-specific Properties.  And in general, sim-specific code should be using type-specific Properties according to this code review item:

> - [ ]  Properties should use type-specific subclasses where appropriate (.e.g `BooleanProperty`, `NumberProperty`, `StringProperty`) or provide documentation as to why they are not. 

I see this as another argument for specifying `{BooleanProperty}` instead of `{Property.<boolean>}`.

So I think that we'll discuss this one in implementation post mortem, maybe have something to discuss in dev meeting, but make no changes to the vector-addition code.

**Comment by pixelzoom** [comment]
@brandonLi8 and I discussed this at 10/21/19 postmortem. I'm going create an issue for dev meeting discussion to see if we can get consensus on this.  

The two most compelling arguments for `{BooleanProperty}` are:
* type validation
* PhET-iO instrumentation

I advised @brandonLi8 to keep doing what he's been doing in the meantime.

**Comment by pixelzoom** [comment]
@veillette and I discuss this at 10/22/19 postmortem.  Agreed that a dev meeting issue would be good, especially for clarification in new sims like collision-lab.

**Comment by pixelzoom** [comment]
Leaving assigned to me to create a general issue in axon repo.

**Comment by pixelzoom** [comment]
General issue created: https://github.com/phetsims/axon/issues/272

Closing.

**Comment by pixelzoom** [comment]
Reopening to make @brandonLi8 and @veillette aware of changes.  See the consensus summarized in https://github.com/phetsims/axon/issues/272#issuecomment-546053856, and apply this going forward.  Let me know if you have questions.  Unassign yourself after you've read this; last person please close.

**Comment by veillette** [comment]
We will track our changes to the JSdoc and type checking for Collision-lab in https://github.com/phetsims/collision-lab/issues/41.  Closing.
