### ISSUE TITLE
sum component vectors are not visible in some cases

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/vector-addition#237]
Discovered while working on #225.

This bug that has been around for awhile. It slipped through dev testing in [1.0.0-dev.36](https://phet-dev.colorado.edu/html/vector-addition/1.0.0-dev.36/phet/vector-addition_en_phet.html), and it's still present in master.

1. Start sim, go to _Explore 2D_ screen.
2. Check the "Sum" checkbox.
3. Choose any of the Components radio buttons except "invisible"
4. Drag 'a' from toolbox to graph
5. Components will be shown for 'a', but not for the sum.  See screenshot below.

Moving 's', changing the Components setting, or toggling the "Sum" checkbox will show the sum component vectors. 

<img width="972" alt="screenshot_1595" src="https://user-images.githubusercontent.com/3046552/66858798-48867a80-ef47-11e9-9c9e-10a7b0843364.png">

**Comment by pixelzoom** [comment]
Fixed in master and [1.0.0-dev.41](https://phet-dev.colorado.edu/html/vector-addition/1.0.0-dev.41/phet/vector-addition_en_phet.html). Closing.

**Comment by arouinfar** [comment]
I ran into this while reviewing interview footage for #230. I was unable to reproduce in dev.41. Thanks @pixelzoom!
