### ISSUE TITLE
Click anywhere in the graph to clear the selected vector

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/vector-addition#238]
Change request from @arouinfar and @kathy-phet: Click anywhere in the graph to clear the selected vector.

**Comment by pixelzoom** [comment]
Done. @arouinfar please review in master.

**Comment by arouinfar** [comment]
Thanks @pixelzoom. This is working nicely in master.

**Comment by pixelzoom** [comment]
Reopening. @arouinfar found a problem in _Lab_ screen.  

To reproduce:

1. Go to Lab screen.
2. Check both Sum checkboxes
3. Drag one 'blue' and one 'orange' vector to the graph.
4. Click on the graph to clear the selection.  Note that both sum vectors become labeled with 's', see screenshot below.

<img width="991" alt="screenshot_1601" src="https://user-images.githubusercontent.com/3046552/67030465-b3ad8980-f0cc-11e9-8c54-14bedc610c45.png">

**Comment by pixelzoom** [comment]
Another similar problem, steps to reproduce:

1. Got to Lab screen.
2. Check blue 'Sum' checkbox.
3. Drag a 'blue' vector to the graph.
4. Click anywhere on the graph to deselect.  Note that that the blue sum 's' continues to be labeled, see screenshot below.  A sum vector should be labeled only if it, or one of its associated vectors, is selected.

<img width="991" alt="screenshot_1602" src="https://user-images.githubusercontent.com/3046552/67033454-08540300-f0d3-11e9-9aa7-61cd53d5644e.png">

**Comment by pixelzoom** [comment]
The change for this issue has caused a new problem, discovered by @arouinfar. See https://github.com/phetsims/vector-addition/issues/241.
