### ISSUE TITLE
Change screen background color

### ISSUE THREAD

**Issue by arouinfar** [phetsims/vector-addition#239]
In working on #228, @kathy-phet and I experimented with changing the background color. We started with blue vector color and dialed the saturation down to 10%. The result is `#e5f7fe`. Here it is in context. @ariel-phet has also given it a 👍 
![Vector Addition screenshot](https://user-images.githubusercontent.com/8419308/67027949-bbb6fa80-f0c7-11e9-9af1-c68903663822.png)

@pixelzoom can you make this change?

**Comment by pixelzoom** [comment]
Done. @arouinfar please review in master.

**Comment by arouinfar** [comment]
👍
