### ISSUE TITLE
sum vector is labeled when it should not be in Lab screen

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/vector-addition#241]
This was caused by the change in https://github.com/phetsims/vector-addition/issues/238 (Click anywhere in the graph to clear the selected vector), and was discovered by @arouinfar.

To reproduce:

1. Go to Lab screen.
2. Check both Sum checkboxes
3. Drag one 'blue' and one 'orange' vector to the graph.
4. Click on the graph to clear the selection.  Note that both sum vectors become labeled with 's', see screenshot below.

<img width="991" alt="screenshot_1601" src="https://user-images.githubusercontent.com/3046552/67030465-b3ad8980-f0cc-11e9-8c54-14bedc610c45.png">

Another similar problem, steps to reproduce:

1. Got to Lab screen.
2. Check blue 'Sum' checkbox.
3. Drag a 'blue' vector to the graph.
4. Click anywhere on the graph to deselect.  Note that that the blue sum 's' continues to be labeled, see screenshot below.  A sum vector should be labeled only if it, or one of its associated vectors, is selected.

<img width="991" alt="screenshot_1602" src="https://user-images.githubusercontent.com/3046552/67033454-08540300-f0d3-11e9-9aa7-61cd53d5644e.png">

**Comment by pixelzoom** [comment]
The code of interest is in `SumVector`:

```js
      // @private {function} isSymbolDisplayed - function to check if the sum vector should display its symbol.
      // The sum vector only displays its symbol when a vector in its vector set is active, or the sum is active.
      this.isSymbolDisplayed = () => {
        return vectorSet.vectors.some( vector => vector === graph.activeVectorProperty.value )
               || graph.activeVectorProperty.value === this
               || graph.activeVectorProperty.value === null;
```

**Comment by pixelzoom** [comment]
Fixed in the above commit, master and [1.0.0-dev.43](https://phet-dev.colorado.edu/html/vector-addition/1.0.0-dev.43/phet/vector-addition_en_phet.html). I'm not particularly pleased with the solution - it feels like a hack - but I was painted into a corner.  This bit of code has caused me repeated problems, and there's no good/easy way to fix it.  I've documented it, and its working, so... onward.

@arouinfar please verify.

**Comment by arouinfar** [comment]
@pixelzoom the behavior is looking good in dev.43. Thanks for making this change and patching things up.

**Comment by pixelzoom** [comment]
Sorry to do this to you @arouinfar. But I dreamed up (literally:) a better way to address this that should mitigate future maintenance problems.  Please verify in master or [1.0.0-dev.45](https://phet-dev.colorado.edu/html/vector-addition/1.0.0-dev.45/phet/vector-addition_en_phet.html).

**Comment by arouinfar** [comment]
Sounds like it was a productive night of dreaming, dev.45 looks good to me.
