### ISSUE TITLE
change colors for Explore 2D screen icon?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/vector-addition#242]
The screen icons are (yawn) kind of boring, lots of blue vectors:

<img width="988" alt="screenshot_1604" src="https://user-images.githubusercontent.com/3046552/67058175-eb3e2500-f110-11e9-90df-bce0f804b290.png">

<img width="992" alt="screenshot_1608" src="https://user-images.githubusercontent.com/3046552/67058240-37896500-f111-11e9-9ab0-eb11e6f2a028.png">

How would you feel about using the pink color palette for the _Explore 2D_ screen icon? (If you hate it, I can live without it :)

<img width="994" alt="screenshot_1605" src="https://user-images.githubusercontent.com/3046552/67058196-014be580-f111-11e9-99eb-87a0745074c0.png">

<img width="993" alt="screenshot_1606" src="https://user-images.githubusercontent.com/3046552/67058221-1d4f8700-f111-11e9-919a-40b546a20052.png">

**Comment by arouinfar** [comment]
> How would you feel about using the pink color palette for the Explore 2D screen icon? 

Love it! I think it adds a nice pop of color, so let's make the change. Back to you @pixelzoom.

**Comment by pixelzoom** [comment]
Glad you like it.  Changed in master, closing.
