### ISSUE TITLE
problems with touch snag

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/vector-addition#243]
I was doing some brief testing on my phone and I find swipe to pick up working with pulling the vector out of the box, but once it is dropped it looks like I have to hit it directly to pick it up - which is hard on a phone. Is it possible to add swipe to pick up to the vectors?

**Comment by kathy-phet** [comment]
Also adding same question re "axis dot" control? It is hard to pick up.

**Comment by pixelzoom** [comment]
`allowTouchSnag: true` is supposed to be the default for the new scenery `DragListener`.  But I'm having the same difficulty on iPad.   I'll have to investigate.

**Comment by pixelzoom** [comment]
Surprisingly, this is not a problem when dragging vectors out of the toolbox, where `DragListener.createForwardingListener` is used.

**Comment by pixelzoom** [comment]
There are 3 places where DragListener is used in this sim:
* the origin manipulator (uses `new DragListener`)
* vectors on the graph(uses `new DragListener`)
* vectors in the toolboxes (uses `DragListener.createForwardingListener`)

I verified that every one of the DragListeners in this sim is created with `allowTouchSnag: true`.  

On my iPad6 + iPadOS 13.1.3, the vectors in the toolbox behave reliably; they can always be snagged.  The other cases don't snag almost all of the time, but occasionally do snag.  So there's something odd going on here.

@jonathanolson can you please take a look?

**Comment by pixelzoom** [comment]
@kathy-phet what version of iOS is your phone running?

**Comment by pixelzoom** [comment]
Via Slack:

@kathy-phet notes that touch snag works in 1.0.0-dev.42, but does not work in 1.0.0-dev.43.

@kathy-phet also confirms that touch snag works from the vector toolbox, but not from the graph.

**Comment by jonathanolson** [comment]
Looks like it's this PressListener being activated by drags or touches:

```js
      // Clicking in the graph clears the active (selected) vector.
      // No need to remove, exists for the lifetime of the sim.
      this.addInputListener( new PressListener( {
        release: () => { graph.activeVectorProperty.value = null; }
      } ) );
```

If it's necessary to have this as a PressListener, it should probably have `attach: false` and `pressCursor: null`. I'm curious as to why the deselect would be on a release, as a raw `{ down: ... }` listener might be better here?

I tested setting that listener to `attach: false` and touch-snag then seems to work.

**Comment by pixelzoom** [comment]
Thanks @jonathanolson.

In the above commit, I've converted to a raw 'down' listener.  Vector deselection (by clicking on the graph) now occurs on pointer 'down'. This is consistent with vector _selection_, which also occurs on 'down'.   

@arouinfar please review in master or [1.0.0-dev.49](https://phet-dev.colorado.edu/html/vector-addition/1.0.0-dev.49/phet/vector-addition_en_phet.html).

**Comment by arouinfar** [comment]
Looks good in dev.49
