### ISSUE TITLE
Larger touch area on equation spinners

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/vector-addition#245]
In playing I found that it would be good if we could increase the touch area of the equation coefficients more too. It led to a bunch of mis-fires when I used it, and it seemed like it would not conflict with anything to dialate it more so similar in size to the unit vectors spinner which was easy to use.

**Comment by arouinfar** [comment]
I do not experience the same mis-fires on the equation spinners on my phone, but we certainly have plenty of space to expand them a bit more, say 25% (shown in green).
![image](https://user-images.githubusercontent.com/8419308/67116894-9d6ffe00-f19e-11e9-94fa-e6499b16b374.png)

**Comment by kathy-phet** [comment]
Thanks!

**Comment by pixelzoom** [comment]
While we're at it...

**Comment by pixelzoom** [comment]
While we're at it...   Should the base vector pickers be adjusted too?  They have the same pointer areas as the coefficient pickers, see below.

<img width="207" alt="screenshot_1611" src="https://user-images.githubusercontent.com/3046552/67130970-32cfba00-f1c0-11e9-99bb-0cd47be5eb08.png">

**Comment by pixelzoom** [comment]
@arouinfar please review in master.

I went ahead and adjusted touchArea for the base vector pickers too. There is no room to increase their y dilation, they would overlap.  So I only increased their x dilation, using the same value as for the coefficient pickers.   Screenshots below show before and after.

If you want to make further tweaks, here are the current dilation values:

```js
// coefficient pickers, EquationTypeNode.js
touchAreaXDilation: 20,
touchAreaYDilation: 14

// base vector pickers, BaseVectorsAccordionBox.js
touchAreaXDilation: 20,
touchAreaYDilation: 10
```

Before:

<img width="1038" alt="screenshot_1613" src="https://user-images.githubusercontent.com/3046552/67132020-5d237680-f1c4-11e9-8eb0-9f4a4efa5ad4.png">

After:

<img width="1038" alt="screenshot_1612" src="https://user-images.githubusercontent.com/3046552/67132027-614f9400-f1c4-11e9-9080-831f7da594b6.png">

**Comment by arouinfar** [comment]
Thanks @pixelzoom, looks good
