### ISSUE TITLE
Should Vector Addition: Equations be a stand-alone sim? 

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/vector-addition#246]
We discussed this last Thursday, but since all the other issues are resolved, its time to make a decision on this one! Assigning to Amanda to take a look at the math. I suspect that overall the 2 sims will get more traffic then just one sim if we do break it out.

**Comment by pixelzoom** [comment]
FYI, this is the only thing currently blocking us from starting RC testing. So the "high" priority is indeed appropriate :)

**Comment by arouinfar** [comment]
From an interaction perspective, I could see the Equations screen being its own sim.
 
It looks like vector-related standards all fall under [High School: Number and Quantity » Vector & Matrix Quantities](http://www.corestandards.org/Math/Content/HSN/VM/).

I think these standards are addressed by the Equations screen, specifically. From a pedagogical perspective, it may also make sense for the Equations screen to be a standalone sim, but I'm curious to hear what @amanda-phet thinks.
[HSN.VM.B.4.C](http://www.corestandards.org/Math/Content/HSN/VM/#CCSS.Math.Content.HSN.VM.B.4)

> CCSS.MATH.CONTENT.HSN.VM.B.4.C
Understand vector subtraction v - w as v + (-w), where -w is the additive inverse of w, with the same magnitude as w and pointing in the opposite direction. Represent vector subtraction graphically by connecting the tips in the appropriate order, and perform vector subtraction component-wise.

[HSN.VM.B.5](http://www.corestandards.org/Math/Content/HSN/VM/#CCSS.Math.Content.HSN.VM.B.5)
> CCSS.MATH.CONTENT.HSN.VM.B.5
(+) Multiply a vector by a scalar.
>>CCSS.MATH.CONTENT.HSN.VM.B.5.A
Represent scalar multiplication graphically by scaling vectors and possibly reversing their direction; perform scalar multiplication component-wise, e.g., as c(vx, vy) = (cvx, cvy).
>>
>>CCSS.MATH.CONTENT.HSN.VM.B.5.B
Compute the magnitude of a scalar multiple cv using ||cv|| = |c|v. Compute the direction of cv knowing that when |c|v ≠ 0, the direction of cv is either along v (for c > 0) or against v (for c < 0).

**Comment by pixelzoom** [comment]
The 'Equation' screen has been renamed to 'Equations' in #247, so we're cleared to name the new sim 'Vector Addition: Equations'.

**Comment by amanda-phet** [comment]
I can see lots of reasons to make Equations it's own sim! It is very much like a game, and I could see it being easy for someone to use without a guided activity. 

I don't see any issues on the math side of things. A standalone Equations sim would address standards relating to operations with vectors, but before they get to that students would also need the initial exploration. If we wanted a sim just for math, I'd probably combine the Explore 2D screen and the Equations screen into a package, but that might be confusing to users. I think it's simpler to just use one screen in a spinoff sim. You have my blessing to move forward! :)

**Comment by kathy-phet** [comment]
My vote is to go with two sims. Vector Addition (All screens) and   Vector Addition: Equations as a stand alone sim, so we have one with all the screens and then Equations as its own sim. The learning goals that Amy had picked out seemed really tied to this screen and good for students who already have a basic knowledge of vectors.

**Comment by pixelzoom** [comment]
@arouinfar let me know if you want me to proceed.

**Comment by arouinfar** [comment]
@pixelzoom let's proceed with Vector Addition (all screens) and Vector Addition: Equations (Equations screen only).

**Comment by pixelzoom** [comment]
Done. 

@arouinfar please verify in master or [1.0.0-dev.1](https://phet-dev.colorado.edu/html/vector-addition-equations/1.0.0-dev.1/phet/vector-addition-equations_en_phet.html).

**Comment by arouinfar** [comment]
Thanks @pixelzoom. Looks good.
