### ISSUE TITLE
rename "Equation" screen to "Equations"

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/vector-addition#247]
Slack:

Chris Malley 12:26 PM
Question… https://github.com/phetsims/vector-addition/issues/246 asked if we should break out a sim named “Vector Addition: Equations” (plural).  But the screen name is “Equation” (singular). Should the screen be renamed, since it in fact deals with 3 equations?

Amy Rouinfar 12:27 PM
Oh yeah, let’s definitely make it “Equations”

Amy Rouinfar 12:32 PM
Since there are multiple equations on that screen, a plural name makes more sense to me

**Comment by pixelzoom** [comment]
Places where rename is required:

- [ ] `Equation*` class names
- [ ] `js/equation/` directory name
- [ ] code comments
- [ ] translated strings file
- [ ] model.md
- [ ] implementation-notes.md

**Comment by pixelzoom** [comment]
Done.  Note that there were several class names that remained singular because they deal with "an equation", not "the Equations screen".  Those classes are: `EquationTypes`, `EquationTypesRadioButtonGroup`, `EquationTypeNode`, `EquationToggleBox`.

@arouinfar please review in master or [1.0.0-dev.53](https://phet-dev.colorado.edu/html/vector-addition/1.0.0-dev.53/phet/vector-addition_en_phet.html).

**Comment by arouinfar** [comment]
Looks good in dev.53 👍
