### ISSUE TITLE
Equations screen: change sum component color to black

### ISSUE THREAD

**Issue by arouinfar** [phetsims/vector-addition#249]
@kathy-phet pointed out that it's a bit odd that the sum components on the Equations screen are dark gray, but the other vector components have the same color as their parent.
![image](https://user-images.githubusercontent.com/8419308/67414635-b30b6c00-f580-11e9-9119-612d0cda1477.png)

I believe we chose dark gray to improve the contrast for the on-axis projection, but now that we've shifted the components off-axis this is unnecessary.

@pixelzoom let's change the color of the sum components to match the sum color (black).

**Comment by pixelzoom** [comment]
Done in master. @arouinfar please review.

**Comment by arouinfar** [comment]
👍
