### ISSUE TITLE
Toolbox arrow icons should have rectangular or more expanded pointer areas

### ISSUE THREAD

**Issue by samreid** [phetsims/vector-addition#250]
Related to other pointer area discussion in https://github.com/phetsims/vector-addition/issues/205.  

I was unable to drag arrows out of the lab screen toolbox because I wasn't clicking close enough to the icons.  Here is a screenshot of where the mouse cursor was--at this point, I was unable to grab an arrow:

![image](https://user-images.githubusercontent.com/679486/67573928-b294e180-f6f6-11e9-87e3-9cc1bdd0ab5a.png)

This is because the pointer areas are along the length of the arrow, like this:
![image](https://user-images.githubusercontent.com/679486/67573969-c93b3880-f6f6-11e9-931a-e646ef1b2834.png)

It seems it would enhance usability to change the icon pointer areas to be rectangular (just for the icons in the toolbox, not for the play area arrows).

In other sims, the pointer area for the toolbox icon has been made rectangular, so there are no "holes" or "dead areas" where the icon cannot be grabbed:

![image](https://user-images.githubusercontent.com/679486/67574677-22579c00-f6f8-11e9-9eaa-78374ad8b763.png)

That seems like it would be a good usability improvement in this sim as well.

I don't know if this has been discussed before, but I didn't see this particular topic in https://github.com/phetsims/vector-addition/issues/205 or skimming through other issues.  Assigning to @arouinfar since she is listed as lead design in the credits.

**Comment by pixelzoom** [comment]
Vector pointer areas have been thoroughly vetted on multiple occasions, including the icons in the toolboxes specifically. See https://github.com/phetsims/vector-addition/issues/183, https://github.com/phetsims/vector-addition/issues/205, https://github.com/phetsims/vector-addition/issues/207, https://github.com/phetsims/vector-addition/issues/240.

@arouinfar If you want to change to rectangles, then those rectangles will need to be customized for each scene.  For example, a different rectangle would be appropriate for the horizontal vs vertical scene in the _Explore 1D_ screen -- see screenshot below that attempt to use the same pointer areas for both scene, resulting in huge overlap for the vertical scene.  Estimate to make this change is 1-2 hours.

<img width="240" alt="screenshot_1637" src="https://user-images.githubusercontent.com/3046552/67610803-6a0b1180-f752-11e9-8c54-83f66f366623.png"> <img width="232" alt="screenshot_1638" src="https://user-images.githubusercontent.com/3046552/67610808-6e372f00-f752-11e9-8d35-b5d5e1e2da8f.png">

Note to self: See `iconNode` in `VectorCreatorPanelSlot`.

**Comment by pixelzoom** [comment]
> ... or more expanded touch areas

Uniformly expanding the pointer areas causes the same overlap problem. And pointer areas that conform to the arrow shape use `Shape.getOffsetShape`, which provide uniform dilation only (no separate dilation for x vs y.)  So this approach is not feasible.  If we must make the toolbox pointer areas larger, we should use rectangles, and specify `dilatedXY` per scene.

<img width="217" alt="screenshot_1639" src="https://user-images.githubusercontent.com/3046552/67611567-c290dd80-f757-11e9-9bc9-ddf910b00d5f.png"> <img width="217" alt="screenshot_1640" src="https://user-images.githubusercontent.com/3046552/67611566-bdcc2980-f757-11e9-8b71-7b21aa86fd07.png">

**Comment by samreid** [comment]
The icon code is currently:

```js
iconNode.mouseArea = iconNode.shape.getOffsetShape( VECTOR_MOUSE_AREA_OFFSET );
iconNode.touchArea = iconNode.shape.getOffsetShape( VECTOR_TOUCH_AREA_OFFSET );
```

If it is changed to:

```js
iconNode.mouseArea = iconNode.localBounds.dilated( 10 );
iconNode.touchArea = iconNode.localBounds.dilated( 10 );
```

Then the areas look like this:

![image](https://user-images.githubusercontent.com/679486/67612050-7c8a4880-f75c-11e9-9811-ba598506ebf7.png)

![image](https://user-images.githubusercontent.com/679486/67612069-aba0ba00-f75c-11e9-965d-2fbb7cab624c.png)


![image](https://user-images.githubusercontent.com/679486/67612047-73997700-f75c-11e9-9dcd-2cfc958a4aba.png)

![image](https://user-images.githubusercontent.com/679486/67612052-8318c000-f75c-11e9-84a0-7fc5b8bc43a2.png)

**Comment by pixelzoom** [comment]
If you don't mind eyeballing it based on current vertical spacing in the toolbox, which will certainly break in the future if the spacing changes (and it has changed many times in the past 3 months), then by all means use `dilated( 10 )` everywhere as @samreid is suggesting above.  If you want a robust solution, plan to spend the extra time to ensure that the pointer areas don't overlap and are optimized for the orientation of the icons in the toolbox.

**Comment by samreid** [comment]
I don't want to discourage you from implementing this in a robust way, but I wonder if we should schedule a developer meeting discussion about this, since I'm seeing a lot of occurrences of the "eyeball it" strategy across our codebase (some are mine):

![image](https://user-images.githubusercontent.com/679486/67612683-b6aa1900-f761-11e9-9ed9-fcd0a1cb137e.png)

**Comment by pixelzoom** [comment]
Whether eyeballing is appropriate depends on context.  For something like PHPaperNode, it's a tool you move around, overlap is not an issue, and the pointer areas are somewhat subjective.  For a set of checkboxes in a VBox, y dilations had better be < 1/2 of the VBox `spacing`, or you may have overlap.  If you set both y dilation and `spacing` empirically, you'll need to consider them both when making changes.  The toolbox in Vector Addition is a VBox, and falls into the latter category.

**Comment by pixelzoom** [comment]
One the other hand... QA seems to be pretty good at catching overlap, and it's certainly easier to hardcode a dilation and document it as "determined empirically".  So maybe it's OK.... I'm done both, so I'm on the fence.

**Comment by arouinfar** [comment]
@samreid I appreciate the suggestion, but I'm generally inclined to leave things the way they are. @kathy-phet @ariel-phet and I have all reviewed the pointerAreas, and this was not something that we had issues with. 

@KatieWoe have you or the QA testers have any issues dragging the vectors out of the toolbox?

**Comment by KatieWoe** [comment]
I haven't encountered any problems so far.  If that changes when we start testing small screens I'll let you know.

**Comment by samreid** [comment]
I'm failing to understand why I'm the only one that considers the following behavior problematic.  What about accessibility concerns or users with fine motor control issues?

![click](https://user-images.githubusercontent.com/679486/67695803-55559600-f96b-11e9-8bb6-7a593d387b28.gif)

**Comment by kathy-phet** [comment]
I also haven't personally had trouble with the interaction. That said, I would be OK with the dilate 10 approach described above to allow for more wiggle room in selecting a vector.  I don't think its worth doing precise custom code for each orientation in the tool boxes, however.

**Comment by pixelzoom** [comment]
I discussed this with @arouinfar and we decided to take a middle approach on this.  I added the ability to customize the icon pointer areas for each scene.  But the values for pointer areas are determined empirically rather than computed, so there may be some overlap if spacing is changed in the future.   And the same values are used for mouseArea and touchArea.  Screenshots below show pointer areas for each scene.

Changes were committed to master and 1.0 branches. @arouinfar please review in master.

_Explore 1D_

![screenshot_143](https://user-images.githubusercontent.com/3046552/67701582-cef28180-f975-11e9-8813-acba3717057a.png) ![screenshot_144](https://user-images.githubusercontent.com/3046552/67701585-d023ae80-f975-11e9-9ea2-ceda84f8b1e3.png)

_Explore 2D_

![screenshot_145](https://user-images.githubusercontent.com/3046552/67701607-d9ad1680-f975-11e9-9d59-568c1de047a9.png) ![screenshot_146](https://user-images.githubusercontent.com/3046552/67701610-db76da00-f975-11e9-82d3-862590483ada.png)

_Lab_

![screenshot_147](https://user-images.githubusercontent.com/3046552/67701619-e0d42480-f975-11e9-8637-74ee83e070d4.png) ![screenshot_148](https://user-images.githubusercontent.com/3046552/67701622-e29de800-f975-11e9-8657-e99ac63949a4.png)

**Comment by kathy-phet** [comment]
Looks good. Thanks!

**Comment by pixelzoom** [comment]
FYI, a bug crept in during this change, see #257. It's fixed in master and 1.0 in the above commits.

**Comment by pixelzoom** [comment]
Adding this to issues associated with 1.0.0-rc.1 testing in phetsims/QA#445.

**Comment by arouinfar** [comment]
Looks good in master @pixelzoom.

I do think this is an improvement, so thanks again for your suggestion and persistence @samreid.

**Comment by KatieWoe** [comment]
I noticed in https://github.com/phetsims/QA/issues/445 that on iPad I honestly had a bit more trouble picking up active vectors on the graph.  Not quite enough for its own issue, but @arouinfar might want to take a look.

**Comment by pixelzoom** [comment]
Let's be sure we're all using "active vector" the same way.  The active vector is the selected vector, and there can be at most one active vector.  All vectors on the graph have the same pointer areas, regardless of whether they are active (selected) or inactive (unselected). So... @KatieWoe do you really mean "active vector" or do you mean any vector that's on the graph?

**Comment by pixelzoom** [comment]
@KatieWoe it also feels like this should be a new issues.  This issue is about the icons in the toolbox.  Did you have any trouble with those?

**Comment by KatieWoe** [comment]
Either, the pointer area size doesn't differ, just any that is on the graph.  I did notice a bit more with active vectors.

**Comment by KatieWoe** [comment]
Do you want a new issue?  I figured they were the same since it involve vector Pointer Area size.  If @arouinfar thinks it is a problem I can make a new issue.

**Comment by pixelzoom** [comment]
They are not the same.  The toolbox contains icons that (as the result of this issue) are now rectangular.   Vectors on the graph are entirely different beasts, and have pointer areas that are shaped like arrows.  Did you have any problem with the icons in the toolbox?

**Comment by KatieWoe** [comment]
No

**Comment by pixelzoom** [comment]
Thanks @KatieWoe.  I've created https://github.com/phetsims/vector-addition/issues/263 to track the new issue reported in https://github.com/phetsims/vector-addition/issues/250#issuecomment-548102879.   And since there are no problems noted with the toolbox icons, I'm promoting this issue to "fixed-awaiting-deploy".

**Comment by KatieWoe** [comment]
Looks good in rc 2
