### ISSUE TITLE
0 vector has larger pointer area

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/vector-addition#252]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/QA/issues/445
When a vector goes to magnitude 0, the last pointer area stays active, meaning you can drag a vector that isn't there.  Since you could still drag a 0 vector by its label and this bug means you can drag around seemingly nothing, I think this should be fixed.  Particularly noticeable if made zero by a scale factor.  However, if made zero by looking at the sum of two opposite vectors a small version will occur. 
**Steps to reproduce**
1. Go to the last screen with showPointerAreas
2. Change the scale factor of one of the vectors to zero in the equation bar

**Visuals**
![smallerpoint](https://user-images.githubusercontent.com/41024075/67609299-3ecff480-f749-11e9-808d-ff058c44b20b.png)
![grabazerovector](https://user-images.githubusercontent.com/41024075/67609303-41cae500-f749-11e9-8be1-ea3116d59247.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Vector Addition‬
URL: https://phet-dev.colorado.edu/html/vector-addition/1.0.0-rc.1/phet/vector-addition_all_phet.html?showPointerAreas
Version: 1.0.0-rc.1 2019-10-23 17:30:32 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.70 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by arouinfar** [comment]
Thanks @KatieWoe. Definitely looks like you found a bug for @pixelzoom.

**Comment by pixelzoom** [comment]
Fixed in master, @KatieWoe please verify.

**Comment by pixelzoom** [comment]
This still needs to be cherry picked to 1.0 branch.

**Comment by pixelzoom** [comment]
Cherry pick to 1.0 has been done.

**Comment by KatieWoe** [comment]
Master seems to be solved

**Comment by pixelzoom** [comment]
Also relevant to From phetsims/QA#446.

**Comment by KatieWoe** [comment]
Looks good in rc.2
