### ISSUE TITLE
this.parentVector = parentVector; appears twice in ComponentVector.js

### ISSUE THREAD

**Issue by samreid** [phetsims/vector-addition#253]
While looking into https://github.com/phetsims/phet-io/issues/1454 I noticed that

```js
this.parentVector = parentVector;
```
appears twice in ComponentVector.js.

**Comment by pixelzoom** [comment]
Fixed, thanks.

This needs to be cherry-picked to 1.0.

**Comment by pixelzoom** [comment]
Cherry pick to 1.0 has been done.

**Comment by pixelzoom** [comment]
Closing this because there's nothing for QA to explicitly test.
