### ISSUE TITLE
Use ES6 template literal

### ISSUE THREAD

**Issue by veillette** [phetsims/vector-addition#26]
The modules should make use of template literals 

```
// String interpolation via template literals (in backticks)
const first = 'Jane';
const last = 'Doe';
console.log(`Hello ${first} ${last}!`);
```

**Comment by veillette** [comment]
This template should be used systematically throughout the simulation.

**Comment by brandonLi8** [comment]
Yea thats what I've been using instead of concatenation my whole js career. Shouldn't be too bad to migrate over.

**Comment by veillette** [comment]
I converted the last string concatenation in the simulation. Closing
