### ISSUE TITLE
Assertion failed: Not handling arcs with start/end angles that show differences in-between browser handling

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/vector-addition#261]
Related to phetsims/QA#445 and phetsims/QA#446.

Discovered during investigation of https://github.com/phetsims/vector-addition/issues/260.

This occurs on macOS 10.14.6 with Chrome 77 & 78, Safari 13.0.1, and Firefox 70 (and I suspect other supported platforms.)

It occurs in master bb1e85ecc038265599d580b1d2283aaee291867a and [1.0.0-rc.1/vector-addition_all_phet_debug.html?ea](https://phet-dev.colorado.edu/html/vector-addition/1.0.0-rc.1/phet/vector-addition_all_phet_debug.html?ea)

Steps to reproduce:

1. start sim with `?ea`
2. go to _Equations_ screen
3. Select the radio button for "Polar" coordinates (pink icon at lower right)
4. expand the "Base Vector" accordion box
5. set picker for 'd' magnitude to 1
6. set picker for 'e' magnitude to 1
7. set picker for 'e' theta to 85
8. set picker for 'd' theta to -95.  The assertion failure shown below will occur when transitioning from -90 to -95.

This happens when 'd' and 'e' magnitude pickers are equal and 1, 2, or 3.  It does not happen when they are 4-10, 0, or any negative value.

Chrome stack trace:
```
assert.js?bust=1572307060629:22 Uncaught Error: Assertion failed: Not handling arcs with start/end angles that show differences in-between browser handling
    at window.assertions.assertFunction (assert.js?bust=1572307060629:22)
    at Arc.invalidate (Arc.js?bust=1572307060705:333)
    at new Arc (Arc.js?bust=1572307060705:53)
    at Subpath.offset (Subpath.js?bust=1572307060705:481)
    at Shape.getOffsetShape (Shape.js?bust=1572307060705:1486)
    at SumVectorNode.updateVector (RootVectorNode.js?bust=1572307060705:147)
    at RootVectorNode.js?bust=1572307060705:108
    at listener (Multilink.js?bust=1572307060705:41)
    at TinyEmitter.emit (TinyEmitter.js?bust=1572307060705:68)
    at DerivedProperty._notifyListeners (Property.js?bust=1572307060705:265)
```

**Comment by pixelzoom** [comment]
The related code is `RootVectorNode` line 145:

```js
      // Make the arrow easier to grab by setting pointer areas
      if ( rootVector.magnitude > 0 && this.arrowNode.shape ) {
        this.arrowNode.mouseArea = this.arrowNode.shape.getOffsetShape( VectorAdditionConstants.VECTOR_MOUSE_AREA_DILATION );
        this.arrowNode.touchArea = this.arrowNode.shape.getOffsetShape( VectorAdditionConstants.VECTOR_TOUCH_AREA_DILATION );
      }
```

Inspecting `rootVector.magnitude`, its value is `9.71445146547012e-17`.

**Comment by pixelzoom** [comment]
`KITE/Arc` constructor has these assertions, and this is hitting the first one.  I'm going to ask @jonathanolson to translate.

```js
      // Constraints that should always be satisfied
      assert && assert( !( ( !this.anticlockwise && this._endAngle - this._startAngle <= -Math.PI * 2 ) ||
                           ( this.anticlockwise && this._startAngle - this._endAngle <= -Math.PI * 2 ) ),
        'Not handling arcs with start/end angles that show differences in-between browser handling' );
      assert && assert( !( ( !this.anticlockwise && this._endAngle - this._startAngle > Math.PI * 2 ) ||
                           ( this.anticlockwise && this._startAngle - this._endAngle > Math.PI * 2 ) ),
        'Not handling arcs with start/end angles that show differences in-between browser handling' );
```

**Comment by pixelzoom** [comment]
And thanks for handling!

**Comment by pixelzoom** [comment]
This is the last issue holding up the next RC, and we need to move on.  So I've pushed a workaround in the commits above to master and 1.0 branches.  

@jonathanolson if you want to investigate further, rollback the above changes in a branch. FYI, the assertion failure was occurring in the code shown in https://github.com/phetsims/vector-addition/issues/261#issuecomment-547199953 when `rootVector.magnitude` was very small (9.71445146547012e-17) and the dimensions of `arrowNode` were consequently very small (1.5157520574185608e-15 x 12).

**Comment by pixelzoom** [comment]
The general issue has been moved to https://github.com/phetsims/kite/issues/82.  This issue will be closed when it passes QA.

**Comment by KatieWoe** [comment]
This no longer seems to cause an assertion failure in rc.2
