### ISSUE TITLE
trouble picking up vectors on the graph

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/vector-addition#263]
For https://github.com/phetsims/QA/issues/445.

In https://github.com/phetsims/vector-addition/issues/250#issuecomment-548102879, @KatieWoe reported:

> I noticed in https://github.com/phetsims/QA/issues/445 that on iPad I honestly had a bit more trouble picking up active vectors on the graph.  Not quite enough for its own issue, but @arouinfar might want to take a look.

**Comment by pixelzoom** [comment]
Me in https://github.com/phetsims/vector-addition/issues/250#issuecomment-548104533:
> Let's be sure we're all using "active vector" the same way.  The active vector is the selected vector, and there can be at most one active vector.  All vectors on the graph have the same pointer areas, regardless of whether they are active (selected) or inactive (unselected). So... @KatieWoe do you really mean "active vector" or do you mean any vector that's on the graph?

@KatieWoe in https://github.com/phetsims/vector-addition/issues/250#issuecomment-548106090
> Either, the pointer area size doesn't differ, just any that is on the graph. I did notice a bit more with active vectors.

**Comment by pixelzoom** [comment]
@KatieWoe said:
> ... I did notice a bit more with active vectors.

I'm not sure why that would be the case. Pointer areas for active and inactive vectors are identical.  For example, 'a' is active, 'b' is inactive:

<img width="306" alt="screenshot_1653" src="https://user-images.githubusercontent.com/3046552/67901592-c7c1a400-fb2c-11e9-87e6-cde70a2672e2.png">

**Comment by KatieWoe** [comment]
It was mostly because the Vector Value box would stop showing the values

**Comment by pixelzoom** [comment]
I'm confused.... By "Vector Value box" do you mean "Vector Values accordion box"?  And why would whether that shows values affect your ability to grab a vector?

**Comment by pixelzoom** [comment]
Here are the current values for vector pointer areas in VectorAdditionConstants.js. The first pair of values is applied to the entire arrow and affects translation.  The second pair of values is applied to the arrow head, and affects rotation and scaling.

```js
    // dilation of vector (arrow) pointer areas
    VECTOR_TOUCH_AREA_DILATION: 3,
    VECTOR_MOUSE_AREA_DILATION: 3,

    // dilation of vector head pointer areas, for vectors that can be scales/rotated
    VECTOR_HEAD_TOUCH_AREA_DILATION: 8,
    VECTOR_HEAD_MOUSE_AREA_DILATION: 6,
```

**Comment by KatieWoe** [comment]
Yes.  I just meant that when I missed the active vector, the the Vector Values accordion box would show it immediately since it would stop showing the values.  Sometimes I could miss it if I picked up the vector by sliding my finger, but the active vector was more obvious.

**Comment by pixelzoom** [comment]
Assigning to @arouinfar to advise on how to proceed.
