### ISSUE TITLE
incorrect (solid) leader lines when sum vector is made visible

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/vector-addition#265]
For phetsims/QA#445 and phetsims/QA#446. Noticed while working on #264. Occurs in master and 1.0.0-rc.1.

If you check the Sum checkbox while Components radio button "projection" is selected, the sum vector's leader lines will be solid.  They should be dashed, since the sum vector isn't yet selected, and only the selected vector has solid leader lines.

Steps to reproduce:
1. Start the sim
2. Go to Explore 2D screen
3. Select the Components radio button for 'projection' style
4. Drag 'a' from toolbox to graph
5. Check the Sum checkbox.  The sum vector will appear on the graph. It is not selected, but it has solid leader lines.  See screenshot below.

This happens anytime that the Sum checkbox is toggle off and on.  If you select 's', then select 'a', the leader lines are corrected.

<img width="1007" alt="screenshot_1669" src="https://user-images.githubusercontent.com/3046552/67982365-2b5cd780-fbe8-11e9-9eb5-83c3bba5ddc0.png">

This is the expected behavior, dashed leader lines for the sum vector:

<img width="1006" alt="screenshot_1670" src="https://user-images.githubusercontent.com/3046552/67982548-85f63380-fbe8-11e9-8900-8bf8167e47f4.png">

**Comment by pixelzoom** [comment]
Same problem with 'c' and 'f' vectors in the _Equations_ screen.

**Comment by pixelzoom** [comment]
Fixed in the above commit. This bug would not have been possible in a strongly-typed language. Hate you Javascript.

No need to have anyone review this, it will be regression tested in 1.0.0-rc.2.

**Comment by pixelzoom** [comment]
Fixed in master and 1.0 branches in the above commits.

This bug would not have been possible in a strongly-typed language. Hate you Javascript.

No need to have anyone review this, it will be regression tested in 1.0.0-rc.2.

**Comment by KatieWoe** [comment]
Looks good in rc.2
