### ISSUE TITLE
missing leader line when sum vector component is zero

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/vector-addition#266]
For phetsims/QA#445 and phetsims/QA#446. Noticed while working on #265. Occurs in master and 1.0.0-rc.1.

If one of the sum vectors components is zero, its corresponding leader line will (sometimes?) be missing.

Steps to reproduce:
1. Start the sim
2. Go to Explore 2D screen
3. Drag 'a' from toolbox to graph
4. Rotate 'a' so that a.y === 0
5. Select the Components radio button for 'projection' style
6. Check the Sum checkbox. Note that the horizontal leader line that extends to the y axis is missing. See screenshot below.

<img width="1073" alt="screenshot_1673" src="https://user-images.githubusercontent.com/3046552/67983537-8099e880-fbea-11e9-9050-417aedb9cad6.png">

Similar problem with vertical leader line if a.x === 0. Note that the vertical leader line that extends to the x axis is missing. 

<img width="1074" alt="screenshot_1672" src="https://user-images.githubusercontent.com/3046552/67983327-12552600-fbea-11e9-9f96-1fe7aa07f36d.png">

**Comment by pixelzoom** [comment]
Also relevant to 'c' and 'f' vectors in _Equations_ screen.

**Comment by pixelzoom** [comment]
Fixed in master and 1.0 branches in the above commits. 

@arouinfar please review in master.  Note that when a component vector's magnitude it zero, the lead lines extend to where a non-zero component vector would be.  This looks a little odd (see examples below), and in retrospect I'd probably make these lead lines terminate at the axes. But that's not possible with the current implementation, and would be a big can of worms.  So I think it's probably fine, and we should just live with it. Let me know if you disagree.

![screenshot_1677](https://user-images.githubusercontent.com/3046552/68061769-1b1e2880-fccc-11e9-92ab-dbcace128161.jpg)

**Comment by arouinfar** [comment]
I am unable to reproduce the bug in master @pixelzoom.

I would agree that 1D vectors don't have the cleanest looking leader lines for the zero-magnitude component. However, I don't think it's particularly harmful, and I actually prefer the look of the leader lines connecting to the the components (when visible). Let's leave this as-is @pixelzoom.

**Comment by KatieWoe** [comment]
Looks good in rc.2
