### ISSUE TITLE
Overlap of component vector labels and angle

### ISSUE THREAD

**Issue by loganbraywork** [phetsims/vector-addition#267]
**Test device**
Windows 7 Laptop
**Operating System**
Windows 7 6.1
**Browser**
Chrome 77.0.3865.120
**Problem description**
From https://github.com/phetsims/QA/issues/445
Similar to https://github.com/phetsims/vector-addition/issues/264

When the y of a vector is 4>y>-4 and the vector resides within the 1st or 4th quadrants then the angle label and the y component length label overlap.
**Steps to reproduce**
1. Go to Explore 2D screen
2. Check the Values and Angle boxes
3. Switch to either the 1st or 3rd quadrant component radio buttons
4. Place a vector down and position it so that it sits at an angle of 90 degrees or -90 degrees (Although any position in the 1st or 4th quadrant will do)
5. Adjust the length of the vector so that it measures 0<y<4 or 0>y>-4
**Visuals**
![2019-10-31CmpntsVctrAdd](https://user-images.githubusercontent.com/54685448/67987554-5993e480-fbf3-11e9-847f-38e06f1b1ed9.gif)

![2019-10-31OvrlpAnglVctrAdd](https://user-images.githubusercontent.com/54685448/67987368-d3779e00-fbf2-11e9-934e-43c412ac5d39.gif)

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Vector Addition‬
URL: https://phet-dev.colorado.edu/html/vector-addition/1.0.0-rc.1/phet/vector-addition_all_phet.html
Version: 1.0.0-rc.1 2019-10-23 17:30:32 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36
Language: en-US
Window: 1366x625
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 32 varying: 32 uniform: 256
Texture: size: 8192 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {}

**Comment by KatieWoe** [comment]
Noting that it can occur in https://github.com/phetsims/QA/issues/446 too

**Comment by pixelzoom** [comment]
@loganbraywork thanks for reporting.

Over in https://github.com/phetsims/vector-addition/issues/93, I believe we decided that things are going to overlap, and there's no clear algorithmic way to avoid that.  If the user wants to create a visual mess, they can do that be turning on all of the visual representations.  If there's too much clutter or overlap, they should turn off some of the visual representations.  In this case specifically where the component values and angles are overlapping, the user should turn one of those visuals off if they want to clean things up. 

Assigning to @arouinfar to confirm.  If that's accurate, feel free to close as "won't fix".

**Comment by arouinfar** [comment]
Couldn't have said it better myself @pixelzoom. With all representations on, there's going to be times where overlap is unavoidable. Luckily, the the user can toggle things on/off as need be.
