### ISSUE TITLE
grabbing the origin manipulator clears the selected vector

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/vector-addition#268]
For phetsims/QA#445 and phetsims/QA#446.

This was introduced by https://github.com/phetsims/vector-addition/issues/238 (Click anywhere in the graph to clear the selected vector).

If you have a vector selected, grabbing the origin manipulator will clear the selection.  That seem kind of wrong.

Steps to reproduce:
1. start the sim
2. go to Explore 1D screen (but could be any screen)
3. drag 'a' from the toolbox to the graph, note that 'a' is selected
4. grab the origin manipulator, note that 'a' is no longer selected

I'll investigate. @arouinfar stop me if you don't think this is worth pursuing.

**Comment by pixelzoom** [comment]
Fixed in the above commits in master and 1.0 branches.  Tested on iPad to make sure this didn't break touch snag (as in #243).   The problem was that the origin manipulator was part of the graph, so had the "click to deselect" listener attached to it too.  I separated out the manipulator, so that the listener is only attached to the graph (which includes background, grid lines, ticks, and axes).

@arouinfar please verify in master.

**Comment by pixelzoom** [comment]
There was still one wart in the fix I made above: you could click on the arrow heads or 'x' and 'y' labels on the axes, and that would deselect.   I push a better solution to master and 1.0 branches in the above commits.  Clicking anywhere inside the graph's rectangular background now deselects.

**Comment by arouinfar** [comment]
Oh, I hadn't thought about the origin manipulator. Good catch @pixelzoom. The behavior in master is looking good.

**Comment by KatieWoe** [comment]
Looks good in rc.2
