### ISSUE TITLE
Unlink listeners

### ISSUE THREAD

**Issue by veillette** [phetsims/vector-addition#28]
Are there leaks due to registering observers or listeners? These guidelines should be followed, or documentation added about why following them is not necessary:
 - [ ] AXON: Property.link is accompanied by Property.unlink.
 - [x] AXON: Creation of DerivedProperty is accompanied by dispose.
 - [x] AXON: Creation of Multilink is accompanied by dispose.
 - [x] AXON: Events.on is accompanied by Events.off.
 - [x] AXON: Emitter.addListener is accompanied by Emitter.removeListener.
 - [x] SCENERY: Node.on is accompanied by Node.off
 - [x] TANDEM: PhET-iO instrumented PhetioObject instances should be disposed.

**Comment by brandonLi8** [comment]
We don't have` Node.on` anywhere

**Comment by brandonLi8** [comment]
b041f2974feba639c97414b4a4af1802731348fd
