### ISSUE TITLE
Add support for dynamic layout

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/vector-addition#280]

**Comment by pixelzoom** [comment]
I did the easy string Properties in https://github.com/phetsims/vector-addition/commit/ee2db85c1d82746920c5126219b78d7f6f06e905, and  verified their behavior with `?stringTest=dynamic`.

The remaining work is for these 2 strings:

```ts
  'symbol': {
    'x': string;
    'xStringProperty': LocalizedStringProperty;
    'y': string;
    'yStringProperty': LocalizedStringProperty;
  };
```

**Comment by pixelzoom** [comment]
Note that the vector symbols (a, b, c, d, e, f) are NOT translatable. That decision was made in https://github.com/phetsims/vector-addition/issues/10.   But we may want to store them as string Properties and address their dynamic layout, so that it's easy to make them translatable in the future, if desired.

**Comment by pixelzoom** [comment]
In the above commits, I moved the remaining "symbol" strings (including the symbols that are not currently translatable) to VectorAdditionSymbols.ts, where they are all string Properties.  Usage sites now need to be changed to update when these strings change.

**Comment by pixelzoom** [comment]
Dynamic locale support for axis symbols (x, y) is done.  And while I was at it, I added future localization support for vector symbols (a,b,c,d,e,f,s,v).

Ready for verification in dev testing.

**Comment by Nancy-Salpepi** [comment]
Looks good in https://github.com/phetsims/qa/issues/1163!

**Comment by Nancy-Salpepi** [comment]
Looks good in https://github.com/phetsims/qa/issues/1164 as well. Closing.
