### ISSUE TITLE
branch: modularizeCommon

### ISSUE THREAD

**Issue by brandonLi8** [phetsims/vector-addition#34]
## Restructure Common models/views to individual screens

**Comment by brandonLi8** [comment]
Currently, our common code is doing too much. We are trying to create a 'one size fits all' in many places.

 For example, our vectorCreatorPanel is trying to do too much:
   - different vector sets, different labels, number of vector sets, appearance on different icons, etc.
This 'one size fits all' approach its starting to break down.

This branch is to move code into respective screens.

Continuing with the vectorCreatorPanel as the example, we would create in each screen their own `VectorSet` and `scene`. In E1D, we would have a `horizontalVS` and a `verticalVS`, `verticalScene` and a `horizontalScene`. This way we can give parameters/properties that are SPECIFIC to each screen. (on 1D, the panel has 3 icons for 1 set, on lab, the panel has 1 icon for each set, 2 sets)

There are several places that could benefit from this, which is up for discussion. ie. `graphControlPanel`, `sumVisibleProperty( in common model)`,  `GraphControlPanel`( with different check boxes) etc.

**Comment by brandonLi8** [comment]
@veillette , I don't like the horizontalVectorSet and veritcalVectorSet approach. It needs to have isInfinite, labels, and numberOfSlots, but it seems redundant because It could be passed. 

That doesn't mean what we have with the creator panel is good.

I'm not sure what the approach is, I'll think about this.

**Comment by brandonLi8** [comment]
@veillette , not sure what to do for the creator Panel, but for the graph control panel, I think we should do what Chris did in GP for control panels. Each screen creates its own control panel. We can create a lot of classes to limit code copy and paste but it would be the same way that chris does it.

Also, the sum visibility is then created in each individual model, and lab would create 2.

Regarding the creator panels, I don't think the vectorSet approach fits. instead, I think we should do a similar thing with individual creatorPanels for each screen. Its what we have now, but more copy and pasted code (right now we have 3 abstract methods, we will need more)

**Comment by pixelzoom** [comment]
Due to https://github.com/phetsims/special-ops/issues/196#issuecomment-823486502, this branch was restored.  It will need to be deleted again.  Reopening and self assigning.

**Comment by pixelzoom** [comment]
Re-deleted using GitHub UI.  Closing.
