### ISSUE TITLE
VectorCreatorPanel API

### ISSUE THREAD

**Issue by veillette** [phetsims/vector-addition#36]
The API for the VectorCreatorPanel requires to pass two nodes:

````
  /**
     * @constructor
     * @param {Node} iconNode
     * @param {Node} vectorRepresentationNode
     * @param {Property.<ModelViewTransform2>} modelViewTransformProperty
     * @param {VectorSet} vectorSet - the vectorSet that the slot adds vectors to.
     * @param {Object} options
     */
    constructor( iconNode, vectorRepresentationNode, modelViewTransformProperty, vectorSet, options )
````

However, these two nodes are not orthogonal to one another and share many similarities.
They both represent arrows that point along the same direction.  They should be relatively similar in details from one screen to another. For instance,  the vectorRepresentationNode will need to have a dropped shadow and that dropped shadow should be present on the three screens (1D,2D, lab). Given this , i think we should shift the responsibility of creating the iconNode and vectorRepresentationNode to the VectorCreatorPanel. 

A proposal for the API change would that VectorCreatorPanel   
```
  /**
     * @constructor
     * @param {Vector2} initialVector - the direction, and length of the modelVector
     * @param {Color} color - color of the vector
     * @param {Property.<ModelViewTransform2>} modelViewTransformProperty
     * @param {VectorSet} vectorSet - the vectorSet that the slot adds vectors to.
     * @param {Object} options
     */
````

**Comment by brandonLi8** [comment]
I got this @veillette

**Comment by brandonLi8** [comment]
Color doesn't need to be there, it can check vector type from vectorSet and draw it itself
