### ISSUE TITLE
Remove possibility of setting Vectors to zero length by dragging.

### ISSUE THREAD

**Issue by veillette** [phetsims/vector-addition#37]
As we decided on a recent design meeting, It should not be possible to move the tip of a vector and set its length to zero. The value should be 'skipped' when the tip is dragged.

**Comment by veillette** [comment]
The property associated with the position of the drag listener is used to determined the vectorAttributes, if it's length is zero, we do not update the associated modelVector. 

This approach will work even in the polar/cartesian mode , (which is yet to be developed)

Work is done.

**Comment by brandonLi8** [comment]
This is fixed @veillette can we close?

**Comment by veillette** [comment]
Given the problem raised in #57, i think there is some problems with zero magnitude vectors.
