### ISSUE TITLE
The inspectVector Panel displays values for deleted vectors

### ISSUE THREAD

**Issue by veillette** [phetsims/vector-addition#38]
As noted by @brandonLi8, the inspectVector Panel can show the values associated with vectors that have been deleted with the erase button. 

A similar problem occurs when the reset button is used. ALthough the reset button closes the panel, reopening the panel shows that it display the information of vectors that are no longer on the board.

**Comment by veillette** [comment]
@brandonLi8 , you solution is a good start, but your approach will only work for the reset all, whereas it should also the case the the vectors are deleted.

**Comment by veillette** [comment]
If in #46 we decide to remove the vectors in bulk, then our work is done here.

**Comment by brandonLi8** [comment]
Finished with #60
