### ISSUE TITLE
How should we handle the labeling of vectors in lab screen.

### ISSUE THREAD

**Issue by veillette** [phetsims/vector-addition#39]
In the lab screen, the vector creator does not have labels, but the inspect vector panel  must have a label to make a reference to their component. 

The question is should we label the vector on the graph (when they are active).

if we label them, they could all have the same labels, say 'v'

another option is to label them dynamically, in alphabetical order, 'a b c d e f g, etc'
we should probably limit them to a number say 10 in that case. 

We should probably discuss it during our next design meeting.

Related to #17.

**Comment by brandonLi8** [comment]
Decided at the meeting that we are only showing the label on the active vector for the lab screen.

**Comment by veillette** [comment]
The labeling on the vector of the board will be shown with a 'v' if the vector is active. There is no labeling on the CreateVectorPanel. The InspectVectorPanel shows the label that is active.

**Comment by veillette** [comment]
I'm unsure how to deal with the Values checkbox since we are currently showing the magnitude and the label for all vectors.

**Comment by arouinfar** [comment]
> I'm unsure how to deal with the Values checkbox since we are currently showing the magnitude and the label for all vectors.

@veillette we had discussed the option of showing just the numbers when Values is checked. If the vector becomes active, then the magnitude string would update from something like "12.0" to  "| v | = 12.0".

**Comment by brandonLi8** [comment]
Labeling content is now corrected, closing
