### ISSUE TITLE
background of vector label wrong size when vector is first dropped

### ISSUE THREAD

**Issue by brandonLi8** [phetsims/vector-addition#40]
@veillette  can you check out this bug. When the vector is first dropped onto the graph, the label background is the wrong size. Once you move it it puts corrects itself and is the right size. Or once you turn on the values checkbox it corrects itself.
I've been trying to figure this out for the last hour ish. It seems as if formula node is bugging out.

**Comment by veillette** [comment]
The bounds of  the formula nodes, found through
```
this.label.calculateDOMBounds();
```
yield Bounds2.NOTHING.

Looking at formulaNode, it suggests that the DOM element 'katex-html' does not exist yet.

**Comment by veillette** [comment]
inspecting FormulaNode through the debugger, I found that the localBounds are non-zero, although too small.

**Comment by brandonLi8** [comment]
Looks to be fixed with 68af849 @veillette  can we close this?

**Comment by veillette** [comment]
Good investigating work. Closing.
