### ISSUE TITLE
Access modifiers

### ISSUE THREAD

**Issue by veillette** [phetsims/vector-addition#45]
Public, private, and protected are keywords to explicitly state the access-controls of class members. I have noticed that a lot of the ```this``` instance are set to ```@public``` when in fact it looks as if it should be ```@private```. 
In general, ```this``` should have the minimal access modifiers needed for the simulation to run.

PhET doesn't use underscore to denote private variables (except in common code)

Tagging @brandonLi8 so that he is aware of theses rules.

**Comment by brandonLi8** [comment]
@veillette, regarding this commit, i think that i should stay as it was. https://github.com/phetsims/vector-addition/commit/711389625fd881075a71d28ad809274ac22e7513

What we have right now is 
![image](https://user-images.githubusercontent.com/42391580/60140285-6fd5f380-976e-11e9-80cb-40aaaf011b9d.png)
I was going to change that to do` this.circleNode.dispose`, `this.angleNode.dispose` so there isn't too much in the constructor.

**Comment by brandonLi8** [comment]
Also with that commit, somehow the arrow tip is harder to grab. Not sure how but I checked out the commit before and it was fine. But with this commit, the arrow tip harder to grab.

**Comment by veillette** [comment]
Thanks for tracking down the problem with the tip

**Comment by veillette** [comment]
The dispose function is following a design pattern that are used throughout the simulations. 
Part of the reason is for the function to be in the constructor is that it doesn't expose all its variable, (albeit at the cost of a closure). 

You can find more information about the pattern here: 
https://github.com/phetsims/phet-info/blob/master/doc/phet-software-design-patterns.md#dispose
