### ISSUE TITLE
branch:  vectorSymbol

### ISSUE THREAD

**Issue by brandonLi8** [phetsims/vector-addition#47]
vectorSymbol is an experimental branch of not using formula node. Currently we use formula node only for one symbol: 
![image](https://user-images.githubusercontent.com/42391580/60046804-789eca80-9685-11e9-82ea-891ca25bdb85.png)

However, we are having issues with its sizing (see #40). On the inspect vector panel, it is also shrinking the magnitude label (formula node). 
![image](https://user-images.githubusercontent.com/42391580/60046879-a4ba4b80-9685-11e9-8e22-f1919241e39f.png)

As you can see, the magnitude label is inexplicably smaller, even though they have the same minWidth/maxWidth.

**Comment by brandonLi8** [comment]
At this point, it doesn't seem we need this (formula node now works). @veillette thoughts?

**Comment by brandonLi8** [comment]
Branch's `VectorSymbolNode` was merged (#85) and the branch is now deleted. Closing.

**Comment by pixelzoom** [comment]
Due to https://github.com/phetsims/special-ops/issues/196#issuecomment-823486502, this branch was restored.  It will need to be deleted again.  Reopening and self assigning.

**Comment by pixelzoom** [comment]
Re-deleted using GitHub UI.  Closing.
