### ISSUE TITLE
Odd assertion on vectorSets

### ISSUE THREAD

**Issue by veillette** [phetsims/vector-addition#48]
I found in BaseVectorModel an assertion on the vectorSets. 
I'm not sure how this assertion works since you are comparing a boolean to a number.

````
      assert && assert( vectorSets.filter( vectorSet => !( vectorSet instanceof VectorSet ).length === 0 ),
        `invalid vectorSets: ${vectorSets}` );

````

Assigning to @brandonLi8  to clarify (or simplify)

**Comment by brandonLi8** [comment]
@veillette Its filtering, to make sure each vector set in vectorSets is a instance of vector Set. In other words, there are 0 things in the array that aren't a vector set

**Comment by veillette** [comment]
I think i get it. Apparently the order of operations of the `!` operators is higher than equality check.

For clarification,  i think it would help if an additional set of parenthesis was added 
```
 !(( vectorSet instanceof VectorSet ).length === 0)
```

**Comment by veillette** [comment]
I think that what you meant was 
````
      assert && assert( vectorSets.filter( vectorSet => !( vectorSet instanceof VectorSet )).length === 0 ,
        `invalid vectorSets: ${vectorSets}` );
````

Note the change of parenthesis. I'm still not sure how this was able to pass this assertion initially. @brandonLi8 : can you check that it is correct?

**Comment by brandonLi8** [comment]
@veillette Yes that works also, but i wanted to make it explicit

```
0 === false // true
```
In javascript 0 is false, so doing a `!_.length` is the same as `0 === false`; I think its a minor thing and doesn't matter too much which one we do.

**Comment by veillette** [comment]
yeah but you use the triple equality here so that it check for type as well 
```
0===false; // false
```

**Comment by brandonLi8** [comment]
Right but when you do !, it does double equal.
so 
```
!g.length is the same as g.length === 0 is the same as g.length == 0
```

**Comment by veillette** [comment]
assertions use coercion such that this would work 
```
assert && assert( [1,2,3], 'smile')
``` 
In your case 
```
vectorSets.filter( vectorSet => !( vectorSet instanceof VectorSet ).length === 0 )
```
you are filtering your array yielding an array and therefore that it passes the assertion because the array is coerced to true. If you change the parenthesis as I described, then  
```
vectorSets.filter( vectorSet => !( vectorSet instanceof VectorSet ))
```
is an array and you can determine the length of the array and compare it to zero.

so that it the condition 

```
vectorSets.filter( vectorSet => !( vectorSet instanceof VectorSet )).length === 0 
```
is the correct one to use

**Comment by brandonLi8** [comment]
I've bee using this version throughout the sim...
```
vectorSets.filter( vectorSet => !( vectorSet instanceof VectorSet )).length === 0 
```
Not only with vector sets, but with sumVisibleProperties and graphs.

Closing as this is what I have been doing.
