### ISSUE TITLE
How should the mathematical symbols be rendered?

### ISSUE THREAD

**Issue by samreid** [phetsims/vector-addition#5]
The design doc shows mathematical notation like:

![image](https://user-images.githubusercontent.com/679486/58183396-85866380-7c6c-11e9-9ff5-fade61b51e7e.png)

and

![image](https://user-images.githubusercontent.com/679486/58183420-9040f880-7c6c-11e9-9e6b-fd9f973a794f.png)

Not sure if there are others.  In #2 we used katex + FormulaNode for rendering.  Here's some comments from that issue:

@veillette said:

> At this point, it is not very clear what is the long term plan, but FormulaNode (which requires katex) can be seen as a placeholder. I dont know about the long term plan for scenery nodes with Math Type but it may be something that need to be resolved for NumberLineIntegers @jbphet .

@samreid said:

> It would be good to consult with @jonathanolson regarding pros and cons of DOM.js subtypes (like FormulaNode). I believe it splits layers, like splitting one SVG layer into SVG/DOM/SVG. Or depending on your z-ordering you may end up with SVG/DOM/SVG/DOM/SVG/DOM...etc. Not sure what other pros and cons there are. I'll open a new issue for this topic.

This issue overlaps with https://github.com/phetsims/scenery/issues/457 where we discussed math symbols and where katex and other solutions were discussed.

**Comment by pixelzoom** [comment]
Vectors are rendered using FormulaNode in this sim, and they look great.  Unless there's some reason to change at this late point in development, I'm assuming that we're leaving them as is.  

Closing this issue. If someone disagrees, please reopen and describe what needs to be done.
