### ISSUE TITLE
How do we handle vector not dragged on onto the graph.

### ISSUE THREAD

**Issue by brandonLi8** [phetsims/vector-addition#50]
Currently the user can drag vectors from the creator panel to any location.
![image](https://user-images.githubusercontent.com/42391580/60116586-94fa4000-9735-11e9-93cf-0856d488773c.png)

Have we decided on what will happen if the user doesn't drag the vector onto the graph?

Personally, I think animating it back is the most user friendly.

**Comment by veillette** [comment]
If we do decide not to animate the vectors, then the twixt library should be removed from package.json

**Comment by arouinfar** [comment]
At today's design meeting, we decided to animate vectors back into the toolbox.

@brandonLi8 @veillette a recent example of items animating back into the toolbox is [Equality Explorer](https://phet.colorado.edu/sims/html/equality-explorer/latest/equality-explorer_en.html). There, items released below the scale will animate back into the toolbox.

**Comment by brandonLi8** [comment]
This animation is decided by the coordinate of the cursor. If the cursor is on the graph, drop the vector. Otherwise animate the vector back to the creator panel
