### ISSUE TITLE
Touch and CreateVectorPanelSlot

### ISSUE THREAD

**Issue by veillette** [phetsims/vector-addition#58]
The current implementation of VectorCreatePanelSlot creates only one vectorRepresentationNode. The visibility of the vectorRepresentation is toggled when the IconNode is selected.
This design works well when the number of vector is limited to 1, such at the Explore1D and Explore2D.

However, for the Lab screen,  this design does not support multi touch where one would like to grab several vectors at a time.

**Comment by veillette** [comment]
An approach to deal with it is to create the vectorRepresentation and add it to Scenery at the start event of the DragListener  and to remove it and the end event.

**Comment by brandonLi8** [comment]
With #60, this should be solved.

**Comment by brandonLi8** [comment]
fixe
