### ISSUE TITLE
A zero vector should not display an angle

### ISSUE THREAD

**Issue by veillette** [phetsims/vector-addition#59]
It is possible for the sum to be zero, in which case, we should not display the associated arcArrowNode. In addition the InspectVector Panel shown below, should display a noValue String such as emdash, U+2014.

![image](https://user-images.githubusercontent.com/7633344/60348478-9de54e80-998d-11e9-8a6d-626e2423de71.png)

**Comment by veillette** [comment]
NumberDisplay  supports noValueString:
```
      // options related to display when numberProperty.value === null
      noValueString: MathSymbols.NO_VALUE, // {string} default is the PhET standard, do no override lightly.
      noValueAlign: null, // {string|null} see ALIGN_VALUES. If null, defaults to options.align
      noValuePattern: null, // {string|null} If null, defaults to options.valuePattern
```
 We can address the InspectVectorPanel by ensure that we pass a null value to the angle when the magnitude of the vector is zero.

**Comment by brandonLi8** [comment]
Fixed now, closing.

**Comment by brandonLi8** [comment]
Comment: vectors with magnitude 0 should not show labels
