### ISSUE TITLE
branch: creatorAnimation

### ISSUE THREAD

**Issue by brandonLi8** [phetsims/vector-addition#60]
At the design meeting 6/27, we decided to animate the vector representation back to the panel if the user fails to drop the vector in the graph.

@veillette  and I decided to implement this by getting rid of the vector representation, and just create the vector the second the icon is clicked. This way, we would be able to 'save' the components and magnitude of the vector when its dragged out of the graph. 
![image](https://user-images.githubusercontent.com/42391580/60365517-21129e80-99a6-11e9-88f3-385e4b345e92.png)

This branch restructures the api for vectorCreatorPanel, vectorCreatorPanelSlot, and other views.

**Comment by brandonLi8** [comment]
This was a success in that I implemented the ability to remove vectors and animate vectors back.
Closing this issue and merging to master.

**Comment by pixelzoom** [comment]
Due to https://github.com/phetsims/special-ops/issues/196#issuecomment-823486502, this branch was restored.  It will need to be deleted again.  Reopening and self assigning.

**Comment by pixelzoom** [comment]
Re-deleted using GitHub UI.  Closing.

**Comment by pixelzoom** [comment]
Re-deleted using GitHub UI.  Closing.
