### ISSUE TITLE
Vector labeling on sum

### ISSUE THREAD

**Issue by brandonLi8** [phetsims/vector-addition#61]
According to the design doc `Lab screen: show label only when active`. 
And :
```
On the Lab screen, the label only appears when the vector is active, and displays the generalized label,v or s
```
I believe this shouldn't be the case. Instead, i think that it only shows the label for the active vector for normal vectors, but `always` shows the vector for the sum. Since the sum uses 's' they will still be distinguishable:
![image](https://user-images.githubusercontent.com/42391580/60533665-66441280-9cbd-11e9-9560-04ed5ecf1160.png)

Having strictly only the active vector show its sum seems weird to me:
![image](https://user-images.githubusercontent.com/42391580/60533725-8a9fef00-9cbd-11e9-980b-0d6d9d10fe36.png)

@arouinfar  thoughts?

**Comment by arouinfar** [comment]
@brandonLi8 that's a great suggestion. I agree; I see no reason why the sum label couldn't be always visible on the Lab screen, and would be better UX.

**Comment by brandonLi8** [comment]
Both in agreement and implemented with https://github.com/phetsims/vector-addition/commit/840c83ba94af906b1329359dceda3156e2517abe, closing
