### ISSUE TITLE
Questions on equation screen.

### ISSUE THREAD

**Issue by brandonLi8** [phetsims/vector-addition#64]
I'm starting to implement the equation screen, and from the mockups I have a few questions:

1. What is the number range of the coefficients? What would the panel say if was closed?
![image](https://user-images.githubusercontent.com/42391580/60623943-4128d000-9da1-11e9-9dc0-393bfa332117.png)

2. Do these represent separate scenes? If it is all in the same scene, i'm assuming only vector c would change.
![image](https://user-images.githubusercontent.com/42391580/60623995-6289bc00-9da1-11e9-9766-8d45d341ddac.png)

3. There is no vector creator panel to drag vectors onto the graph. Where are the vectors and ghost vectors when the sim is first started? Would the equation types change the positioning of the vectors.

4. Do the ghost vectors show components when components aren't invisible? Do ghost vectors show values as well when values is checked. Can ghost vectors be activated when dragging so the inspect a vector panel displays it? And if so, would the ghost vectors show angles when activated?

5. What are the defaults for vectors. Do they start off as <5,5> still?

**Comment by arouinfar** [comment]
I've answered some of these questions over Zoom, but answering in this issue so they're on the record. I'll also make sure this is all documented in the design doc too.

> What is the number range of the coefficients? 

Equation coefficients: [-5, 5]
Base vector components (Cartesian): [-10, 10]
Base vector magnitude (Polar): [-10, 10]
Base vector angle (Polar): [-180°, 180°] in steps of 5°

> What would the panel say if was closed?

Equation 

> Do these represent separate scenes? If it is all in the same scene, i'm assuming only vector c would change.

Yes, these are separate scenes. This will allow for users to make comparisons such as `a + -b = c` and `a - b = c`. The base vectors would be semi-global. That is, constant across the equation scenes, but different between the Cartesian and Polar modes. As a side note, Polar mode has vectors `d`, `e`, and `f` where `d` & `e` are the base vectors and `f` is the sum.

> There is no vector creator panel to drag vectors onto the graph. Where are the vectors and ghost vectors when the sim is first started? Would the equation types change the positioning of the vectors.

@brandonLi8 can you anchor the tails of the vectors to these major grid intersections, like so?

![image](https://user-images.githubusercontent.com/8419308/60843495-11f4d300-a194-11e9-85b0-6fa962c992e1.png)

The equation types would not change these positions, but the Base Vectors should not be visible by default.

> Do the ghost vectors show components when components aren't invisible? Do ghost vectors show values as well when values is checked. Can ghost vectors be activated when dragging so the inspect a vector panel displays it? And if so, would the ghost vectors show angles when activated?

The ghost vectors never show components or values. I'm leaning towards making them completely interactive (so no dragging/inspecting) but we should probably discuss this more at design meeting first.

> What are the defaults for vectors. Do they start off as <5,5> still?

This is still TBD, but here are some tentative defaults.

Equation coefficients: 1

**Cartesian mode <x, y>**
Base vector a: <0, 5>
Base vector b: <5, 5>

**Polar mode <r, θ>**
Base vector d: <5, 0°>
Base vector e: <5, 45°>

**Comment by brandonLi8** [comment]
This was implemented today
