### ISSUE TITLE
do a quick review

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/vector-addition#66]
7/11/19 status meeting:

PhET would like me to do a quick review of the current state of Vector Addition, focusing on:

* overall architecture
* architectural concerns related to PhET-iO
* application of design patterns
* any obvious code-review issues (but don't do a formal code review)

I'm planning to do this on Monday, 7/15/19.

@brandonLi8 @veillette @ariel-phet

**Comment by brandonLi8** [comment]
@pixelzoom, I was hoping that you could give me advice to solving number #33. I have been getting this for weeks, but it seems strange that It only picks up about 30% of the time on CT. I have been unable to reproduce even after 25+ minutes of fuzzing, and I have been trying for weeks.

**Comment by pixelzoom** [comment]
Quick review is done, here are my notes.

Overall, this sim is in very nice shape. Well done!  Specifically...

* I don't see anything obvious that would prevent or complicate PhET-iO instrumentation.
* Good use of general and PhET design patterns. 
* Documentation is overall very good. 
* The view is nicely broken up into classes that correspond to things that appear on the screen. 
* The model is also nicely organized.
* I like the use of "Root" prefix for base classes that have no superclass. I'm going to steal that
for the future. 

I only have one significant concern, and it's related to the model:

- [ ] Enumeration `VectorGroups` is confusing. I don't understand it, and believe that it might not be necessary.  As far as I can tell, it only determines what colors are used for a set of vectors.  The enumeration values ('ONE', 'TWO', 'THREE', 'FOUR') don't help me understand it.  So this needs some detailed documentation, and/or reexamination to see if it's necessary.   Feel free to break this out into its own issue if you'd like to discuss further.

Other minor things:

- [ ] String key “one” is unused, see warning printed by ‘grunt’.  And I’m not sure why it would be necessary to localize “1”.  Recommended to delete this key.

 - [ ] Using `VectorGroups` with the bracket operator to assign color to `VectorAdditionColors` seems sketchy, see code below. The bracket operator requires a string value. `VectorGroup` is an enumeration, enumeration value are opaque, and this is relying on an implicit conversion to string.   Not sure what to recommend as a better approach.  If there's not a better way, it would preferable to make the conversion to string explicit, e.g. `VectorGroups.ONE.toString()`. 

```js
70 VectorAdditionColors[ VectorGroups.ONE ] = {
77 VectorAdditionColors[ VectorGroups.TWO ] = {
84 VectorAdditionColors[ VectorGroups.THREE ] = {
91 VectorAdditionColors[ VectorGroups.FOUR ] = {
```

- [ ] Per the code-review checklist, it is not necessary to annotate ES6 `class` constructors with `@constructor`. E.g. `RootVectorModel` constructor.  Since this sim uses `class` instead of `inherit`, I would expect to find 0 occurrences of `@constructor`, but I see 61 occurrences. 

- [ ] For base/root classes that are not intended to be instantiated, annotate the constructor with `@abstract`. E.g. `RootVectorModel`.  That makes it unnecessary to say things like “should be subtyped”.  

- [ ] Distinguish between property and Property in comments, they are different things. E.g. in `RootVectorModel`, “tip and tail position properties” should be “tip and tail position Properties”.
Uppercase Property is an axon type. Lowercase property is a field in a JavaScript object.

- [ ] PhET typically does not put 'Model' suffix on model classes. For example, you have `RootVectorModel` and `RootVectorNode`.  We would typically just have `RootVector` and `RootVectorNode`. The exception to this rule is the top-level model for each screen, which should have a "Model" suffix, e.g. `Explore1DModel`.


- [ ] In `RootVectorModel` has `this.tag`.  Maybe this is some term that I'm not familiar with for vectors, but we typically refer to "a", "b", "c", etc. as "symbols".  So `this.symbol` might be a better name, to improve readability. 

- [ ] In general, you don't need to dispose Properties that you own.  For example, `RootVectorModel` does not need a `dispose` method because it owns all of the Properties that are being disposed.  You do need to dispose a `DerivedProperty` or `Multilink` that you own if it has a dependency that you don't own.
 
- [ ] Properties that are specific to the view typically do not belong in the model. For example, `VectorAdditionModel` contains Properties that are used only in the view.  They would typically be in `common/view/VectorAdditionViewProperties`.

- [ ] There's a basic terminology problem with "vector component", as used in `VectorComponentModel`. A "vector component" is a scalar, not a vector, and it's especially confusing that "vector component" is sometimes a scalar and sometimes a vector in this sim.  I discussed with @arouinfar, and she suggested that "component vector" is the proper term in this context, since it is the projection of a vector component (scalar) onto an axis, which results in a vector.  So try to differentiate between "vector component" (scalar) and "component vector" (vector) in names and documentation.

- [ ] You don't need to provide a description of `options` parameters, we all know what they are. I see the doc below duplicated at least 25 times.  `@param [Object] options` is generally sufficient.

```js
* @param {Object} [options] - Various key-value pairs that control the appearance and behavior. Some options are
*                             specific to this class while some are passed to the superclass. See the code where
*                             the options are set in the early portion of the constructor for details.
```

- [ ] When implementing `dispose`, PhET has a well-defined pattern that should be followed. As an example, look at `this.unlinkListeners` in `VectorAngleNode`.  Everything is correct here except the name `unlinkListeners`.  PhET convention is to call this `dispose VectorAngleNode`.  The general naming convention is `dispose{{CLASS_NAME}}`.

**Comment by pixelzoom** [comment]
Back to you @brandonLi8.  Let me know if you have any questions.

**Comment by brandonLi8** [comment]
Thanks @pixelzoom!

**Comment by brandonLi8** [comment]
Assigning @chrisklus for review

**Comment by chrisklus** [comment]
@brandonLi8 sorry I did not clarify this earlier, but typically when a dev does a review, the same dev signs off on the changes that comes from the review. So I'm going to assign back to @pixelzoom.

@pixelzoom let me know if you feel differently - I'm happy to look over these if you prefer.

**Comment by pixelzoom** [comment]
Changed look great @brandonLi8, nice job.   

I skipped the `VectorGroups` item, and will review that over in #75.

Closing.
