### ISSUE TITLE
Base vectors are semi global; but this could be problamatic

### ISSUE THREAD

**Issue by brandonLi8** [phetsims/vector-addition#68]
At the design meeting today, we decided vase vectors are global for the cartesian and polar scenes.

We decided that along with their components, their tail's would be the same for all three graphs. For instance, if a base vector was at the coordinate (5, 5) for one scene, it would be at the same coordinate for all scenes (within polar/cartesian)

I have just realized that this is problematic. Since the origin can be dragged, the tail position is different.

Consider the following scenario:
![image](https://user-images.githubusercontent.com/42391580/61099139-965a8680-a41e-11e9-86dc-fd7a440d4618.png)
The user drags the origin all the way to the top right corner in the second scene

Then in the First scene, the user moves base vector b:
![image](https://user-images.githubusercontent.com/42391580/61099188-b722dc00-a41e-11e9-9819-4780ec0ae766.png)

base vector `b` is at the point (45, 20)

Then the user switches back to the second scene.

Since the origin is so far to the right, the point (45, 20) is way off the graph. It is impossible to even grab it since it is so far off the graph.

@arouinfar  @ariel-phet how should I approach this?

**Comment by brandonLi8** [comment]
I think there are 2 solutions:

1. Instead of having the base vector's tail position be saved, have its view coordinates be saved.
This would be that even though it's on (45,20) in the first scene, it would be translated to a different spot on the second scene so that it's in the same spot to the visual eye.

2. Instead of having different scenes, have the three equation scenes just be a single scene. However, each scene would have its own equation panel.

Method 2 seems to be more feasible.

**Comment by arouinfar** [comment]
@brandonLi8 option (1) is highly preferable.

Option (2) isn't great from a pedagogical standpoint. The primary motivation for the `a - b = c` scene is that it allows students to compare subtraction to the addition of a negative in the `a + b = c` scene.  It would be really nice to be able to switch between two equivalent equations, such as  `a - 2b = c` and `a + -2b = c`. This would require independent coefficients in each scene.

**Comment by brandonLi8** [comment]
@arouinfar what I meant for option 2 would be to have each equation type have its own equation panel.
When going from the first equation to the second equation,  the equation panel would switch as well.

Another way to think about it is it would be essentially the same as 3 more scenes but the origin is semi global.

Thoughts?

**Comment by brandonLi8** [comment]
https://github.com/phetsims/vector-addition/issues/67#issuecomment-511962864

**Comment by arouinfar** [comment]
> @arouinfar what I meant for option 2 would be to have each equation type have its own equation panel.
When going from the first equation to the second equation, the equation panel would switch as well.

@brandonLi8 so the entire equation panel would change for each equation type? If that solves the problem, then that would be fine with me, so long as the panel placement remains the same.

**Comment by brandonLi8** [comment]
Yes! This makes everything A LOT easier :)

**Comment by brandonLi8** [comment]
Now solved with #67
