### ISSUE TITLE
"Inspect a vector" accordion box is confusing

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/vector-addition#71]
Noted while playing with the sim in preparation for "quick review" #66.

The first thing that I went for in this sim was the "Inspect a vector" accordion box.  And I found it very confusing that it toggled between the 2 states shown below:

<img width="512" alt="screenshot_1278" src="https://user-images.githubusercontent.com/3046552/61190747-70bbc000-a65e-11e9-8a58-a1ce58cbdb93.png">

<img width="509" alt="screenshot_1279" src="https://user-images.githubusercontent.com/3046552/61190749-731e1a00-a65e-11e9-916f-b83c62214875.png">

I eventually figured out that "Inspect a vector" is the title.   And when expanded, the title is hidden and "Select a vector" is the content, in lieu of a selected vector.  

First, "Inspect a vector" and "Select a vector" are both commands.  AccordionBoxes should be labeled with titles that indicate what the box contains, so the former should be something like "Selected Vector" (in title case).

Second, this would not be nearly as confusing if the title wasn't hidden when the box is expanded. I realize that there are space constraints, but highly recommended to keep the title visible. Or investigate another way to show/hide the properties of the selected vector.

**Comment by pixelzoom** [comment]
The more I think about this, an AccordionBox feels like the wrong UI component for this job.  How about a check box inside of a panel?  Something like this:

![unchecked](https://user-images.githubusercontent.com/3046552/61190953-8e3e5900-a661-11e9-83f8-9ed096b37318.jpg)

![checked](https://user-images.githubusercontent.com/3046552/61190956-91394980-a661-11e9-8b7a-c6b210940039.jpg)

**Comment by pixelzoom** [comment]
Sorry, there should really be 3 mockups in the comment above.  When no vector is selected, the "Inspect Vector" check box is disabled and the "Select a vector" instruction is shown.  When a vector is selected and the "Inspect Vector" check box is unselected, then the area to the right of the checkbox is blank.  

Revised mockups showing the 3 states:

![unchecked1](https://user-images.githubusercontent.com/3046552/61191015-5d125880-a662-11e9-8697-79ce793c4c0c.jpg)

![unchecked2](https://user-images.githubusercontent.com/3046552/61191017-61d70c80-a662-11e9-9e00-5ad1b4fdf147.jpg)

![checked](https://user-images.githubusercontent.com/3046552/61191018-656a9380-a662-11e9-8fb5-9444a4f54b66.jpg)

**Comment by pixelzoom** [comment]
I have similar feelings about the "Equation" accordion box in the "Equation" screen.  Using an Accordion Box to show/hide one thing is not what accordion boxes are typically used for.

**Comment by pixelzoom** [comment]
One more comment to tie together some of my thoughts...    In general, I think we need to be careful about using an accordion box to show/hide one thing, especially when combined with the "hide title when expanded" feature.   Doing so results in an odd UX -- an accordion box that does not change size when the button is clicked.  It's named "accordion" box because the space that it occupies grows/shrinks to show/hide its content. And when there's no growing or shrinking happening, that should be a red flag that we may not be using the right UI component for the job.

**Comment by brandonLi8** [comment]
@pixelzoom wanted to point out that these are not accordion boxes. Once you do the "quick review" #66 you can see it uses a module named `ExpandCollapsePanel`. Not sure if this changes the UX or what you think of this, but just wanted to clarify.

**Comment by pixelzoom** [comment]
Thanks for the clarification @brandonLi8.   But I still have the same concerns -- regardless of how it's implemented, from the user's perspective, it looks like an accordion box.

**Comment by pixelzoom** [comment]
@brandonLi8 said:
> ... wanted to point out that these are not accordion boxes. Once you do the "quick review" #66 you can see it uses a module named `ExpandCollapsePanel`. ...

Looking at `ExpandCollapsePanel`, it is duplicating functionality that `AccordionBox` provides.  So if the UI is not changed,  `ExpandCollapsePanel` should certainly be replaced with `AccordionBox`.

**Comment by brandonLi8** [comment]
@pixelzoom If I were to use `AccordionBox`, the contentNode would be nothing, and the titleNode would technically be the entire panel (i.e. 'select a vector', 'inspect a vector' ... )

Since the contentNode isn't really anything, I would have to pass an arbitrary new Node() as the content node. But this fails an assertion (rectHeight should be a finite number).

Because of this, I would have to give an arbitrary node with a defined width/height. But If I did this, the AccordionBox would change height as you 'open' and 'close' it.

So if the UI is not changed, how would I achieve an accordion box without changing size when opened and closed, but at the same time not really having a contentNode?

**Comment by pixelzoom** [comment]
> ... how would I achieve an accordion box without changing size when opened and closed, but at the same time not really having a contentNode?

* Make sure that your ExpandCollapsePanel's `closedContent` and `openContent` have the same height, by using an AlignGroup or adding a VStrut.
* Create an AccordionBox with `showTitleWhenExpanded: false`.
* Take the `closedContent` arg of your ExpandCollapsePanel and pass it to the AccordionBox via `options.titleNode`.
* Take the `openContent` arg of ExpandCollapsePanel and pass it to the AccordionBox via param `contentNode`.

The other reason for using AccordionBox is for a11y and PhET-iO instrumentation.  A custom component like ExpandCollapsePanel is going to require custom instrumentation, it's going to be confusing to Studio users, because it looks like an AccordionBox but isn't, and it's going to be confusing for screen readers for the same reason.

And again...  This is only if there will be no UI change.

**Comment by brandonLi8** [comment]
From the design meeting:
- Change 'Inspect A Vector' to 'Vector Values'
- Change 'Select a Vector' to 'No vector selected'

**Comment by brandonLi8** [comment]
Decided with @arouinfar that
- theta size should be italicized and larger
- spacing should increase only on the 'equation' screen
- more spacing for the expandCollapseButton

**Comment by brandonLi8** [comment]
With the commit above, expand collapse panel now extends `AccordionBox`. Back to @pixelzoom for review (note that some of the naming needs to change. To be addressed in #81).

**Comment by pixelzoom** [comment]
I still think this is a questionable way to use an AccordionBox. But I'm guessing that a conclusion the design meeting mentioned in https://github.com/phetsims/vector-addition/issues/71#issuecomment-515200590 was to stick with it.  That said...

The adjusted wording and use of AccordionBox makes this much better.  I reviewed the code changes, and they look good.    

Back to @brandonLi8 is case there's anything left to do here. Feel free to close.

**Comment by brandonLi8** [comment]
Thanks! Closing
