### ISSUE TITLE
are screen names correct? 

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/vector-addition#72]
Noted while playing with the sim in preparation for "quick review" #66.

Are "Explore1D" and "Explore2D" the intended screen names? Recommended to add a space, i.e. "Explore 1D" and "Explore 2D". 

<img width="937" alt="screenshot_1283" src="https://user-images.githubusercontent.com/3046552/61191036-e45fcc00-a662-11e9-9158-89cb344b3519.png">

**Comment by arouinfar** [comment]
>Are "Explore1D" and "Explore2D" the intended screen names? 

No, these are not the intended screen names in the view. @brandonLi8 please add a space.

**Comment by brandonLi8** [comment]
Implemented with 32a6cc2. Closing
