### ISSUE TITLE
have Unfuddle tickets been triaged?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/vector-addition#73]
There are 6 open tickets for vector-addition in Unfuddle.  Have these been triaged?

<img width="1030" alt="screenshot_1284" src="https://user-images.githubusercontent.com/3046552/61191077-43bddc00-a663-11e9-90ec-dd9b8908c517.png">

**Comment by arouinfar** [comment]
They have been now @pixelzoom. I've commented in and closed all of these issues, as they were either irrelevant to the HTML5 design or have already been addressed.
