### ISSUE TITLE
More questions for the sim

### ISSUE THREAD

**Issue by brandonLi8** [phetsims/vector-addition#74]
I have finished implementing #68 and in my opinion, we are super close to being feature complete.

That being said, I have more questions about the rest of the tasks that need to be done:

1. What should the inspect a vector panel display when vectors have a coefficient (e.g. 3A)?

2. We might have discussed this at the design meeting but do base vectors display component vectors?

3. #16 do we have a solution? We can talk about this at a design meeting but If base vectors display component vectors, this could get tricky.

4. #71 do we have a solution?

Other than this and polishing, the sim is in great shape.

**Comment by arouinfar** [comment]
> What should the inspect a vector panel display when vectors have a coefficient (e.g. 3A)?

Great question. Yes, I think the inspect panel should show the coefficient. For vector magnitude (both in inspect and play area) the coefficient should go inside of the absolute value bars. 

> We might have discussed this at the design meeting but do base vectors display component vectors?

I think we had considered not showing the coefficients on the base vectors, but giving it more thought, I think it would be more powerful to have them shown.

In this example b = 2a. If we show the components of the base/ghost vectors, then students would be able to see how the components scale up too.

![image](https://user-images.githubusercontent.com/8419308/61646555-93a23180-ac67-11e9-8e70-b3a7babc0e21.png)


> #16 do we have a solution? We can talk about this at a design meeting but If base vectors display component vectors, this could get tricky.

No, not yet. Can you evaluate the options presented in https://github.com/phetsims/vector-addition/issues/16#issuecomment-500601328, and let me know what you think.

> #71 do we have a solution?

No, but I will try to comment on this issue soon!

**Comment by brandonLi8** [comment]
@arouinfar said 
>For vector magnitude (both in inspect and play area) the coefficient should go inside of the absolute value bars.

This is what is currently used:
![image](https://user-images.githubusercontent.com/42391580/61654797-7165df00-ac7a-11e9-8b60-a2fff37b02f0.png)

Since the coefficient goes inside the absolute value bars, would it be possible to put the 2 inside the formula node.

Otherwise, it makes it more complicated.

**Comment by arouinfar** [comment]
@brandonLi8 yes, I think it would be acceptable to put the 2 inside of the formula node. I know that means the font face will be different than other numbers, but that seems like a reasonable trade-off to me.

**Comment by brandonLi8** [comment]
From design meeting:
  - When the coefficient is 0, the label should say '0a'
  - Dashed vectors on component vectors (lineArrowNode.js)

**Comment by brandonLi8** [comment]
With my commits above, I was able to:

1. Have the label show the 0 when the coefficient is 0.
![image](https://user-images.githubusercontent.com/42391580/62150734-f6c14300-b2bb-11e9-88a5-8423fe3191ea.png)
But still say 'a' when the components are 0. 
![image](https://user-images.githubusercontent.com/42391580/62150777-0ccf0380-b2bc-11e9-982b-688b6a5ed32e.png)


2. 
Make the inspect a vector panel show coefficients, with the magnitude inside the absolute value bars. I was able to keep the fonts consistent with the coefficient and the symbol.
![image](https://user-images.githubusercontent.com/42391580/62150821-30924980-b2bc-11e9-8196-8fdf3cfb4052.png)

In Order to fit this, I had to make the panel larger. This is what it looks like now on Explore2D: 
![image](https://user-images.githubusercontent.com/42391580/62150925-69cab980-b2bc-11e9-9659-ac560989ddf5.png)

@arouinfar is this ok with you?

**Comment by brandonLi8** [comment]
I'm also assigning @chrisklus to review https://github.com/phetsims/vector-addition/issues/74#issuecomment-515197596.


Don't worry about `Dashed vectors on component vectors (lineArrowNode.js)`, as this is tracked in #84.

**Comment by brandonLi8** [comment]
Side note:
- the base vectors accordion box on polar mode should be 'theta<sub>a</sub>'

**Comment by chrisklus** [comment]
Implementation looks good, back to @brandonLi8.
