### ISSUE TITLE
VectorGroups confusing

### ISSUE THREAD

**Issue by brandonLi8** [phetsims/vector-addition#75]
@pixelzoom noted in #66 :
> - [ ] Enumeration `VectorGroups` is confusing. I don't understand it, and believe that it might not be necessary.  As far as I can tell, it only determines what colors are used for a set of vectors.  The enumeration values ('ONE', 'TWO', 'THREE', 'FOUR') don't help me understand it.  So this needs some detailed documentation, and/or reexamination to see if it's necessary.   Feel free to break this out into its own issue if you'd like to discuss further.

I agree that it is confusing, but I am not sure what to do instead.
For now, I am going to say the only functionality of VectorGroups is to decide what colors are used.

I tried using a static variable in VectorSet like:
```
  VectorSet.COLOR_GROUPS = new Enumeration( [ 'COLOR_GROUP_1', 'COLOR_GROUP_2', 'COLOR_GROUP_3', 'COLOR_GROUP_4' ] );
```

However, it wouldn't be usable in VectorAdditionColors as it cannot load `VectorSet.js` (has not been loaded yet for context)

I am leaning towards renaming `VectorGroup` to `VectorColorGroups` and using ` [ 'COLOR_GROUP_1', 'COLOR_GROUP_2', 'COLOR_GROUP_3', 'COLOR_GROUP_4' ] ` instead.
We wouldn't need to pass it to every model, as just `VectorSet` should suffice.

**Comment by brandonLi8** [comment]
Assigning @chrisklus for review

**Comment by chrisklus** [comment]
I'm also not understanding why a separate Enum is needed for this. It seems like four color groups could just be object literals in VectorAdditionColors.js:

```js
BLUE_COLOR_GROUP: {
  fill: 'rgb( 10, 170, 250 )',
  sum: 'rgb( 0, 181, 225 )',
  component: 'rgb( 120, 200, 255 )',
  labelBackground: 'rgb( 150, 210, 255 )'
},
```

And then they could directly be assigned instead of the using an Enum key, so:
```
this.vectorGroup = vectorGroup;
```
would look like
```
```

**Comment by chrisklus** [comment]
I'm also not understanding why a separate Enum is needed for this. It seems like four color groups could just be object literals in VectorAdditionColors.js:

```js
BLUE_COLOR_GROUP: {
  fill: 'rgb( 10, 170, 250 )',
  sum: 'rgb( 0, 181, 225 )',
  component: 'rgb( 120, 200, 255 )',
  labelBackground: 'rgb( 150, 210, 255 )'
},
```

And then they could directly be assigned instead of the using an Enum key, so:
```js
// @public (read-only) {VectorColorGroups} vectorColorGroup - vectorColorGroup for the set
this.vectorColorGroup = vectorColorGroup;
```
would look something like
```js
this.vectorColorGroup = VectorAdditionColors.BLUE_COLOR_GROUP;
```

And then options that currently look like

```js
fill: VectorAdditionColors[ vectorColorGroup ].sum
```

would instead look like this:

```js
fill: vectorColorGroup.sum
```

I'm not sure if this covers all of your cases, but I think it would be nicer if it worked out. Otherwise, if an Enum is needed, I think something like `BLUE_COLOR_GROUP` would be a better value than `ONE`. @pixelzoom any thoughts?

**Comment by pixelzoom** [comment]
I like @chrisklus' `BLUE_COLOR_GROUP` suggestion above, so perhaps @brandonLi8 can comment on whether it would work.   And I agree that enum values like 'BLUE' would be better than 'ONE', per the code comments:

```js
  const VectorColorGroups = new Enumeration( [
    'ONE',    // Blue
    'TWO',    // Red
    'THREE',  // Purple
    'FOUR'    // Green
  ] );
```

**Comment by brandonLi8** [comment]
@chrisklus I like the idea, going to go forward with it.

**Comment by brandonLi8** [comment]
After thinking about it over the night, I like having the enumeration as is.


When creating graphs, the `VectorColorGroup` is passed to it.
For instance, in `Explore1DModel`:
```
this.polarGraph = new Explore2DGraph( CoordinateSnapModes.POLAR,
        this.componentStyleProperty,
        VectorColorGroups.THREE );
```

I like this better than passing an object , `BLUE_COLOR_GROUP`.:
```
 {
  fill: 'rgb( 10, 170, 250 )',
  sum: 'rgb( 0, 181, 225 )',
  component: 'rgb( 120, 200, 255 )',
  labelBackground: 'rgb( 150, 210, 255 )'
},
```

Not only would the js doc get much longer (as the color group is passed from graph, to vector set, to vectors/root vectors/componentVectors, and each time I would have to document the fill, sum, component, and labelBackground), but It also doesn't feel like it is as clean as just an Enumeration Value.


In the meantime, I will change it to be `BLUE_COLOR_GROUP` instead of `ONE`.

**Comment by brandonLi8** [comment]
Back to @chrisklus for further comment.

**Comment by brandonLi8** [comment]
Chatted with @chrisklus about either using the enumeration or passing the object. Didn't come up with a solution so we would like to see what @pixelzoom thinks about it.

**Comment by brandonLi8** [comment]
I was once told that names should never be based on appearance. For example, in `GasProperties`  , the particles are called `Particle1` and `Particle2` instead of something like `ParticleRed` and `ParticleBlue`.

At the moment, the values of the enumeration are `BLUE_COLOR_GROUP`, `RED_COLOR_GROUP` ... but it doesn't feel right to me to be naming these values after the appearance. Moreover, using these values is requiring me to name other variables in various other views based on the color as-well.

This gets problematic if a designer wants to change a color, and I have to change the name of the enumeration value along with various other variable names.

Thus, In my opinion, I like `ONE` more than `BLUE`. Perhaps something more specific like `VECTOR_COLOR_GROUP_1` could ease confusion.

@chrisklus  @pixelzoom  thoughts?

**Comment by pixelzoom** [comment]
Good point @brandonLi8.   I'm fine if you want to stick with names like `VECTOR_COLOR_GROUP_1`.

**Comment by brandonLi8** [comment]
Refactored names in https://github.com/phetsims/vector-addition/commit/2282f3d26b17c01e1f06177e59867b040902f3e0 to:
```
  const VectorColorGroups = new Enumeration( [
    'COLOR_GROUP_1',    // blue
    'COLOR_GROUP_2',    // red
    'COLOR_GROUP_3',    // purple
    'COLOR_GROUP_4'     // green
  ] );
```

Assigning @chrisklus for review

**Comment by chrisklus** [comment]
Looks good, back to @brandonLi8 to close.
