### ISSUE TITLE
Vector Label Node Refactor

### ISSUE THREAD

**Issue by brandonLi8** [phetsims/vector-addition#77]
In #76, the vectors in the screen icons contain vector label nodes. 

`VectorLabelNode`'s API uses a RootVector. So in order to use the label node, a root vector must be instantiated. This cannot be done in the Icon Factory

Approach 1: Create background rectangles manually in the Icon Factory. This is what I was going to do but felt like too much copy and pasting.

Approach 2. `VectorLabelNode' should  change its api:
```
## API:
 *  - Meant to be a static view, but the content (coefficient and value) can be changed with methods
 *
 *  - NOT meant depend on a RootVector. In other words, this WILL NOT update its content to match a Vector (In fact, it
 *    isn't even necessary to instantiate a RootVector to generate this view. This is how the Icon Factory creates
 *    label nodes without instantiating a Vector in the screen icons).
 *        - However, since this view contains methods to change the content (coefficient and value), links can be made
 *           to a RootVector EXTERNALLY to match a vector's symbol, coefficient, and value
 *
 *  - WILL auto format. For instance, it a value was 15 and its symbol is 'a', this view will auto format the display to
 *    be '|a|=15' with the absolute value bars and equals symbol.
 *
 *  - This view is NOT responsible for any positioning other than the text nodes / formulates internally.
 *    (for instance if it is desirable to put the label node under a vector node, it must be done externally).
 *
 *  - Contains method to change if the label is part of a active vector (which uses a yellow label) or not.
 *
```

RootVectorNode will then update it with a multilink.

Approach 2 is what I am going to work on today.

**Comment by brandonLi8** [comment]
I am experiencing a weird bug with `Formula Node` inside of screen icons:

Right now, the screen icon passed to `Explore1d` as a test icon is :
```
new ScreenIcon( new Node().setChildren( [ new FormulaNode( 'hello world') ] ) );
```

This seems like the correct view when the icon is deselected:

![image](https://user-images.githubusercontent.com/42391580/61684764-b5d39800-acd7-11e9-9cb6-8f7ae7853b60.png)

However, when it is selected, it strangely just goes away:
![image](https://user-images.githubusercontent.com/42391580/61684817-df8cbf00-acd7-11e9-839f-2629fea5631d.png)

Can someone confirm that this is an issue or am I forgetting something?

**Comment by brandonLi8** [comment]
Stalled https://github.com/phetsims/vector-addition/issues/77

**Comment by brandonLi8** [comment]
See https://github.com/phetsims/vector-addition/issues/78#issuecomment-514329300. Since this is the case, I'm going to revert back to before 
a80ea39

**Comment by brandonLi8** [comment]
Reverted, tagging @chrisklus to close

**Comment by chrisklus** [comment]
Reverting sounds good, closing.
