### ISSUE TITLE
FormulaNode not working on screen icons

### ISSUE THREAD

**Issue by brandonLi8** [phetsims/vector-addition#78]
I am experiencing a weird bug with `Formula Node` inside of screen icons:

Right now, the screen icon passed to `Explore1d` as a test icon is :
```
new ScreenIcon( new Node().setChildren( [ new FormulaNode( 'hello world') ] ) );
```

This seems like the correct view when the icon is deselected:

![image](https://user-images.githubusercontent.com/42391580/61684764-b5d39800-acd7-11e9-9cb6-8f7ae7853b60.png)

However, when it is selected, it strangely just goes away:
![image](https://user-images.githubusercontent.com/42391580/61684817-df8cbf00-acd7-11e9-839f-2629fea5631d.png)

Can someone confirm that this is an issue or am I forgetting something?

**Comment by chrisklus** [comment]
I experienced the same problem when trying this locally. Simplifying to this:

```js
return new ScreenIcon( new FormulaNode( 'hello world' ) );
```

outputs this:

![image](https://user-images.githubusercontent.com/5618316/61729515-9e76c800-ad34-11e9-9344-2cd2172059ed.png)

![image](https://user-images.githubusercontent.com/5618316/61729531-a898c680-ad34-11e9-9df0-28bf56470c89.png)


I see normal behavior when changing the type to 'Text':

```js
return new ScreenIcon( new Text( 'hello world' ) );
```

![image](https://user-images.githubusercontent.com/5618316/61729628-de3daf80-ad34-11e9-8cf4-33bb05b6d8e6.png)

![image](https://user-images.githubusercontent.com/5618316/61729648-e7c71780-ad34-11e9-9fde-8a3980c9f9c6.png)

**Comment by arouinfar** [comment]
@brandonLi8 in #76 I said:

> Here's a rough idea of what I'm thinking for icons. I'd want the grid off, and all labels hidden.

Since the icons should not include the vector labels, there shouldn't be any need to include the `FormulaNode`.

**Comment by brandonLi8** [comment]
@arouinfar thanks for the clarification. How did I miss that?! Anyways that solves the issue for now. I'm going to keep it open for now for sims in the future that might use FormulaNode in the icon

**Comment by brandonLi8** [comment]
Closing this as this is no longer specific to Vector Addition
