### ISSUE TITLE
ControlPanel refactor

### ISSUE THREAD

**Issue by brandonLi8** [phetsims/vector-addition#79]
Currently, each screen creates its own GraphControlPanel that extends `Panel`. (for instance, `explore1DGraphControlPanel`, `equationGraphControlPanel` ...)

This works but is a little too much copy and pasting since the panels are very similar in content/appearance.

Here is a visual of the 4 graph control panels:

### Explore 1D

![image](https://user-images.githubusercontent.com/42391580/61747607-78b0e980-ad5b-11e9-92b3-6607abc8d542.png)

### Explore 2D

![image](https://user-images.githubusercontent.com/42391580/61747623-81a1bb00-ad5b-11e9-939f-598e8b2e34d1.png)

### Lab
![image](https://user-images.githubusercontent.com/42391580/61747633-87979c00-ad5b-11e9-9240-f25774d76cf2.png)

### Equation

![image](https://user-images.githubusercontent.com/42391580/61747653-8e261380-ad5b-11e9-9788-247c49203eac.png)

What should be done is to create a `GraphControlPanel` as a common view. Each screen's control panel will extend this.

`GraphControlPanel` will have options to pass the a sum checkboxes node and optional flags to include the angle checkbox and the component style radio buttons.

**Comment by brandonLi8** [comment]
This has now been implemented, and works will with stringTest = long / stringTest=x. Assigning @chrisklus  for review.

**Comment by chrisklus** [comment]
Nice, this eliminated a lot of code! Back to @brandonLi8 to close.
