### ISSUE TITLE
Vector Display Panel should displays the values and label associated with the last active vector

### ISSUE THREAD

**Issue by veillette** [phetsims/vector-addition#8]
There is a todo in VectorDisplayNode
```
      // TODO generalize to active vector
      const vector = vectors.get( 0 );
```

The VectorDisplayNode receives the model as an argument, but it arbitrarily decided to pick the first one to display its value. This should be generalized such that the panel displays the vector that is being dragged. 
Each model vector has a property called isDraggingProperty which is set to true at the beginning of a drag event.

**Comment by veillette** [comment]
The layout of the panel does not reflect the screenshot of the first screen. 
The layout of the content of the panel is currently done with a Layout box. this should be node with a series of scenery nodes that are given specific location since it is not correct to assume that the spacing of all the nodes are equal.

**Comment by brandonLi8** [comment]
I was able to display the numerical values associated labels with the active vector as well as restructuring the scenery to fit layout. I also updated the panel locations and options of the panel to better reflect the design.

We need to be a that disposes the added listener to the observableArray when a vector is disposed.

**Comment by veillette** [comment]
This feature has been implemented for the vectors and vector sum. Closing
