### ISSUE TITLE
Should vectors on equation have separate tail positions?

### ISSUE THREAD

**Issue by brandonLi8** [phetsims/vector-addition#80]
Currently, the vectors on equation screen have the same tail position for all three equation types. If a vector is moved to <5,5>, it is moved to <5,5> for all three equation types.

Is this the behavior that is desired, or should the vectors have separate tail positions for each equation type?

**Comment by arouinfar** [comment]
> Is this the behavior that is desired, or should the vectors have separate tail positions for each equation type?

@brandonLi8 I think it would be more natural for the vectors to have separate tail positions. The coefficients are scene-specific, so the vectors in the play area could potentially be quite different. It seems odd to me to shift a vector's position based on something unrelated to the scene.

**Comment by brandonLi8** [comment]
Separate tail positions have been implemented with my only commit above. Assigning @chrisklus  to review and close.

**Comment by chrisklus** [comment]
Looks good! Closing.
