### ISSUE TITLE
Creator Panel API

### ISSUE THREAD

**Issue by brandonLi8** [phetsims/vector-addition#82]
From #81, looking at the `VectorCreatorPanelSlot`, the creation of vectors could be cleaned up: 

1. In `Explore1DVectorCreatorPanel`, `Explore2DVectorCreatorPanel` ... (for each screen), the argument types are incorrect, and could be cleaned up. Also, instead of passing a separate vectorSet and graph, just the Graph could be passed (since the graph is a subtype).

2. Instead of passing the vector container and the parent screen view, just the scene node should be passed (from screen view to creator panel to creator panel slot).

3. The Vector Creator Panel Slot should tell the scene node to create a vector (since it has access to the scene node) to keep the vector node layer consistent. The creator panel slot should pass itself so the scene has access to the icon size.

4. The initial vector should be a option (with the default of <5,5>)

Edit: 
Per Code comments, this is the new implementation strategy:
```
/**
 * View for a single 'slot' on the VectorCreatorPanel (./VectorCreatorPanel.js).
 *
 * A slot creates a Vector when the icon is clicked.
 *
 * ## Slots can differ in:
 *  - Icon colors and sizes
 *  - Infinite slot versus only one vector per slot
 *  - Having symbols versus not having symbols
 *  - Icon components and initial vector components (e.g. on Explore 1D the initial vectors are horizontal/vertical
 *    while on Explore 2D the vectors are 45 degrees)
 *
 * ## Implementation of creation of Vectors:
 *  1. Once the icon is clicked, a Vector is made.
 *  2. A call to the Scene Node is made, passing the created Vector. The Scene Node then creates the subsequent views
 *     for the Vector (Vector Node and Vector Component Node), layering the views correctly and forwarding the event.
 *  3. Once the Vector indicates the Vector was dropped outside the Graph, the slot will then animate the Vector and
 *     dispose the vector, signaling to the Scene Node to dispose of the views.
 *
 * @author Brandon Li
 */
```

**Comment by brandonLi8** [comment]
This has now been integrated. Assigning @chrisklus  to review.

**Comment by chrisklus** [comment]
Nice work @brandonLi8, this implementation looks cleaner to me. Back to you to close.
