### ISSUE TITLE
Pixel Polish : Vector Label

### ISSUE THREAD

**Issue by brandonLi8** [phetsims/vector-addition#83]
Vector Addition is starting the 'Pixel Polish' process, and I thought I would start it off with the Vector Label. (this issue is more for me to track progress)

## Polishes (for the vector label only)
1. Currently, when the vector is first dropped the label is not centered:
![image](https://user-images.githubusercontent.com/42391580/61909604-dbd38500-aeef-11e9-971c-063390a4e981.png)
Strangely, this only happens on the lab screen and the values have to be on before the vector is dropped.

2. @ariel-phet suggested to increase the label font for both formula node and the text nodes by at least 25%

3. Strangely, on the equation screen, the padding of the label is off. In some cases the padding is negative:
![image](https://user-images.githubusercontent.com/42391580/61909757-34a31d80-aef0-11e9-973b-9d19ea371b0e.png) (the - sign is outside the rectangle)
This could be fixed when https://github.com/phetsims/vector-addition/issues/74#issuecomment-513848721 is addressed (putting the '-2' inside the absolute value bars)
  - But also, the vertical padding is off. It is hard to tell if the vector symbol is outside the rectangle, but there should be more padding to make the top and the bottom padding the same. This could get hard since `Formula Node` is often hard to deal with.

4. The Font of the vector symbol should be the same as the font in the inspect a vector panel

**Comment by brandonLi8** [comment]
Vector Label now doesn't have negative margins (tracked in #85). It now looks like this:
![image](https://user-images.githubusercontent.com/42391580/62151296-3e949a00-b2bd-11e9-964b-c66a71a69108.png)

The positioning of the vector label when first dropped on the lab screen is now correct with my commit above.

Polishing for the vector label is done (besides small things like font size which can be easily changed).


Assigning @chrisklus to review

**Comment by brandonLi8** [comment]
@arouinfar and I decided that the label size looks good for now, but we would like to discuss later.

Right now, the label overlaps on the 'rectangle' component style:
![image](https://user-images.githubusercontent.com/42391580/62388150-d0004800-b519-11e9-9332-e44476a299cc.png)

but it looks better on the 'triangle' component style:
![image](https://user-images.githubusercontent.com/42391580/62388220-f32af780-b519-11e9-96d6-33737610058d.png)

**Comment by chrisklus** [comment]
Looks good @brandonLi8. A couple things: 

Whenever you want to use a value if it exists, you can use 'or' instead of a ternary. For example:

```js
const myValue = valueIfItExists ? valueIfItExists : alternateValue;
```

can be simplified to

```js
const myValue = myValueIfItExists || alternateValue;
```

Also, on line 191 of Vector.js, I wasn't sure why you needed to wrap `this.fallBackSymbol`:

```js
symbol = this.symbol ? this.symbol : `${this.fallBackSymbol}`;
```

`this.symbol` and `this.fallBackSymbol` are both documented as strings, so `&{}` seems redundant.

Ready to close once you've addressed what you would like to.

**Comment by brandonLi8** [comment]
> Also, on line 191 of Vector.js, I wasn't sure why you needed to wrap this.fallBackSymbol:

Not sure why its there either, must have been a mistake.

> const myValue = valueIfItExists || alternateValue;

Wouldn't this simplify to a boolean value?

**Comment by brandonLi8** [comment]
back to @chrisklus, I'm ready to close.

**Comment by chrisklus** [comment]
Nice changes, closing.
