### ISSUE TITLE
VectorSymbol (#47) Merge

### ISSUE THREAD

**Issue by brandonLi8** [phetsims/vector-addition#85]
There are a couple of things that I would like to address all at once in this issue related to the label:
1. (from #74) Inspect a Vector Panel should display the coefficient along with the symbol, but the coefficient should be inside the absolute value bars
2. `FormulaNode` often has weird bounds that are incorrect, and I believe this is the source of the negative margins (#83)
3. The coefficient should be inside the absolute value bars for the vector label (from #74)

## Problems with formula node
- I can never get the bounds of `FormulaNode` to be correct. (#83)
- By using Formula Node, putting the coefficient inside the absolute value bars becomes more complicated.  It is desirable to keep the coefficient sans serif, and keep the symbol serif.
- Formula Nodes vector symbol is spaced weirdly vertically, as the vector symbol often is out of bounds. (See #83)

## New plans
I plan on ditching `FormulaNode` all together for the following reasons:
 - I will use the `VectorSymbolNode` from #47 for labels, but implement a coefficient as well.

## Advantages of a custom solution
- This will make all the fonts more consistent, making the absolute value bars and the coefficient sans serif but keeping the variable name serif (#70)
- will solve both the vector label and the inspect a vector panel at once
- Will fix negative margins (both horizontally and vertically)
- Will allow a more custom look (e.g. if the absolute value bars needed to be skinnier, it would be possible. )

## Disadvantages of a custom solution
- as noted from #47, using a custom solution will only be specific to Vector Addition

I plan to integrate `VectorSymbolNode` for now.

**Comment by brandonLi8** [comment]
I went ahead with the approach above bu I am still running into formula node bounds issues

![image](https://user-images.githubusercontent.com/42391580/62082366-e3f23400-b211-11e9-8e94-4d4ee1192162.png)
As you can see, the coefficient is the correct font and is placed inside the absolute value bars, but the label margin is still negative

**Comment by brandonLi8** [comment]
With, my commits above, it looks a lot better: 
![image](https://user-images.githubusercontent.com/42391580/62146680-1f910a80-b2b3-11e9-8dcc-408e8afbb80f.png)

**Comment by brandonLi8** [comment]
This has successfully been implemented, assigning @chrisklus  to review.

**Comment by pixelzoom** [comment]
Per 8/15/19 status meeting, reassigning to me.

**Comment by pixelzoom** [comment]
Looks good to me. Closing.
