### ISSUE TITLE
Should the control panel size change on stringTest?

### ISSUE THREAD

**Issue by brandonLi8** [phetsims/vector-addition#86]
From the design meeting, we decided that the control panel should increase in size when the strings get longer.

Here is the current behavior:
<img width="432" alt="Screen Shot 2019-07-31 at 10 02 33 AM" src="https://user-images.githubusercontent.com/42391580/62228391-ce4c4e00-b37a-11e9-9248-89753a0c21e7.png">

If the control panel were to increase in size, it would look something like this:
<img width="349" alt="Screen Shot 2019-07-31 at 10 01 46 AM" src="https://user-images.githubusercontent.com/42391580/62228637-4dda1d00-b37b-11e9-8b1e-fad0eb97c37b.png">

## here is why I think it shouldn't change in size
- As you can see from the second screen shot, the x axis label and the control panel overlap, meaning that if the axis was dragged up, the label wouldn't be visible.
- Screen shot 1 looks much cleaner (in my opinion)
- This is the behavior in gas properties, and it should be consistent
<img width="579" alt="Screen Shot 2019-07-31 at 10 13 01 AM" src="https://user-images.githubusercontent.com/42391580/62228988-f7211300-b37b-11e9-8ff3-084782dfa395.png">
- From an implementation standpoint, it becomes more complicated since the length of the line (above the components text) is unknown.

**Comment by brandonLi8** [comment]
Decided with @arouinfar  to make it wider but not as wide as the second ss.

**Comment by brandonLi8** [comment]
With the commit above, the panel  is now correct.

Normal
![image](https://user-images.githubusercontent.com/42391580/62641370-a0c64e00-b900-11e9-9c6c-a7f562872fa8.png)

long
![image](https://user-images.githubusercontent.com/42391580/62641302-88563380-b900-11e9-8471-d93fa718921f.png)

x
![image](https://user-images.githubusercontent.com/42391580/62641330-94da8c00-b900-11e9-9c8c-b37e612ad098.png)

**Comment by brandonLi8** [comment]
Assigning @chrisklus to review

**Comment by chrisklus** [comment]
Implementation looks good, back to @brandonLi8 to close.
