### ISSUE TITLE
VectorComponentsNode code review

### ISSUE THREAD

**Issue by brandonLi8** [phetsims/vector-addition#9]
Martin, 
I have finished the vectorComponentsNode view. It works for all 4 styles and I fixed the issue where the components go off the axis on the 'ON_AXIS' mode. 

I feel that my approach was relatively clean by using an object to toggle the different enumeration states, but it could use a quick code review.

**Comment by brandonLi8** [comment]
Upon further consideration, my approach should be changed. Under the componentStyles enumeration property, I unlink the previous vector component style. For the moment, I unlinked all:
'vector.vectorProperty.unlinkAll();' but this shouldn't be there because other views will be using the same property.

**Comment by veillette** [comment]
Good work, I'm attaching a few commits that were mistagged https://github.com/phetsims/vector-addition/commit/36481241cf51ee146844510bd4470ac2abf5f9c1, https://github.com/phetsims/vector-addition/commit/f32f8de47bcc3762fe1bc6cad3d5fa1ba842637a, https://github.com/phetsims/vector-addition/commit/f32f8de47bcc3762fe1bc6cad3d5fa1ba842637a

**Comment by veillette** [comment]
I this commit,  1fa5be988a20c2b258aad93a0fe61b404dbc6847 , I used a multilink property to update the vector components.

**Comment by veillette** [comment]
Most of the logic resides in Vector.
