### ISSUE TITLE
rendering solid vs dashed vectors

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/vector-addition#90]
PhET currently has `ArrowNode` for solid arrows and `LineArrowNode` for dashed lines, but nothing that does both.  @ariel-phet mentioned that _Vector Addition_ uses solid arrows for vectors, and dashed arrows for vector component, and that is causing some complication in the implementation.  He asked me to discuss with @brandonLi8, so I'm creating this issue to remind myself.

**Comment by brandonLi8** [comment]
To give some background, urrently, on master, everything uses `ArrowNode`. However, on the branch `dashedComponent`, I experimented with `LineArrowNode` for dashing components.

See https://github.com/phetsims/vector-addition/issues/84 for more context.

**Comment by pixelzoom** [comment]
Thanks for the pointer to https://github.com/phetsims/vector-addition/issues/84.  Let's discuss there.  Closing.
