### ISSUE TITLE
investigate strategies to avoid overlapping labels

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/vector-addition#93]
... as in this situation in the _Explore 1D_ screen:

<img width="377" alt="screenshot_1312" src="https://user-images.githubusercontent.com/3046552/63112272-093eac00-bf4d-11e9-8039-c8e65bcb5a52.png">

If it's relatively easy to address, great.  If not, students can just move the vector.

1D case is more important than 2D case.  And this issue is relatively low priority, could publish as is.

**Comment by pixelzoom** [comment]
It looks like the location chosen for labels didn't consider the angle indicator. For example:

<img width="324" alt="screenshot_1500" src="https://user-images.githubusercontent.com/3046552/65534940-acc09c00-debd-11e9-8eeb-a74a70c6535a.png">

**Comment by pixelzoom** [comment]
Deciding where labels should be based on the location of other vectors is a difficult problem in general, and not feasible for the current implementation.   It can do more harm than good, sometimes resulting in labels jumping around while you're moving something. 

So I think we should limit this issue to a single vector.  That is, prevent the label and angle indicator from overlapping.

**Comment by pixelzoom** [comment]
In the above commits, I adjusted the label position so that it never overlaps the angle indicator.  Examples for all of the cases are shown below.

@arouinfar @arouinfar I'm not sure where to go from here.  Please advise.

<img width="222" alt="screenshot_1506" src="https://user-images.githubusercontent.com/3046552/65616761-d4c10580-df78-11e9-953b-1f857de68c58.png">
<img width="193" alt="screenshot_1515" src="https://user-images.githubusercontent.com/3046552/65616906-0d60df00-df79-11e9-8893-4ead8ebe5a89.png">
<img width="178" alt="screenshot_1507" src="https://user-images.githubusercontent.com/3046552/65616768-d7bbf600-df78-11e9-81fe-3ba84df90abf.png">
<img width="200" alt="screenshot_1508" src="https://user-images.githubusercontent.com/3046552/65616776-db4f7d00-df78-11e9-90ac-d4cb54878944.png">
<img width="208" alt="screenshot_1509" src="https://user-images.githubusercontent.com/3046552/65616783-ddb1d700-df78-11e9-86b1-d0fa6e15d344.png">
<img width="213" alt="screenshot_1510" src="https://user-images.githubusercontent.com/3046552/65616791-e0acc780-df78-11e9-8586-7d3528dbf4a3.png">
<img width="207" alt="screenshot_1511" src="https://user-images.githubusercontent.com/3046552/65616794-e1ddf480-df78-11e9-8399-bf1ef426348c.png">
<img width="176" alt="screenshot_1512" src="https://user-images.githubusercontent.com/3046552/65616802-e4d8e500-df78-11e9-8822-2532ab20fdc5.png">
<img width="221" alt="screenshot_1513" src="https://user-images.githubusercontent.com/3046552/65616804-e60a1200-df78-11e9-8d5a-a615b5e096e1.png">
<img width="175" alt="screenshot_1514" src="https://user-images.githubusercontent.com/3046552/65616915-12259300-df79-11e9-88ed-f00bbb871b07.png">

**Comment by ariel-phet** [comment]
Discussed with @pixelzoom over slack, since this would be a hard problem to address in general, what has been done so far seems perfectly sufficient for 1.0

**Comment by pixelzoom** [comment]
@arouinfar if you agree with https://github.com/phetsims/vector-addition/issues/93#issuecomment-535092297, then please close.  Otherwise please advise on how to proceed.

**Comment by arouinfar** [comment]
> Discussed with @pixelzoom over slack, since this would be a hard problem to address in general, what has been done so far seems perfectly sufficient for 1.0

Agreed, let's close.
