### ISSUE TITLE
sum vector that corresponds to selected vector should be in front

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/vector-addition#94]
Discussed with @ariel-phet.

In this screenshot, we've determined that there are 2 ways to get the same sum. The blue vector is selected, but the blue sum vector is behind the red sum vector.  We'd like the blue sum vector to be in front of the red sum vector.

<img width="732" alt="screenshot_1314" src="https://user-images.githubusercontent.com/3046552/63113313-7ce1b880-bf4f-11e9-9e26-c8158543a950.png">

**Comment by pixelzoom** [comment]
This is really only an issue in the _Lab_ screen, since it's the only screen that has 2 sum vectors.

**Comment by pixelzoom** [comment]
Discussed with @arouinfar.  Moving the entire set of vectors to the front is actually preferable, since the case shown in https://github.com/phetsims/vector-addition/issues/94#issue-481253895 could happen with non-sum vectors.   So in the previous commit, selecting a vector moves the entire set of vectors (blue or red) to the front.  The vector that was selected (and its components) will be on top.

@arouinfar please review in master.

**Comment by pixelzoom** [comment]
Probably also good to have @ariel-phet take a look, since this issue was originated during a discussion with him.

**Comment by arouinfar** [comment]
@pixelzoom this is looking good in master. @ariel-phet do you want to also take a look before we move into QA testing?

**Comment by arouinfar** [comment]
Reviewed over Zoom with @ariel-phet, and he also gave this a 👍
