### ISSUE TITLE
increase space between arrow and label

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/vector-addition#95]
Increase space slightly between arrow and label, so that label doesn't overlap the arrow's head.

<img width="135" alt="screenshot_1315" src="https://user-images.githubusercontent.com/3046552/63114122-4016c100-bf51-11e9-9ecb-6a7c2940f0f8.png">

**Comment by brandonLi8** [comment]
@pixelzoom, this is a constant in the `VectorAdditionConstants` file, called "VECTOR_LABEL_OFFSET", so it should take 2 seconds to fix.

**Comment by pixelzoom** [comment]
Thanks for the pointer @brandonLi8, that saved me some time.
