### ISSUE TITLE
model.md

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/vector-addition#96]
Describe the model in [model.md](https://github.com/phetsims/vector-addition/blob/master/doc/model.md).

**Comment by pixelzoom** [comment]
@arouinfar I'm at a loss for what to include for the model description.  Do you have any suggestions?

**Comment by pixelzoom** [comment]
I'm feeling inspired today, so I'll make a pass at this.

**Comment by arouinfar** [comment]
A few things off the top of my head that we might want to include
* Cartesian vs. Polar
* Tail restricted to grid, but tip can spill over
* **c** and **f** are always derived (Equation screen)

**Comment by pixelzoom** [comment]
@arouinfar ready for review.

**Comment by arouinfar** [comment]
@pixelzoom nice work! I cannot think of anything else to add.
