### ISSUE TITLE
implementation-notes.md

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/vector-addition#97]
Describe the implementation in [implementation-notes.md](https://github.com/phetsims/vector-addition/blob/master/doc/implementation-notes.md).

**Comment by brandonLi8** [comment]
I would like to add some notes...

- [ ] When using the `Vector2` module, "position" or "point" refers to the model coordinate (which is a graph coordinate) and "location" refers to the view coordinate
- [ ] assertions are made to check types of arguments, and should be kept like this when possible (similar to gas-properties)
- [ ] terminology of component (scalar) and comonentVector (vector)

That's all I can think of at the moment, but I will comment things if anything comes up in my head.

**Comment by pixelzoom** [comment]
@brandonLi8 said:
> - [ ]  When using the Vector2 module, "position" or "point" refers to the model coordinate (which is a graph coordinate) and "location" refers to the view coordinate

For future reference, we try to keep the nouns consistent and quality view-specific quantities with an adjective.  For example `location` and `viewLocation`, or `position` and `viewPosition`.  This qualification is similar(in spirit)  to class names, e.g.`Vector` and `VectorNode`.

**Comment by pixelzoom** [comment]
@brandonLi8 said:
> - [ ]  assertions are made to check types of arguments, and should be kept like this when possible (similar to gas-properties)

@brandonLi8 (and @veillette, if applicable) did you find this to be helpful, and worth the effort?  In gas-properties, I noted that it felt like overkill, but it was helpful.   In vector-addition, I found it to be even more helpful, since I was working with someone else's code.

**Comment by pixelzoom** [comment]
@brandonLi8 said:
> - [ ]  assertions are made to check types of arguments, and should be kept like this when possible (similar to gas-properties)

In [gas-properties/implementation-notes.md](https://github.com/phetsims/gas-properties/blob/master/doc/implementation-notes.md), I noted:
> While this may look like overkill, it did catch quite a few problems during refactoring, and was a net gain.

@brandonLi8 (and @veillette, if applicable) did you find this to be helpful, and worth the effort? In vector-addition, I found it to be even more helpful, since I was working with someone else's code.

**Comment by brandonLi8** [comment]
> @brandonLi8 (and @veillette, if applicable) did you find this to be helpful, and worth the effort?

Personally, I found it to be helpful and worth it especially when API's change or when something significant in the sim changes.

**Comment by brandonLi8** [comment]
@pixelzoom I noticed that the link to `VectorAdditionQueryParameters` in `implementation-notes.md` was wrong.

**Comment by pixelzoom** [comment]
Thanks @brandonLi8, `VectorAdditionQueryParameters` link is fixed.

**Comment by pixelzoom** [comment]
This still needs to be finished, called out in code review #231.

**Comment by pixelzoom** [comment]
@veillette volunteered to review this when I'm done. Thanks!

**Comment by pixelzoom** [comment]
I feel like I'm at a good stopping point with this. @veillette could you please review at your convenience? Feel free to correct typos, add info, etc.

**Comment by pixelzoom** [comment]
@brandonLi8 Your input is also welcome, if you have time (no pressure).

**Comment by pixelzoom** [comment]
Note to self: Not super important, but it might be nice to cherry pick this to the 1.0 branch when this issue is closed.

**Comment by veillette** [comment]
I reviewed the implementation notes. I addressed a few typos and corrected the URL.

**Comment by pixelzoom** [comment]
Thanks @veillette!

**Comment by pixelzoom** [comment]
Assigning back to me to cherry-pick to 1.0 branch.

**Comment by veillette** [comment]
The notes are quite thorough. I don't have anything to add to them. Unassigning.

**Comment by pixelzoom** [comment]
Thanks again @veillette. Sorry that I reassigned prematurely.

**Comment by pixelzoom** [comment]
Cherry pick done.

```
% git checkout 1.0
% git checkout master -- doc/implementation-notes.md 
% git commit -m '#97 cherry-pick to 1.0'
% git push
```

Closing.
