### ISSUE TITLE
credits

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/vector-addition#98]
Finalize the credits in vector-addition-main.js.

**Comment by pixelzoom** [comment]
Below is a first pass at the credits, based on who is listed in the design document, and who is listed as `@author` in the code.

<img width="558" alt="screenshot_1316" src="https://user-images.githubusercontent.com/3046552/63115847-64749c80-bf55-11e9-9659-86fd71c15c84.png">

**Comment by pixelzoom** [comment]
Below is a first pass at the credits, based on who is listed in the design document, and who is listed as `@author` in the code.  @arouinfar please advise on any non-QA changes.  (QA credits will be addressed during RC testing.)

<img width="677" alt="screenshot_1346" src="https://user-images.githubusercontent.com/3046552/63461707-730bf980-c416-11e9-93ab-0c2cdca8b035.png">

**Comment by pixelzoom** [comment]
We've added a new _Vector Addition: Equations_ sim, which is the Equations screen only.  Since this is a totally derivative sim, it should have the same credits as _Vector Addition_.  The above commit makes that so.

**Comment by pixelzoom** [comment]
@arouinfar Do the non-QA credits look complete and correct?

@KatieWoe Who should be added to QA credits?

**Comment by pixelzoom** [comment]
Sorry @arouinfar, I see that you already addressed non-QA credits.

**Comment by KatieWoe** [comment]
So far myself and Megan Lai.  However, we've just started it so I'm certain more will be added.

**Comment by KatieWoe** [comment]
QA Credits so far: Jaspe Arias, Logan Bray, Megan Lai, Liam Mulhall, Kathryn Woessner

**Comment by pixelzoom** [comment]
Revised QA credits pushed to master and 1.0 branches.

**Comment by pixelzoom** [comment]
@KatieWoe any additional credits to add before the next RC?

**Comment by KatieWoe** [comment]
I don't believe so.  Thanks

**Comment by KatieWoe** [comment]
For https://github.com/phetsims/QA/issues/451, Jacob still needs to be added.

**Comment by pixelzoom** [comment]
I wasn't sure how this happened, because I remember copy-pasting from https://github.com/phetsims/vector-addition/issues/98#issuecomment-548124798 directly into the code.  Discussing with @KatieWoe on Slack, we determined that she edited the comment and added Jacob after I had made the code changes.  

Easy enough to fix, but it also affects phetsims/QA#452, and will need to be rolled into both sims.  And we'll have to decide whether 1.0.0-rc.3 is needed.

**Comment by pixelzoom** [comment]
I've added Jacob to the QA credits in master and 1.0.  @KatieWoe please verify in master.

**Comment by KatieWoe** [comment]
Looks good on master

**Comment by pixelzoom** [comment]
To be verified in 1.0.0-rc.3, or possibly just published if this is the only issue found for phetsims/QA#451 and phetsims/QA#452.

**Comment by pixelzoom** [comment]
Slack:

Chris Malley 5:00 PM
Since https://github.com/phetsims/vector-addition/issues/98 (credits) is the sole issue that didn’t pass 1.0.0-rc.2, are you comfortable with me publishing 1.0.0 without another RC?   If you inspect https://github.com/phetsims/vector-addition/commits/1.0, you can see that adding Jacob’s name is the only commit on the 1.0 branch since 1.0.0-rc.2 was published.

Kathryn Woessner:office: 5:00 PM
Sounds good to me

**Comment by pixelzoom** [comment]
Over in https://github.com/phetsims/natural-selection/issues/2, we discussed the convention for in corporation Java credits into HTML5 sims.

@ariel-phet's said:
> For ports, we list the original lead designer in the Lead Design, but generally if there have been significant changes, we put the HTML5 lead first. (So for instance, current Vector Addition lists Mike Dubson first in lead design, but probably Amy should be listed first there)
>
> For software development, if the code is basically the same as the Legacy code, it seems correct to include the original software developer, but certainly recently, most of the code has basically been written from scratch. I think this is mostly developer discretion.
> 
> In team, we just list people alphabetically.
>
> I cannot say I have personally been too worried as long as people are listed (but that is because I personally don't care about credits too much). But the above is my understanding of our decisions.

I discussed "Lead Designer" credits with @arouinfar on Slack, and she said "It's fine as is. Thanks for checking."

For the "Software Development" credits...  There is no legacy code in this sim, and I doubt that the Flash implementation was even consulted.   So the credits include the developers who were involved in the HTML5 implementation.
