### ISSUE TITLE
adding values to tick marks

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/vector-addition#99]
Discussed with @ariel-phet. Consider adding values to the graph's tick marks, at every 10 units.  It's not obvious what the units are, especially when the grid is turned off.

**Comment by pixelzoom** [comment]
Before I do this, checking with @arouinfar.   Does this sound like a reasonable addition?

**Comment by pixelzoom** [comment]
8/22/19 design meeting: do it

**Comment by pixelzoom** [comment]
Tick mark labels have been added at intervals of 10 units.  The current tick label color is `rgb( 130, 130, 130 )`, so that that aren't so obtrusive.   Offset of labels from the axes is 15 pixels.

@arouinfar please review in master.

**Comment by arouinfar** [comment]
Looks great @pixelzoom!
